"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Plus, Target } from "lucide-react";
import { JOB_PROFILES } from "../../data/jobData";
import { getManageableEmployees } from "../../utils/hierarchy";
import { getStorageData, setStorageData, STORAGE_KEYS } from "../../utils/storage";
import { extractCompetencyMap } from "../../../lib/hr/talentPotential";
import { useNotifications } from "../../../context/NotificationContext";

interface DevelopmentPlan {
  id: string;
  employee: string;
  competency?: string;
  goal: string;
  action: string;
  actionType: "İş Üstünde" | "Koçluk" | "Proje" | "Formal Eğitim" | "Okuma / Araştırma";
  successMetric: string;
  dueDate?: string;
  status: "Planlandı" | "Devam Ediyor" | "Tamamlandı";
  createdBy: string;
  createdAt: string;
  transferredToTraining?: boolean;
}

const ACTION_TYPES: DevelopmentPlan["actionType"][] = ["İş Üstünde","Koçluk","Proje","Formal Eğitim","Okuma / Araştırma"];
const LABEL_TO_CODE:Record<string,string>={"Dijital Okuryazarlık":"DIG","Analitik Düşünme":"ANA","Sonuç Odaklılık":"RES","Detaylara Özen":"DET","Sürekli Öğrenme":"LRN","Etik ve Uyum":"ETH","Öz-Disiplin":"DIS","Stratejik Bakış":"STR","Takım Çalışması":"TEA","İletişim Becerileri":"COM"};

export default function GelisimPage(){
  const {addNotification,showToast}=useNotifications();
  const [user,setUser]=useState<any>(null);const[orgData,setOrgData]=useState<any[]>([]);const[plans,setPlans]=useState<DevelopmentPlan[]>([]);const[assessments,setAssessments]=useState<any[]>([]);const[selectedName,setSelectedName]=useState("");const[form,setForm]=useState({competency:"",goal:"",action:"",actionType:"İş Üstünde" as DevelopmentPlan["actionType"],successMetric:"",dueDate:""});
  useEffect(()=>{const u=getStorageData(STORAGE_KEYS.CURRENT_USER,null);setUser(u);setOrgData(getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]));setPlans(getStorageData<DevelopmentPlan[]>(STORAGE_KEYS.DEVELOPMENT_PLANS,[]));setAssessments(getStorageData<any[]>(STORAGE_KEYS.HISTORY_360,[]));},[]);
  const role=String(user?.role||"").toUpperCase();const employees=useMemo(()=>{if(!user)return[];if(role==="CEO"||role==="IK")return orgData;try{return getManageableEmployees(user,orgData)}catch{return[]}},[user,orgData,role]);
  useEffect(()=>{if(!selectedName&&employees.length)setSelectedName(employees[0]["Ad Soyad"])},[employees,selectedName]);
  const selectedOrg=orgData.find((e)=>e["Ad Soyad"]===selectedName)||{};const latestAssessment=assessments.find((e)=>(e.Personel||e.target)===selectedName)||{};const selected={...selectedOrg,...latestAssessment};
  const target=JOB_PROFILES[selectedOrg.Pozisyon]||{};const current=extractCompetencyMap(selected);const gaps=Object.entries(target).map(([label,expected])=>{const code=LABEL_TO_CODE[label]||label;const actual=Number(current[code]||0);return{label,actual,expected:Number(expected),gap:Number(expected)-actual}}).filter(i=>i.actual>0&&i.gap>0).sort((a,b)=>b.gap-a.gap);
  const employeePlans=plans.filter((p)=>p.employee===selectedName);
  const savePlans=(next:DevelopmentPlan[])=>{setPlans(next);setStorageData(STORAGE_KEYS.DEVELOPMENT_PLANS,next);window.dispatchEvent(new CustomEvent("dataUpdated"));};
  const create=(e:FormEvent)=>{e.preventDefault();if(!selectedName||!form.goal.trim()||!form.action.trim()||!form.successMetric.trim())return;const plan:DevelopmentPlan={id:`dev-${Date.now()}`,employee:selectedName,competency:form.competency||undefined,goal:form.goal.trim(),action:form.action.trim(),actionType:form.actionType,successMetric:form.successMetric.trim(),dueDate:form.dueDate||undefined,status:"Planlandı",createdBy:user?.name||user?.username||"",createdAt:new Date().toISOString()};savePlans([plan,...plans]);addNotification(`Yeni gelişim aksiyonu tanımlandı: ${plan.goal}`,"info",{targetUser:selectedName,link:"/gelisim",source:"development"});setForm({competency:"",goal:"",action:"",actionType:"İş Üstünde",successMetric:"",dueDate:""});};
  const updateStatus=(id:string,status:DevelopmentPlan["status"])=>savePlans(plans.map(p=>p.id===id?{...p,status}:p));
  const sendToTraining=(plan:DevelopmentPlan)=>{const trainingAssignments=getStorageData<any[]>(STORAGE_KEYS.TRAINING_ASSIGNMENTS,[]);if(trainingAssignments.some((a)=>a.sourceDevelopmentPlanId===plan.id))return showToast("Bu aksiyon zaten Eğitim modülüne aktarıldı.","info");const assignment={id:`training-${Date.now()}`,employee:plan.employee,trainingId:`dev-${plan.id}`,trainingName:plan.action,source:"Gelişim Planı",sourceDevelopmentPlanId:plan.id,assignedBy:user?.name||"",assignedAt:new Date().toISOString(),dueDate:plan.dueDate,status:"Atandı"};setStorageData(STORAGE_KEYS.TRAINING_ASSIGNMENTS,[assignment,...trainingAssignments]);savePlans(plans.map(p=>p.id===plan.id?{...p,transferredToTraining:true}:p));addNotification(`${plan.action} eğitimi Eğitim modülüne aktarıldı.`,"info",{targetUser:plan.employee,link:"/egitim",source:"development"});};
  return <div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-600">Gelişim planlama</p><h1 className="mt-1 text-2xl font-semibold">Gelişim Planı</h1><p className="mt-1 text-sm text-slate-500">Bu ekran “neyi geliştirmeliyim, hedefim ne, hangi aksiyonu yapmalıyım?” sorularını yönetir. Eğitimin atanması ve tamamlanma takibi Eğitim modülündedir.</p></div>
  <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><div className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="text-xs font-medium text-slate-500">Çalışan<select value={selectedName} onChange={(e)=>setSelectedName(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-2.5 text-sm">{employees.map((e:any)=><option key={e.id??e["Ad Soyad"]}>{e["Ad Soyad"]}</option>)}</select></label><div className="mt-4 rounded-xl bg-emerald-50 p-3"><p className="text-xs font-semibold text-emerald-900">{selectedOrg.Pozisyon||"Pozisyon"}</p><p className="mt-1 text-xs text-emerald-700">{gaps.length} ölçülebilir yetkinlik açığı</p></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-emerald-600"/><h2 className="text-sm font-semibold">Öncelikli gelişim alanları</h2></div><div className="mt-3 space-y-2">{gaps.slice(0,5).map(g=><button key={g.label} onClick={()=>setForm({...form,competency:g.label,goal:`${g.label} yetkinliğini rol hedefi olan ${g.expected.toFixed(1)} seviyesine yaklaştırmak`})} className="w-full rounded-xl bg-slate-50 p-3 text-left text-xs hover:bg-emerald-50"><div className="flex justify-between"><span className="font-medium">{g.label}</span><span className="font-semibold text-red-600">-{g.gap.toFixed(1)}</span></div><p className="mt-1 text-slate-400">{g.actual.toFixed(1)} → hedef {g.expected.toFixed(1)}</p></button>)}{!gaps.length&&<p className="text-xs text-slate-500">Yetkinlik verisi veya rol hedefi bulunmuyor.</p>}</div></div></div>
  <form onSubmit={create} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Plus className="h-4 w-4 text-emerald-600"/><h2 className="text-sm font-semibold">Gelişim aksiyonu oluştur</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Yetkinlik / alan"><input value={form.competency} onChange={e=>setForm({...form,competency:e.target.value})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"/></Field><Field label="Aksiyon tipi"><select value={form.actionType} onChange={e=>setForm({...form,actionType:e.target.value as any})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm">{ACTION_TYPES.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Gelişim hedefi"><textarea value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})} rows={3} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"/></Field><Field label="Aksiyon"><textarea value={form.action} onChange={e=>setForm({...form,action:e.target.value})} rows={3} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"/></Field><Field label="Başarı ölçütü"><input value={form.successMetric} onChange={e=>setForm({...form,successMetric:e.target.value})} placeholder="Örn. 90 gün içinde proje sunumu" className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"/></Field><Field label="Son tarih"><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"/></Field></div><button className="mt-4 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Aksiyonu ekle</button></form></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Aktif gelişim planı</h2><p className="mt-1 text-xs text-slate-500">Formal eğitim seçilen aksiyonlar Eğitim modülüne aktarılabilir.</p></div><Link href="/egitim" className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700">Eğitim modülü <ArrowRight className="h-3.5 w-3.5"/></Link></div><div className="mt-4 space-y-3">{employeePlans.length?employeePlans.map(p=><div key={p.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700">{p.actionType}</span>{p.competency&&<span className="text-xs text-slate-400">{p.competency}</span>}</div><h3 className="mt-2 text-sm font-semibold">{p.goal}</h3><p className="mt-1 text-xs text-slate-600">Aksiyon: {p.action}</p><p className="mt-1 text-xs text-slate-400">Ölçüt: {p.successMetric}{p.dueDate?` · Son tarih ${p.dueDate}`:""}</p></div><select value={p.status} onChange={e=>updateStatus(p.id,e.target.value as any)} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs"><option>Planlandı</option><option>Devam Ediyor</option><option>Tamamlandı</option></select></div>{p.actionType==="Formal Eğitim"&&<button onClick={()=>sendToTraining(p)} disabled={p.transferredToTraining} className="mt-3 rounded-lg bg-violet-50 px-3 py-2 text-xs font-semibold text-violet-700 disabled:opacity-50">{p.transferredToTraining?"Eğitime aktarıldı":"Eğitim modülüne aktar"}</button>}</div>):<p className="py-8 text-center text-sm text-slate-500">Henüz gelişim aksiyonu yok.</p>}</div></div></div>}
function Field({label,children}:{label:string;children:any}){return <label className="text-xs font-medium text-slate-600">{label}<div className="mt-1">{children}</div></label>}
