import type { UserRole } from "../../app/data/roles";
import { hasAccess, mapToUserRole } from "../../app/data/roles";
import { activePerformanceCycle, canEditPerformance, ensurePerformanceCycle, PERFORMANCE_STAGE_LABELS } from "./performanceCycle";

export type DataScope = "NONE" | "SELF" | "DIRECT_REPORTS" | "DEPARTMENT" | "COMPANY" | "ASSIGNED";
export type SensitiveDomain = "salary" | "talent" | "succession";
export type ModuleKey = "dashboard"|"decision"|"leave"|"experience"|"organization"|"jobArchitecture"|"performance"|"calibration"|"talent"|"skillsGraph"|"training"|"development"|"developmentAnalytics"|"career"|"succession"|"salary"|"compensationFairness"|"recruitment"|"assessment"|"team"|"onboarding"|"admin"|"governance"|"turkiyeCompliance"|"integrations"|"dataImport"|"executiveReports"|"managerSalary"|"accessArchitecture";
export interface CompanyAccessPolicy { version:2; moduleOverrides:Partial<Record<UserRole,Partial<Record<ModuleKey,boolean>>>>; performance:{ secondManagerCanEvaluate:boolean; hrCanOverride:boolean; hrOverrideRequiresReason:boolean; }; }
export interface AccessUser { role?:string; name?:string; dept?:string; department?:string; [key:string]:any; }
export interface AccessEmployee { "Ad Soyad"?:string; Departman?:string; "Yönetici 1"?:string; "Yönetici 2"?:string; [key:string]:any; }
export const ACCESS_POLICY_STORAGE_KEY="hr_access_policy_v2";
export const DEFAULT_COMPANY_ACCESS_POLICY:CompanyAccessPolicy={version:2,moduleOverrides:{},performance:{secondManagerCanEvaluate:true,hrCanOverride:false,hrOverrideRequiresReason:true}};
export const MODULE_DEFINITIONS:Array<{key:ModuleKey;label:string;route:string;sensitive?:SensitiveDomain}>=[
  {key:"dashboard",label:"Yönetici Özeti",route:"/dashboard"},{key:"decision",label:"Karar Motoru",route:"/karar-merkezi"},{key:"leave",label:"İzin Yönetimi",route:"/izinler"},{key:"experience",label:"Çalışan Deneyimi",route:"/calisan-deneyimi"},{key:"organization",label:"Çalışanlar & Organizasyon",route:"/organizasyon"},{key:"jobArchitecture",label:"Rol & Yetkinlik Mimarisi",route:"/rol-mimarisi"},{key:"performance",label:"Performans & Yetkinlik",route:"/degerlendirme"},{key:"calibration",label:"Performans Kalibrasyonu",route:"/kalibrasyon"},{key:"talent",label:"Yetenek & 9-Box",route:"/yetenek-matrisi",sensitive:"talent"},{key:"skillsGraph",label:"Yetkinlik Haritası",route:"/yetkinlik-haritasi",sensitive:"talent"},{key:"training",label:"Eğitim",route:"/egitim"},{key:"development",label:"Gelişim Planı",route:"/gelisim"},{key:"developmentAnalytics",label:"Gelişim Etkinliği",route:"/gelisim-analitigi"},{key:"career",label:"Kariyer Yolu",route:"/kariyer"},{key:"succession",label:"Halefiyet & Yedekleme",route:"/yedekleme",sensitive:"succession"},{key:"salary",label:"Ücret Karar Merkezi",route:"/maas",sensitive:"salary"},{key:"compensationFairness",label:"Ücret Adaleti & Sıkışma",route:"/ucret-adaleti",sensitive:"salary"},{key:"managerSalary",label:"Yönetici Ücret Talepleri",route:"/yonetici/maas-talep"},{key:"recruitment",label:"İşe Alım",route:"/ise-alim"},{key:"assessment",label:"Yetkinlik Testi",route:"/aday-testi"},{key:"team",label:"Ekip",route:"/ekip-yonetimi"},{key:"onboarding",label:"FutureHR Kurulum",route:"/kurulum"},{key:"governance",label:"Güven & KVKK",route:"/admin/guven-kvkk"},{key:"turkiyeCompliance",label:"Türkiye Uyum Katmanı",route:"/turkiye-uyum"},{key:"integrations",label:"Entegrasyon Merkezi",route:"/admin/entegrasyonlar"},{key:"dataImport",label:"Veri Aktarımı",route:"/admin/veri-aktarimi"},{key:"executiveReports",label:"Yönetici Raporları",route:"/yonetici-raporlari"},{key:"admin",label:"Kullanıcı & Yetki",route:"/admin"},{key:"accessArchitecture",label:"Yetki Mimarisi",route:"/ayarlar/yetki-mimarisi"},
];
export const SENSITIVE_SCOPE_BY_ROLE:Record<SensitiveDomain,Record<UserRole,DataScope>>={salary:{ceo:"COMPANY",hr_admin:"COMPANY",director:"NONE",manager:"NONE",employee:"NONE"},talent:{ceo:"COMPANY",hr_admin:"COMPANY",director:"NONE",manager:"NONE",employee:"NONE"},succession:{ceo:"COMPANY",hr_admin:"COMPANY",director:"NONE",manager:"NONE",employee:"NONE"}};
export function loadCompanyAccessPolicy():CompanyAccessPolicy{if(typeof window==="undefined")return DEFAULT_COMPANY_ACCESS_POLICY;try{const raw=localStorage.getItem(ACCESS_POLICY_STORAGE_KEY);if(!raw)return DEFAULT_COMPANY_ACCESS_POLICY;const parsed=JSON.parse(raw) as Partial<CompanyAccessPolicy>;return{...DEFAULT_COMPANY_ACCESS_POLICY,...parsed,moduleOverrides:parsed.moduleOverrides||{},performance:{...DEFAULT_COMPANY_ACCESS_POLICY.performance,...(parsed.performance||{})},version:2};}catch{return DEFAULT_COMPANY_ACCESS_POLICY;}}
export function saveCompanyAccessPolicy(policy:CompanyAccessPolicy){if(typeof window==="undefined")return;localStorage.setItem(ACCESS_POLICY_STORAGE_KEY,JSON.stringify({...policy,version:2}));window.dispatchEvent(new CustomEvent("accessPolicyUpdated"));}
export function moduleForPath(pathname:string):ModuleKey|null{const normalized=decodeURIComponent(pathname||"/");const match=[...MODULE_DEFINITIONS].sort((a,b)=>b.route.length-a.route.length).find(item=>normalized===item.route||normalized.startsWith(item.route+"/"));return match?.key||null;}
export function canAccessRoute(role:UserRole|null|undefined,pathname:string){if(!role)return false;if(!hasAccess(role,pathname))return false;const key=moduleForPath(pathname);if(!key)return hasAccess(role,pathname);const override=loadCompanyAccessPolicy().moduleOverrides?.[role]?.[key];return override!==false;}
export function canConfigureAccess(role:UserRole|null|undefined){return role==="ceo";} export function canViewAccessArchitecture(role:UserRole|null|undefined){return role==="ceo"||role==="hr_admin";} export function getSensitiveScope(role:UserRole|null|undefined,domain:SensitiveDomain):DataScope{return role?SENSITIVE_SCOPE_BY_ROLE[domain][role]||"NONE":"NONE";}
export function getManagerRelationship(user:AccessUser|null,employee:AccessEmployee|null):"Yönetici 1"|"Yönetici 2"|null{const name=String(user?.name||"").trim();if(!name||!employee)return null;if(String(employee["Yönetici 1"]||"").trim()===name)return"Yönetici 1";if(String(employee["Yönetici 2"]||"").trim()===name)return"Yönetici 2";return null;}
export function getPerformanceViewTargets(user:AccessUser|null,employees:AccessEmployee[]){if(!user)return[];const role=mapToUserRole(String(user.role||""));if(role==="hr_admin")return employees;if(role==="ceo"||role==="director"||role==="manager")return employees.filter(e=>getManagerRelationship(user,e)!==null);return employees.filter(e=>String(e["Ad Soyad"]||"")===String(user.name||""));}
export function canEvaluateEmployee(user:AccessUser|null,employee:AccessEmployee|null):{allowed:boolean;relation:string|null;override:boolean;reason?:string}{
  if(!user||!employee)return{allowed:false,relation:null,override:false,reason:"Kullanıcı veya çalışan bulunamadı."};
  if(typeof window!=="undefined"){const cycle=activePerformanceCycle(ensurePerformanceCycle());if(cycle&&!canEditPerformance(cycle))return{allowed:false,relation:null,override:false,reason:`${cycle.name} şu anda ${PERFORMANCE_STAGE_LABELS[cycle.stage]} aşamasında; yeni puan girişi kapalı.`};}
  const role=mapToUserRole(String(user.role||""));const policy=loadCompanyAccessPolicy();if(role==="hr_admin")return policy.performance.hrCanOverride?{allowed:true,relation:"İK Override",override:true}:{allowed:false,relation:null,override:false,reason:"İK sonuçları izler; varsayılan politikada puan veremez."};if(role==="employee")return{allowed:false,relation:null,override:false,reason:"Personel başka çalışanı değerlendiremez."};const relation=getManagerRelationship(user,employee);if(!relation)return{allowed:false,relation:null,override:false,reason:"Çalışan bu kullanıcının doğrudan raporu değil."};if(relation==="Yönetici 2"&&!policy.performance.secondManagerCanEvaluate)return{allowed:false,relation,override:false,reason:"Firma politikasında Yönetici 2 değerlendirmesi kapalı."};return{allowed:true,relation,override:false};}
export function roleLabel(role:UserRole){return({ceo:"CEO / Genel Müdür",hr_admin:"İK Yöneticisi",director:"Direktör",manager:"Müdür / Yönetici",employee:"Personel"} as Record<UserRole,string>)[role];} export function scopeLabel(scope:DataScope){return({NONE:"Erişim yok",SELF:"Kendi",DIRECT_REPORTS:"Doğrudan ekip",DEPARTMENT:"Departman",COMPANY:"Tüm şirket",ASSIGNED:"Atandığı kayıtlar"} as Record<DataScope,string>)[scope];}
