"use client";

import { useEffect } from "react";
import { getStorageData, markHRDataActive, setStorageData, STORAGE_KEYS } from "@/app/utils/storage";
import { findDevelopmentIntervention } from "@/lib/hr/developmentLibrary";

const CODES = ["DIG","ANA","RES","DET","LRN","ETH","DIS","STR","TEA","COM"] as const;
const EXTRA: Array<[string,string,string]> = [
  ["Cansu Demir","People Analytics Uzmanı","İnsan Kaynakları"],
  ["Serkan Bozkurt","İK İş Ortağı","İnsan Kaynakları"],
  ["Ayşe Nur Tek","Çalışan Deneyimi Uzmanı","İnsan Kaynakları"],
  ["Furkan Vural","Özlük İşleri Uzmanı","İnsan Kaynakları"],
  ["İlayda Çelik","Finansal Kontrol Uzmanı","Finans & Muhasebe"],
  ["Barış Acar","Hazine Uzmanı","Finans & Muhasebe"],
  ["Yasemin Uslu","Maliyet Muhasebesi Uzmanı","Finans & Muhasebe"],
  ["Gökhan Duman","Bölge Satış Uzmanı","Satış & Pazarlama"],
  ["Selin Kurt","Dijital Pazarlama Uzmanı","Satış & Pazarlama"],
  ["Mert Öz","Müşteri İçgörü Analisti","Satış & Pazarlama"],
  ["Sibel Erol","Planlama Mühendisi","Operasyon & Üretim"],
  ["Eray Akın","Tedarik Zinciri Uzmanı","Operasyon & Üretim"],
  ["Dilan Şimşek","İSG ve Süreç Uzmanı","Operasyon & Üretim"],
  ["Caner Oral","Sistem Uzmanı","BT & Dijital"],
  ["Damla Korkmaz","Ürün Analisti","BT & Dijital"],
  ["Yiğit Ersoy","DevOps Uzmanı","BT & Dijital"],
  ["Lara Yüce","Proje Kontrol Uzmanı","Proje & İş Geliştirme"],
  ["Eren Taş","Strateji Uzmanı","Proje & İş Geliştirme"],
  ["İpek Bulut","İnovasyon Uzmanı","Proje & İş Geliştirme"],
];
const INT = ["ANA-02","DET-03","RES-02","DIG-03","DIS-03","DIG-04","DET-04","COM-03","TEA-03","LRN-03","ETH-02","TEA-02","COM-02","RES-03","LRN-01","STR-02","ANA-03","ETH-03"];
const COST:Record<string,string>={"Genel Yönetim":"CC-100","İnsan Kaynakları":"CC-200","Finans & Muhasebe":"CC-300","Satış & Pazarlama":"CC-400","Operasyon & Üretim":"CC-500","BT & Dijital":"CC-600","Proje & İş Geliştirme":"CC-700"};
const round=(n:number)=>Math.round(n*100)/100;
const clamp=(n:number)=>Math.max(1,Math.min(5,n));
const iso=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString();};
const day=(days:number)=>iso(days).slice(0,10);
const username=(name:string)=>name.toLocaleLowerCase("tr-TR").replace(/ı/g,"i").replace(/ğ/g,"g").replace(/ü/g,"u").replace(/ş/g,"s").replace(/ö/g,"o").replace(/ç/g,"c").replace(/[^a-z0-9]/g,"");
function week(offset:number){const d=new Date();d.setDate(d.getDate()-offset*7);const jan=new Date(d.getFullYear(),0,1);const w=Math.ceil((((d.getTime()-jan.getTime())/86400000)+jan.getDay()+1)/7);return `${d.getFullYear()}-W${String(w).padStart(2,"0")}`;}
function score(seed:number,shift=0){return round(clamp(3.05+((seed*7+shift*3)%16)/10));}
function salary(position:string,index:number){const base=/müdür/i.test(position)?108000:/mühendis|analist/i.test(position)?72000:63500;return Math.round((base+(index%6)*3250)/500)*500;}
function upgradeOrg(base:any[]){
  const org=base.map((p,i)=>({...p,"Personel Kodu":p["Personel Kodu"]||`FHR-${String(i+1).padStart(4,"0")}`,"Maliyet Merkezi":p["Maliyet Merkezi"]||COST[p.Departman]||"CC-900",Lokasyon:p.Lokasyon||(p.Departman==="Operasyon & Üretim"?"Çorlu":"İstanbul / Hibrit"),"Şube":p["Şube"]||(p.Departman==="Operasyon & Üretim"?"Çorlu Fabrika":"Merkez Ofis"),"Kadro Durumu":"Aktif","Çalışan Tipi":"Tam Zamanlı","İşgücü Tipi":"Beyaz Yaka",Eposta:p.Eposta||`${username(String(p["Ad Soyad"]||`calisan${i+1}`))}@futurehr.demo`}));
  const names=new Set(org.map(p=>String(p["Ad Soyad"]||"")));
  EXTRA.forEach(([name,position,dept],i)=>{if(names.has(name)||org.length>=50)return;const manager=org.find(p=>p.Departman===dept&&/müdür/i.test(String(p.Pozisyon||"")));const ceo=org.find(p=>p.Departman==="Genel Yönetim");const n=org.length+1;org.push({id:`P${String(n).padStart(3,"0")}`,"Personel Kodu":`FHR-${String(n).padStart(4,"0")}`,"Ad Soyad":name,Departman:dept,Pozisyon:position,"Yönetici 1":manager?.["Ad Soyad"]||ceo?.["Ad Soyad"]||"","Yönetici 2":ceo?.["Ad Soyad"]||"","İşe Giriş Tarihi":`202${i%5}-${String((i%9)+1).padStart(2,"0")}-10`,"Maaş (TL)":salary(position,n),Lokasyon:dept==="Operasyon & Üretim"?"Çorlu":"İstanbul / Hibrit","Şube":dept==="Operasyon & Üretim"?"Çorlu Fabrika":"Merkez Ofis","Maliyet Merkezi":COST[dept],"Kadro Durumu":"Aktif","Çalışan Tipi":"Tam Zamanlı","İşgücü Tipi":"Beyaz Yaka",Eposta:`${username(name)}@futurehr.demo`,career_aspiration:3+(i%4)*.5,mobility_willingness:3+((i+1)%4)*.5});});
  if(org.length!==50)throw new Error(`50 kişilik demo şirketi oluşturulamadı: ${org.length}`);return org;
}
function historyFor(org:any[],existing:any[]){const out=[...existing];org.forEach((p,i)=>{const has=out.filter(r=>String(r.employee_id||"")===String(p.id)||String(r.Personel||"")===String(p["Ad Soyad"])).length;for(let j=has;j<2;j++){const current=j===0;const mgr=Object.fromEntries(CODES.map((c,k)=>[c,p["Ad Soyad"]==="Pelin Yılmaz"&&c==="ANA"?(current?3.95:3.15):score(i+1,k+(current?1:0))]));const kpi=score(i+2,current?2:0),manager=round(clamp(kpi+(((i+j)%5)-2)*.12));out.push({id:`eval-${p.id}-${current?"current":"prev"}`,employee_id:p.id,Personel:p["Ad Soyad"],"Ad Soyad":p["Ad Soyad"],Departman:p.Departman,Pozisyon:p.Pozisyon,evaluator:p["Yönetici 1"]||"Yönetim Kurulu",evaluation_type:"FutureHR 50 Kişilik Demo",period:current?"2026 Q2":"2025 Q4",date:iso(current?-30:-210),kpi_score:kpi,"KPI Score":kpi,manager_performance_score:manager,"Manager Score":manager,Performans:round(kpi*.6+manager*.4),competency_score:round(Object.values(mgr).reduce((s:any,v:any)=>s+Number(v),0)/CODES.length),manager_scores:mgr,...mgr,...Object.fromEntries(Object.entries(mgr).map(([c,v])=>[`${c}_Mgr`,v])),note:current?"Güncel dönem kalibrasyon kaydı.":"Önceki dönem karşılaştırma kaydı."});}});return out.sort((a,b)=>String(a.employee_id||a.Personel).localeCompare(String(b.employee_id||b.Personel))).slice(0,100);}
function benchmarks(org:any[]){return org.map((p,i)=>{const s=Number(p["Maaş (TL)"]||salary(p.Pozisyon,i));const m=Math.round(s*(1.03+(i%5)*.025)/500)*500;return{id:`bench-${p.id}`,employee_id:p.id,employee:p["Ad Soyad"],Departman:p.Departman,Pozisyon:p.Pozisyon,"Piyasa Alt":Math.round(m*.9/500)*500,"Piyasa Ortalaması":m,"Piyasa Üst":Math.round(m*1.12/500)*500,compaRatio:round(s/m),Kaynak:"FutureHR 50 kişi demo piyasa referansı",source:"FutureHR 50 kişi demo piyasa referansı",updatedAt:new Date().toISOString()};});}
function plans(emp:any[]){return emp.map((p,i)=>{const id=INT[i%INT.length],x=findDevelopmentIntervention(id),c=(x?.competencyCode||CODES[i%CODES.length]) as string,cur=round(2.7+(i%8)*.18),target=round(Math.min(4.6,cur+.55+(i%3)*.15));return{id:`dev-${p.id}`,employee:p["Ad Soyad"],employee_id:p.id,department:p.Departman,role:p.Pozisyon,competency:c,competencyLabel:x?.competencyLabel||c,currentScore:cur,targetScore:target,target,gap:round(target-cur),interventionId:id,interventionName:x?.name||`${c} gelişim müdahalesi`,goal:`${x?.competencyLabel||c} gelişim açığını rol hedefiyle kapatmak`,actionType:x?.type||"İş Üstünde",action:x?.transferTask||"İş üstünde uygulama kanıtı oluştur.",successMetric:x?.successMetric||"Yönetici doğrulaması",status:i%7===0?"Planlandı":i%6===0?"Tamamlandı":"Devam Ediyor",progress:i%6===0?100:25+(i%4)*20,owner:p["Yönetici 1"],start:day(-80+i%20),deadline:day(25+i%90),dueDate:day(25+i%90),evidence:i%4===0?"Ara çıktı ve yönetici gözlemi kaydedildi.":"",reassessmentDate:day(30+i%70),transferredToTraining:i%3===0,createdAt:iso(-95+i%20)};});}
function training(emp:any[]){return emp.map((p,i)=>{const id=INT[(i*2)%INT.length],x=findDevelopmentIntervention(id),status=i%5===0?"planned":i%4===0?"in_progress":"completed",done=status==="completed";return{id:`train-${p.id}`,employee:p["Ad Soyad"],employee_id:p.id,department:p.Departman,role:p.Pozisyon,interventionId:id,title:x?.name||"Uygulamalı Gelişim Programı",competencyCode:x?.competencyCode||CODES[i%CODES.length],competencyLabel:x?.competencyLabel||"",type:x?.type||"Uygulamalı Eğitim",duration:x?.duration||"4 saat",startDate:day(-90+i%25),endDate:day(-35+i%35),status,completionDate:done?day(-20-i%25):undefined,knowledgeChecks:done?[{score:78+i%18,at:day(-22-i%12)}]:[],transferEvidence:done&&i%3!==0?{status:i%4===1?"verified":"submitted",evidence:x?.transferTask||"İş üstünde uygulama kanıtı",verifiedBy:i%4===1?p["Yönetici 1"]:undefined,verifiedAt:i%4===1?day(-8-i%10):undefined}:null,reassessmentDate:day(20+i%65),durationWeeks:2+i%7,manager:p["Yönetici 1"]};});}
function candidates(){const roles=[["Kıdemli Yazılım Uzmanı","BT & Dijital"],["Üretim Mühendisi","Operasyon & Üretim"],["Finans Uzmanı","Finans & Muhasebe"],["Satış Uzmanı","Satış & Pazarlama"],["İK İş Ortağı","İnsan Kaynakları"],["Proje Uzmanı","Proje & İş Geliştirme"]],first=["Ada","Kuzey","İdil","Doruk","Mina","Batu","Eylül","Toprak","Derin","Aras","Defne","Rüzgar","Lina","Atlas","Ela","Efe","Nisan","Deniz","Maya","Emir","Alara","Baran","Lale","Tuna"],last=["Kara","Soylu","Özdemir","Ateş","Güler","Kurt","Akın","Taş","Keskin","Eren","Aydın","Bulut"],st=["Başvuru","Ön Eleme","Test","Mülakat","İş Örneği","Teklif"];return Array.from({length:24},(_,i)=>{const [position,department]=roles[i%roles.length],name=`${first[i]} ${last[(i*5)%last.length]}`;return{id:`C${String(i+1).padStart(3,"0")}`,name,email:`${username(name)}@aday.futurehr.demo`,phone:`+90 555 21${String(i).padStart(3,"0")}`,position,role:position,department,type:"Aday",stage:st[i%st.length],score:62+(i*7)%33,fitScore:60+(i*9)%36,appliedAt:iso(-45+i),source:i%3===0?"LinkedIn":i%3===1?"Kariyer.net":"Referans"};});}
function pulse(emp:any[]){const rows:any[]=[];for(let w=7;w>=0;w--)emp.forEach((p,i)=>{const b=3.25+((i*3+w*2)%13)/10;rows.push({id:`pulse-${week(w)}-${p.id}`,employeeKey:p.id,employee:p["Ad Soyad"],department:p.Departman,week:week(w),score:round(clamp(b)),driverScores:{manager:round(clamp(b+.18)),meaning:round(clamp(b+.1)),workload:round(clamp(b-.35+((i+w)%4)*.12)),growth:round(clamp(b-.05)),trust:round(clamp(b+.12)),team:round(clamp(b+.22))},comment:["Öncelikler net.","İş yükü dengelenmeli.","Geri bildirim faydalı.","Gelişim fırsatları görünür."][(i+w)%4],privateComment:`Demo anonim yanıt ${i+1}`,createdAt:iso(-w*7-i%5)});});return rows;}
function users(org:any[]){return Object.fromEntries(org.map(p=>{const u=username(p["Ad Soyad"]),pos=String(p.Pozisyon||""),role=/genel müdür/i.test(pos)?"CEO":p.Departman==="İnsan Kaynakları"&&/müdür/i.test(pos)?"IK":/müdür|direktör/i.test(pos)?"MANAGER":"PERSONEL";return[u,{username:u,password:"Demo123!",name:p["Ad Soyad"],role,dept:p.Departman,department:p.Departman,position:p.Pozisyon,active:true,employee_id:p.id,createdAt:iso(-120)}];}));}

export default function DemoCompany50Bridge(){
  useEffect(()=>{
    let applying=false;
    const hydrate=()=>{
      if(applying)return;
      const base=getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]),names=new Set(base.map(p=>String(p?.["Ad Soyad"]||"")));
      if(base.length<25||!names.has("Pelin Yılmaz"))return;
      const profile=getStorageData<any>("hr_company_demo_profile",null);if(base.length===50&&profile?.demoVersion==="FHR-DEMO-50-1")return;
      applying=true;
      try{
        const org=upgradeOrg(base),emp=org.filter(p=>p.Departman!=="Genel Yönetim"),mgr=org.filter(p=>/müdür|direktör/i.test(String(p.Pozisyon||"")));
        const hist=historyFor(org,getStorageData<any[]>(STORAGE_KEYS.HISTORY_360,[])),bench=benchmarks(org),dev=plans(emp),learn=training(emp),cand=candidates(),pa=pulse(emp);
        const career=emp.map((p,i)=>({id:`career-${p.id}`,employee_id:p.id,employee:p["Ad Soyad"],department:p.Departman,currentRole:p.Pozisyon,targetRole:i%4===0?`${p.Departman} Takım Lideri`:i%4===1?"Kıdemli Uzman":i%4===2?"Uzmanlıkta Derinleşme":"Yatay Kritik Rol",aspiration:i%3===0?"Yönetim":i%3===1?"Uzmanlıkta Derinleşme":"Yatay Gelişim",mobility:i%4!==0,readiness:i%4===0?"12+ ay":i%3===0?"6-12 ay":"0-6 ay",readinessScore:58+(i%10)*3,evidenceCoverage:68+(i%7)*4,updatedAt:iso(-20+i%14)}));
        const ass=emp.map((p,i)=>({id:`assessment-${p.id}`,employee_id:p.id,person:p["Ad Soyad"],role:p.Pozisyon,department:p.Departman,version:"FHR-ASSESS-DEMO-2",score:66+(i*5)%30,potentialScore:62+(i*7)%34,status:i%12===0?"Gözden Geçirme":"Tamamlandı",completedAt:iso(-90+i%55)}));
        const cres=cand.map((c,i)=>({id:`candidate-result-${c.id}`,candidateId:c.id,candidate:c.name,role:c.role,score:c.score,competencyFit:c.fitScore,evidenceCoverage:58+(i%8)*5,recommendation:i%5===0?"Yapılandırılmış mülakat":i%4===0?"İş örneği":i%3===0?"Yedek havuz":"İleri aşama",completedAt:iso(-30+i)}));
        const leaves=Array.from({length:32},(_,i)=>{const p=emp[i%emp.length];return{id:`leave-demo-${i+1}`,employee_id:p.id,employee:p["Ad Soyad"],department:p.Departman,type:i%7===0?"sick":i%5===0?"excuse":"annual",start:day(i-18),end:day(i-17+i%4),days:1+i%4,status:i%6===0?"Bekliyor":i%9===0?"Reddedildi":"Onaylandı",note:"Ekip kapasitesi dikkate alınarak oluşturuldu.",createdAt:iso(-55+i),approvedBy:i%6===0?undefined:p["Yönetici 1"]};});
        const rewards=Array.from({length:12},(_,i)=>{const p=emp[(i*3+4)%emp.length];return{id:`reward-demo-${i+1}`,employee_id:p.id,employee:p["Ad Soyad"],days:i%3===0?2:1,reason:i%2===0?"Kritik proje katkısı":"Dönem hedefinin üzerinde performans",grantedBy:p["Yönetici 1"],createdAt:iso(-70+i*4)};});
        const results=emp.map((p,i)=>{const s=Number(p["Maaş (TL)"]||0),inc=15+(i%7)*1.5;return{employee_id:p.id,employee:p["Ad Soyad"],department:p.Departman,currentSalary:s,proposedIncrease:inc,proposedSalary:Math.round(s*(1+inc/100)/500)*500,performance:hist.find(r=>r.employee_id===p.id&&r.period==="2026 Q2")?.Performans||3.5,evidenceScore:62+(i%8)*4,internalEquityFlag:i%11===0};});
        const cycle={id:"cycle-demo-2026",name:"2026 Ücret Dönemi",stage:"BUDGET_REVIEW",createdAt:iso(-24),effectiveDate:day(30),managerDeadline:day(8),budgetLimit:22.5,scenario:"B",inflationRate:19.5,managerRequests:mgr.map((p,i)=>({id:`comp-req-${i+1}`,manager:p["Ad Soyad"],department:p.Departman,requestedIncrease:18+i*1.5,status:i%3===0?"Revizyon":"Gönderildi"})),results,stageHistory:[{stage:"DRAFT_SIMULATION",at:iso(-24),by:"İK"},{stage:"MANAGER_INPUT",at:iso(-14),by:"İK"},{stage:"BUDGET_REVIEW",at:new Date().toISOString(),by:"İK"}]};
        const activities=Array.from({length:64},(_,i)=>{const p=emp[(i*7)%emp.length],types=["performance","development","learning","career","compensation","leave","pulse","talent"],links=["/degerlendirme","/gelisim","/egitim","/kariyer","/maas","/izinler","/calisan-deneyimi","/yetenek-matrisi"];return{id:`activity-${i+1}`,type:types[i%8],title:["Performans kaydı güncellendi","Gelişim aksiyonu güncellendi","Eğitim ilerlemesi kaydedildi","Kariyer kanıtı güncellendi","Ücret girdisi kaydedildi","İzin talebi işlendi","Pulse yanıtı toplulaştırıldı","Yetenek kanıtı yenilendi"][i%8],employee_id:p.id,employee:p["Ad Soyad"],department:p.Departman,actor:i%4===0?p["Yönetici 1"]:"FutureHR Demo",link:links[i%8],status:i%6===0?"attention":"completed",occurredAt:iso(-i)};});
        const skills=emp.flatMap((p,i)=>Array.from({length:5},(_,k)=>{const c=CODES[(i+k*2)%CODES.length];return{id:`skill-${p.id}-${c}`,employee_id:p.id,employee:p["Ad Soyad"],department:p.Departman,competencyCode:c,competency:c,current:round(2.8+((i+k)%10)*.18),target:round(3.8+((i+k)%4)*.2),evidenceCount:2+(i+k)%6,updatedAt:iso(-i%20)};}));
        setStorageData(STORAGE_KEYS.ORG_CHART,org);setStorageData(STORAGE_KEYS.HISTORY_360,hist);setStorageData(STORAGE_KEYS.MARKET_BENCHMARKS,bench);setStorageData(STORAGE_KEYS.DEVELOPMENT_PLANS,dev);setStorageData(STORAGE_KEYS.TRAINING_ASSIGNMENTS,learn);setStorageData(STORAGE_KEYS.CANDIDATES,cand);setStorageData(STORAGE_KEYS.PULSE_ANSWERS,pa);setStorageData(STORAGE_KEYS.CAREER_PROFILES,career);setStorageData(STORAGE_KEYS.ASSESSMENTS,ass);setStorageData(STORAGE_KEYS.CANDIDATE_RESULTS,cres);setStorageData(STORAGE_KEYS.LEAVE_REQUESTS,leaves);setStorageData(STORAGE_KEYS.REWARD_LEAVE,rewards);setStorageData(STORAGE_KEYS.COMPENSATION_CYCLES,[cycle]);setStorageData(STORAGE_KEYS.USERS,users(org));
        setStorageData(STORAGE_KEYS.NOTIFICATIONS,[["2 izin talebi yönetici onayı bekliyor.","/izinler"],["Ücret dönemi bütçe kontrolüne hazır.","/maas"],["7 gelişim yeniden ölçümü yaklaşıyor.","/gelisim-analitigi"],["Kritik rol havuzu güncellendi.","/yedekleme"],["4 aday iş örneği aşamasında.","/ise-alim"],["Pulse katılımı %88 seviyesinde.","/calisan-deneyimi"],["5 performans kaydı kalibrasyonda.","/kalibrasyon"],["KVKK kontrolünde 2 görev açık.","/admin/guven-kvkk"]].map((x,i)=>({id:93000+i,message:x[0],type:i%3===0?"warning":"info",read:i%4===0,timestamp:iso(-i*2),link:x[1],source:"demo"})));
        setStorageData("hr_activities",activities);setStorageData("hr_skills",skills);setStorageData("hr_risk_alerts",Array.from({length:14},(_,i)=>{const p=emp[(i*5+2)%emp.length];return{id:`risk-${i+1}`,type:["succession","workload","equity","evidence","retention","development"][i%6],severity:i%5===0?"high":i%3===0?"medium":"low",employee_id:p.id,employee:p["Ad Soyad"],department:p.Departman,title:["Kritik rol yedekleme riski","İş yükü / kapasite sinyali","İç ücret adaleti sinyali","Düşük kanıt kapsamı","Elde tutma görüşmesi","Gelişim yeniden ölçümü"][i%6],requiresHumanReview:true,createdAt:iso(-i*3)};}));
        setStorageData("hr_learning_impact",learn.map((a,i)=>({id:`impact-${a.id}`,employee_id:a.employee_id,employee:a.employee,trainingId:a.interventionId,training:a.title,competencyCode:a.competencyCode,completionStatus:a.status,transferStatus:a.transferEvidence?.status||"pending",preScore:round(2.9+(i%7)*.14),postScore:round(3.2+(i%7)*.16),measuredAt:iso(-20+i%25),causalClaimAllowed:false})));setStorageData("hr_development_interventions",dev);
        setStorageData("hr_simulation_scenarios",[{id:"A",label:"Temkinli",budgetImpact:14.8,averageIncrease:13.5},{id:"B",label:"Dengeli",budgetImpact:19.6,averageIncrease:18.2,active:true},{id:"C",label:"Agresif",budgetImpact:23.9,averageIncrease:22.1},{id:"D",label:"Hedefli",budgetImpact:18.4,averageIncrease:16.7}]);
        setStorageData("hr_talent_potential",ass.map((a,i)=>({employee_id:a.employee_id,employee:a.person,potential:a.potentialScore,performance:hist.find(r=>r.employee_id===a.employee_id&&r.period==="2026 Q2")?.Performans||3.5,evidenceScore:60+(i%9)*4})));setStorageData("hr_performance_entries",hist.filter(r=>r.period==="2026 Q2"));
        setStorageData("hr_succession_plans",mgr.map((m,i)=>({id:`succession-${m.id}`,criticalRole:m.Pozisyon,department:m.Departman,incumbent:m["Ad Soyad"],criticality:i%3===0?"Kritik":"Yüksek",candidates:emp.filter(p=>p.Departman===m.Departman).slice(0,3).map((p,k)=>({employee_id:p.id,employee:p["Ad Soyad"],currentRole:p.Pozisyon,readinessScore:58+k*12,evidenceCoverage:68+k*6})),updatedAt:iso(-i*4)})));
        setStorageData("hr_ai_audit_log",Array.from({length:18},(_,i)=>({id:`ai-audit-${i+1}`,action:["Employee360 context prepared","PII aliasing applied","Decision guardrail applied","Evidence summary generated"][i%4],module:["performance","development","compensation","recruitment"][i%4],actorRole:i%3===0?"CEO":"IK",externalNameShared:false,finalDecisionByAI:false,createdAt:iso(-i*2)})));
        setStorageData("hr_compliance_tasks",["KVKK veri minimizasyonu","AI kullanım kayıtları","Yetki matrisi kontrolü","Aday verisi saklama","Ücret erişim kontrolü","Pulse anonimlik eşiği","Demo veri temizleme","Veri aktarımı doğrulama"].map((t,i)=>({id:`compliance-${i+1}`,title:t,owner:mgr[i%mgr.length]?.["Ad Soyad"]||"İK",status:i%4===0?"Yaklaşıyor":i%3===0?"İncelemede":"Tamamlandı",dueDate:day(5+i*9),module:i%2===0?"KVKK":"AI Governance"})));
        setStorageData("hr_company_demo_profile",{id:"futurehr-demo-50",name:"FutureHR Teknoloji A.Ş.",employeeCount:50,departments:7,demoVersion:"FHR-DEMO-50-1",generatedAt:new Date().toISOString(),coverage:{organization:50,performanceRecords:hist.length,benchmarks:bench.length,developmentPlans:dev.length,trainingAssignments:learn.length,careerProfiles:career.length,assessments:ass.length,candidates:cand.length,pulseAnswers:pa.length,leaveRequests:leaves.length,compensationEmployees:results.length,activities:activities.length,skills:skills.length}});
        markHRDataActive();window.dispatchEvent(new CustomEvent("demoCompany50Ready",{detail:{employeeCount:50}}));window.dispatchEvent(new CustomEvent("dataUpdated"));window.dispatchEvent(new CustomEvent("talentMatrixUpdated"));window.dispatchEvent(new CustomEvent("pulseUpdated"));
      }catch(error){console.error("50 kişilik demo şirketi oluşturulamadı",error);}finally{applying=false;}
    };
    hydrate();window.addEventListener("dataUpdated",hydrate);window.addEventListener("storage",hydrate);return()=>{window.removeEventListener("dataUpdated",hydrate);window.removeEventListener("storage",hydrate);};
  },[]);
  return null;
}
