"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRight, Bot, BrainCircuit, FileSearch, Loader2, Send, ShieldCheck, X } from "lucide-react";
import FutureHRCopilot from "./FutureHRCopilot";
import { SAAS_DATA_MODE } from "@/lib/hr/saasWorkforceClient";
import { fetchDecisionPriorities, fetchDecisionProfile, type DecisionPriority, type DecisionProfile } from "@/lib/hr/decisionIntelligenceClient";

type Severity="kritik"|"yüksek"|"orta"|"bilgi";
type Analysis={answer:string;confidence:"düşük"|"orta"|"yüksek";confidenceReason:string;priorities:Array<{severity:Severity;title:string;evidence:string;action:string;route:string}>;nextActions:string[];evidenceGaps:string[];guardrail:string;};
type Result={mode?:"ai"|"rules";provider?:string;model?:string;analysis?:Analysis;error?:string};
const QUICK=["Şu anda en kritik insan kararları hangileri?","Kanıt güveni düşük çalışan profillerini özetle.","Ücret sıkışması veya piyasa riski olan kararları göster.","Yüksek performans gösteren çalışanlarda hangi karar kanıtları eksik?","Bu hafta İK olarak hangi insan kararlarını doğrulamalıyım?"];

export default function FutureHRCopilotV2({pathname}:{pathname:string}){
  if(!SAAS_DATA_MODE)return <FutureHRCopilot pathname={pathname}/>;
  return <SaasCopilot pathname={pathname}/>;
}

function SaasCopilot({pathname}:{pathname:string}){
  const[open,setOpen]=useState(false);const[question,setQuestion]=useState("");const[loading,setLoading]=useState(false);const[result,setResult]=useState<Result|null>(null);const[priorities,setPriorities]=useState<DecisionPriority[]>([]);const[focus,setFocus]=useState<{name:string;profile:DecisionProfile}|null>(null);const[contextError,setContextError]=useState("");
  const loadPriorities=async()=>{try{const payload=await fetchDecisionPriorities();setPriorities(payload.items);setContextError("");return payload.items;}catch(err){setContextError(err instanceof Error?err.message:"Karar Motoru bağlamı alınamadı.");return[];}};
  useEffect(()=>{if(open&&priorities.length===0)void loadPriorities();},[open]);
  const provider=useMemo(()=>result?.provider==="groq"?"Groq · FutureHR":result?.provider==="openai"?"OpenAI · FutureHR":result?.provider==="rules"?"FutureHR Kural Motoru":"FutureHR Copilot",[result?.provider]);

  const ask=async(raw:string)=>{const clean=raw.trim();if(!clean||loading)return;setQuestion(clean);setLoading(true);setResult(null);setFocus(null);try{const rows=priorities.length?priorities:await loadPriorities();const normalized=clean.toLocaleLowerCase("tr-TR");const matched=[...rows].filter(item=>normalized.includes(item.employee_name.toLocaleLowerCase("tr-TR"))).sort((a,b)=>b.employee_name.length-a.employee_name.length)[0];let profile:DecisionProfile|null=null;let outbound=clean;if(matched){profile=await fetchDecisionProfile(matched.employee_id);outbound=clean.replace(new RegExp(escapeRegExp(matched.employee_name),"gi"),"seçili çalışan");setFocus({name:matched.employee_name,profile});}
      const context={pageContext:pathname,scope:profile?"selected_employee":"company",decisionEngine:{priorityCount:rows.length,priorities:rows.slice(0,12).map(item=>({employee_id:item.employee_id,department:item.department,priority_score:item.priority_score,reasons:item.reasons,recommended_next_step:item.recommended_next_step,evidence_score:item.evidence_score})),targetEmployee:profile?{recommendation:profile.recommendation,evidence:profile.evidence,explainabilityChain:profile.explainability_chain.map(row=>({step:row.step,value:row.value}))}:null},guardrail:"Do not make an autonomous employment decision. Explain evidence, missing data, risk, and next human validation step."};
      const response=await fetch("/api/ai/copilot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:outbound,context})});const data=await response.json();if(!response.ok)throw new Error(data?.error||"Copilot yanıtı alınamadı.");if(data?.analysis&&matched)data.analysis=restoreName(data.analysis,matched.employee_name);setResult(data);
    }catch(err){setResult({error:err instanceof Error?err.message:"Copilot servisine ulaşılamadı."});}finally{setLoading(false);}};
  const submit=(event:FormEvent)=>{event.preventDefault();void ask(question);};

  return <><button type="button" onClick={()=>setOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-lg border border-slate-800 bg-slate-950 px-3 text-xs font-semibold text-white dark:border-slate-600 dark:bg-slate-800" aria-label="FutureHR Copilot'u aç"><span className="h-1.5 w-1.5 rounded-full bg-[#86b3af]"/><span className="hidden xl:inline">FutureHR Copilot</span></button>{open&&<div className="fixed inset-0 z-[95]"><button type="button" aria-label="Kapat" onClick={()=>setOpen(false)} className="absolute inset-0 bg-slate-950/35"/><aside className="absolute inset-y-0 right-0 flex w-full max-w-[560px] flex-col border-l border-slate-200 bg-[#f6f6f3] dark:border-slate-800 dark:bg-[#0f151b]"><header className="flex items-start justify-between border-b border-slate-200 bg-white px-5 py-4 dark:border-slate-800 dark:bg-[#141b22]"><div className="flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 text-slate-700 dark:border-slate-700 dark:bg-slate-800"><Bot className="h-[18px] w-[18px]"/></span><div><p className="text-[10px] font-semibold uppercase tracking-[.11em] text-[#2f6664]">Decision Intelligence</p><h2 className="mt-0.5 text-[17px] font-semibold">FutureHR Copilot</h2><p className="mt-1 text-[11px] text-slate-500">Canlı Karar Motoru bağlamı · insan onaylı AI</p></div></div><button onClick={()=>setOpen(false)} className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><X className="h-4 w-4"/></button></header>
      <div className="min-h-0 flex-1 overflow-y-auto p-5">{contextError&&<div className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-[10.5px] text-amber-800">{contextError}</div>}{!result&&!loading&&<><div className="enterprise-card p-4"><div className="flex items-start gap-2"><BrainCircuit className="mt-0.5 h-4 w-4 text-[#2f6664]"/><div><p className="text-sm font-semibold">Karar verisini sorun</p><p className="mt-1 text-xs leading-5 text-slate-500">Copilot; performans, kanıt güveni, gelişim ve ücret sinyallerini Karar Motoru üzerinden okur. Çalışan adı eşleşirse dış modele isim gönderilmez.</p></div></div></div><div className="mt-4 divide-y divide-slate-100 overflow-hidden rounded-lg border border-slate-200 bg-white dark:divide-slate-800 dark:border-slate-800 dark:bg-[#141b22]">{QUICK.map(prompt=><button key={prompt} onClick={()=>void ask(prompt)} className="flex w-full items-center justify-between gap-3 px-3.5 py-3 text-left text-xs font-medium hover:bg-slate-50 dark:hover:bg-slate-800/50"><span>{prompt}</span><ArrowRight className="h-3.5 w-3.5 shrink-0 text-slate-300"/></button>)}</div></>}{loading&&<div className="flex min-h-[320px] flex-col items-center justify-center text-center"><Loader2 className="h-6 w-6 animate-spin text-[#2f6664]"/><p className="mt-4 text-sm font-semibold">Karar zinciri okunuyor</p><p className="mt-1 text-xs text-slate-500">Tenant verisi → kanıt → risk → insan aksiyonu</p></div>}{result?.error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-xs text-red-700">{result.error}</div>}{result?.analysis&&<ResultView analysis={result.analysis} provider={provider} focus={focus} priorities={priorities}/>}</div>
      <form onSubmit={submit} className="border-t border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-[#141b22]"><div className="flex items-end gap-2"><textarea value={question} onChange={event=>setQuestion(event.target.value)} rows={2} placeholder="Örn. Selin Acar için neden ek kanıt gerekiyor?" className="min-h-[58px] flex-1 resize-none rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs outline-none focus:border-[#7ba4a1] dark:border-slate-700 dark:bg-slate-900"/><button disabled={loading||!question.trim()} className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#2f6664] text-white disabled:opacity-40"><Send className="h-4 w-4"/></button></div></form></aside></div>}</>;
}

function ResultView({analysis,provider,focus,priorities}:{analysis:Analysis;provider:string;focus:{name:string;profile:DecisionProfile}|null;priorities:DecisionPriority[]}){return <div className="space-y-4"><section className="enterprise-card p-4"><div className="flex items-center justify-between gap-2"><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#2f6664]">{provider}</p><span className="text-[9.5px] font-semibold text-slate-400">Veri güveni: {analysis.confidence}</span></div>{focus&&<p className="mt-2 text-[10px] text-slate-500">Odak: {focus.name} · isim dış AI sağlayıcısına gönderilmedi</p>}<p className="mt-3 text-sm font-medium leading-6">{analysis.answer}</p><p className="mt-2 text-[10.5px] leading-4 text-slate-400">{analysis.confidenceReason}</p></section>{focus&&<section className="enterprise-card p-4"><div className="flex items-center gap-2"><FileSearch className="h-4 w-4 text-[#2f6664]"/><p className="text-xs font-semibold">Karar Motoru dayanağı</p></div><div className="mt-3 grid grid-cols-2 gap-2"><Evidence label="Evidence Score" value={`${focus.profile.evidence.score}/100`}/><Evidence label="Eksik sinyal" value={String(focus.profile.evidence.missing.length)}/></div><p className="mt-3 text-[10.5px] leading-4 text-slate-500">{focus.profile.recommendation.next_step}</p></section>}{!focus&&priorities.length>0&&<section className="enterprise-card p-4"><p className="text-xs font-semibold">Kullanılan şirket sinyalleri</p><div className="mt-3 space-y-2">{priorities.slice(0,4).map(item=><div key={item.employee_id} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-2 text-[10.5px] last:border-0 dark:border-slate-800"><span className="truncate text-slate-600 dark:text-slate-300">{item.reasons.join(" · ")}</span><span className="shrink-0 font-semibold text-[#2f6664]">{item.evidence_score}/100</span></div>)}</div></section>}{analysis.priorities?.length>0&&<section className="enterprise-card overflow-hidden"><div className="border-b border-slate-100 px-4 py-3 text-xs font-semibold dark:border-slate-800">Öncelikler</div><div className="divide-y divide-slate-100 dark:divide-slate-800">{analysis.priorities.slice(0,5).map((item,index)=><div key={`${item.title}-${index}`} className="p-4"><p className="text-xs font-semibold">{item.title}</p><p className="mt-1 text-[10.5px] leading-4 text-slate-500">{item.evidence}</p><p className="mt-2 text-[10.5px] font-medium text-[#2f6664]">{item.action}</p></div>)}</div></section>}<div className="flex items-start gap-2 rounded-lg border border-[#cbdad8] bg-[#f1f6f5] p-3 text-[10.5px] leading-4 text-[#315f5c]"><ShieldCheck className="mt-0.5 h-3.5 w-3.5 shrink-0"/><span>{analysis.guardrail||"FutureHR karar desteği sunar; nihai karar insandadır."}</span></div></div>}
function Evidence({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800/60"><p className="text-[9.5px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
function escapeRegExp(text:string){return text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function restoreName(analysis:Analysis,name:string):Analysis{const replace=(text:string)=>String(text||"").replace(/seçili çalışan/gi,name);return{...analysis,answer:replace(analysis.answer),priorities:(analysis.priorities||[]).map(item=>({...item,title:replace(item.title),evidence:replace(item.evidence),action:replace(item.action)})),nextActions:(analysis.nextActions||[]).map(replace),evidenceGaps:(analysis.evidenceGaps||[]).map(replace)}}
