"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, CalendarClock, CheckCircle2, ClipboardCheck, Download, Gauge, ListChecks, Plus, Save, ShieldCheck, Users } from "lucide-react";
import { getStorageData, setStorageData, STORAGE_KEYS } from "@/app/utils/storage";

type DecisionAction = { id:string; employee?:string; employee_id?:string; title:string; owner:string; dueDate?:string; status:"Açık"|"Devam Ediyor"|"Tamamlandı"; note?:string; createdAt:string };
type RoleOverride = { id:string; role:string; version:number; status:"Taslak"|"Onaylı"; targets:Record<string,number>; approvedAt?:string; updatedAt:string };

export default function ProductCompletionLayer(){
  const pathname=usePathname();
  if(pathname==="/karar-merkezi") return <DecisionActionsPanel/>;
  if(pathname==="/maas") return <CompensationExecutivePanel/>;
  if(pathname==="/admin/guven-kvkk") return <SecuritySalesPack/>;
  if(pathname==="/turkiye-uyum") return <OnboardingFinishPanel/>;
  if(pathname==="/rol-mimarisi") return <RoleGovernancePanel/>;
  return null;
}

function DecisionActionsPanel(){
  const[revision,setRevision]=useState(0);const[form,setForm]=useState({employee:"",title:"",owner:"",dueDate:""});
  useEffect(()=>{const f=()=>setRevision(v=>v+1);window.addEventListener("dataUpdated",f);return()=>window.removeEventListener("dataUpdated",f)},[]);
  const employees=getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]);const actions=getStorageData<DecisionAction[]>(STORAGE_KEYS.DECISION_ACTIONS,[]);void revision;
  const save=(next:DecisionAction[])=>{setStorageData(STORAGE_KEYS.DECISION_ACTIONS,next);window.dispatchEvent(new CustomEvent("dataUpdated"));setRevision(v=>v+1)};
  const add=(e:FormEvent)=>{e.preventDefault();if(!form.title.trim()||!form.owner.trim())return;const employee=employees.find(row=>row["Ad Soyad"]===form.employee);save([{id:`decision-${Date.now()}`,employee:form.employee||undefined,employee_id:employee?.id,title:form.title.trim(),owner:form.owner.trim(),dueDate:form.dueDate||undefined,status:"Açık",createdAt:new Date().toISOString()},...actions]);setForm({employee:"",title:"",owner:"",dueDate:""})};
  const open=actions.filter(a=>a.status!=="Tamamlandı").length;
  return <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#2f6664]">Karardan aksiyona</p><h2 className="mt-1 text-base font-semibold">Karar aksiyonları</h2><p className="mt-1 text-xs text-slate-500">Karar sinyalini sahip, tarih ve kapanış kaydı olan izlenebilir bir işe dönüştürün.</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">{open} açık aksiyon</span></div><form onSubmit={add} className="mt-4 grid gap-2 md:grid-cols-[1fr_1.5fr_1fr_150px_auto]"><select value={form.employee} onChange={e=>setForm({...form,employee:e.target.value})} className="h-10 rounded-xl border border-slate-200 px-3 text-xs"><option value="">Genel karar</option>{employees.map(row=><option key={row.id??row["Ad Soyad"]}>{row["Ad Soyad"]}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Aksiyon" className="h-10 rounded-xl border border-slate-200 px-3 text-xs"/><input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})} placeholder="Sorumlu" className="h-10 rounded-xl border border-slate-200 px-3 text-xs"/><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} className="h-10 rounded-xl border border-slate-200 px-3 text-xs"/><button className="inline-flex h-10 items-center justify-center gap-1 rounded-xl bg-slate-950 px-4 text-xs font-semibold text-white"><Plus className="h-3.5 w-3.5"/>Ekle</button></form><div className="mt-4 divide-y divide-slate-100">{actions.slice(0,8).map(action=><div key={action.id} className="grid gap-2 py-3 text-xs md:grid-cols-[1.5fr_1fr_120px_130px]"><div><p className="font-semibold">{action.title}</p><p className="mt-1 text-[10px] text-slate-400">{action.employee||"Şirket geneli"}</p></div><span>{action.owner}</span><span>{action.dueDate||"Tarih yok"}</span><select value={action.status} onChange={e=>save(actions.map(item=>item.id===action.id?{...item,status:e.target.value as DecisionAction["status"]}:item))} className="h-8 rounded-lg border border-slate-200 px-2 text-[10px]"><option>Açık</option><option>Devam Ediyor</option><option>Tamamlandı</option></select></div>)}{!actions.length&&<p className="py-5 text-center text-xs text-slate-400">Henüz karar aksiyonu oluşturulmadı.</p>}</div></section>
}

function CompensationExecutivePanel(){
  const org=getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]),bench=getStorageData<any[]>(STORAGE_KEYS.MARKET_BENCHMARKS,[]),cycles=getStorageData<any[]>(STORAGE_KEYS.COMPENSATION_CYCLES,[]);
  const payroll=org.reduce((sum,row)=>sum+Number(row["Maaş (TL)"]||row.salary_amount||0),0);const covered=org.filter(row=>bench.some(b=>String(b.Departman||b.department)===String(row.Departman)&&String(b.Pozisyon||b.position)===String(row.Pozisyon))).length;const coverage=org.length?Math.round(covered/org.length*100):0;const active=cycles.find((c:any)=>c.stage!=="EFFECTIVE")||cycles[0];
  return <section className="mt-5 rounded-2xl border border-emerald-100 bg-gradient-to-br from-white to-emerald-50/40 p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-emerald-700">Compensation Intelligence</p><h2 className="mt-1 text-base font-semibold">Yönetici ücret karar özeti</h2></div><Link href="/ucret-adaleti" className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700">Adalet & sıkışma<ArrowRight className="h-3.5 w-3.5"/></Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Mini label="Aylık ücret tabanı" value={payroll?`${Math.round(payroll).toLocaleString("tr-TR")} ₺`:"—"}/><Mini label="Benchmark kapsaması" value={`%${coverage}`}/><Mini label="Aktif dönem" value={active?.name||"Henüz yok"}/><Mini label="Karar aşaması" value={active?.stage||"Başlatılmadı"}/></div><p className="mt-3 text-[10.5px] leading-5 text-slate-500">Bütçe senaryosu, piyasa konumu ve iç adalet aynı karar paketinde izlenir; kesin ücret değişikliği onay akışından sonra uygulanır.</p></section>
}

function SecuritySalesPack(){
  const download=()=>{const controls=["Rol ve veri kapsamı (RBAC)","Tenant izolasyonu","Hassas ücret/yetenek erişimi","AI veri minimizasyonu","Audit izi","Aday saklama kontrolü","SSO fail-closed eşleme","Anonim çalışan deneyimi","Human-in-the-loop kararlar","Yedekleme / iş sürekliliği hazırlığı"];const html=`<!doctype html><html><meta charset="utf-8"><title>FutureHR Security & KVKK Pack</title><body style="font-family:Arial;max-width:900px;margin:40px auto;line-height:1.5"><h1>FutureHR Security & KVKK Pack</h1><p>Kurumsal satış ve bilgi güvenliği incelemesi için teknik hazırlık özeti. Hukuki uygunluk sertifikası değildir.</p><h2>Kontroller</h2><ol>${controls.map(x=>`<li>${x}</li>`).join("")}</ol><h2>Satın alma paketi</h2><ul><li>DPA / veri işleme eki: müşteri hukuk ekibiyle tamamlanır.</li><li>SLA: erişilebilirlik, destek ve olay bildirim hedefleri sözleşmede tanımlanır.</li><li>Alt işleyenler / veri lokasyonu: production sağlayıcılarıyla sözleşme öncesi doğrulanır.</li><li>Silme ve saklama: müşteri politikasına göre yapılandırılır.</li><li>AI: yüksek etkili insan kararlarında nihai karar üretmez.</li></ul><p>Oluşturma: ${new Date().toLocaleString("tr-TR")}</p></body></html>`;const url=URL.createObjectURL(new Blob([html],{type:"text/html;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="FutureHR-Security-KVKK-Pack.html";a.click();URL.revokeObjectURL(url)};
  return <section className="mt-5 rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-300"/><h2 className="text-sm font-semibold">Kurumsal güvenlik satın alma paketi</h2></div><p className="mt-1 max-w-3xl text-[11px] leading-5 text-slate-300">DPA, SLA, veri lokasyonu, alt işleyenler, saklama-silme ve AI karar sınırlarının satış öncesi kontrol başlıklarını tek pakette sunun.</p></div><button onClick={download} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-white px-4 text-xs font-semibold text-slate-950"><Download className="h-4 w-4"/>Paketi oluştur</button></div></section>
}

function OnboardingFinishPanel(){
  const org=getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]),runs=getStorageData<any[]>(STORAGE_KEYS.INTEGRATION_RUNS,[]),policy=getStorageData<any>(STORAGE_KEYS.ACCESS_POLICY,null);const steps=[{ok:org.length>0,title:"Çalışan ana verisi",href:"/organizasyon"},{ok:runs.some(r=>r.status==="success"),title:"Veri bağlantısı / aktarım",href:"/admin/entegrasyonlar"},{ok:Boolean(policy),title:"Yetki politikası",href:"/ayarlar/yetki-mimarisi"},{ok:true,title:"Türkiye kuralları",href:"/izinler"}];const done=steps.filter(s=>s.ok).length;return <section className="mt-5 rounded-2xl border border-indigo-100 bg-indigo-50/40 p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-indigo-700">Kurulum yol haritası</p><h2 className="mt-1 text-base font-semibold">Şirketi kullanıma hazırla</h2></div><strong className="text-2xl text-indigo-700">%{Math.round(done/steps.length*100)}</strong></div><div className="mt-4 grid gap-2 md:grid-cols-4">{steps.map((step,index)=><Link key={step.title} href={step.href} className="rounded-xl border border-white bg-white p-3 shadow-sm"><div className="flex items-center gap-2">{step.ok?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<CalendarClock className="h-4 w-4 text-amber-500"/>}<span className="text-[10px] font-bold text-slate-400">0{index+1}</span></div><p className="mt-2 text-xs font-semibold">{step.title}</p><p className="mt-1 text-[10px] text-slate-400">{step.ok?"Hazır":"Tamamlanmalı"}</p></Link>)}</div></section>
}

function RoleGovernancePanel(){
  const[roles,setRoles]=useState<any[]>([]);const[selected,setSelected]=useState("");const[targets,setTargets]=useState<Record<string,number>>({});const[revision,setRevision]=useState(0);const overrides=getStorageData<RoleOverride[]>(STORAGE_KEYS.ROLE_OVERRIDES,[]);void revision;
  useEffect(()=>{fetch("/api/job-architecture?limit=100",{cache:"no-store"}).then(r=>r.json()).then(p=>{const rows=Array.isArray(p?.data)?p.data:[];setRoles(rows);if(rows[0])setSelected(rows[0].canonicalTitle||rows[0].title)}).catch(()=>undefined)},[]);
  useEffect(()=>{const role=roles.find(r=>(r.canonicalTitle||r.title)===selected);const current=overrides.find(o=>o.role===selected&&o.status==="Onaylı")||overrides.find(o=>o.role===selected);setTargets(current?.targets||Object.fromEntries((role?.competencies||[]).map((c:any)=>[c.label,Number(c.target)])))},[selected,roles,revision]);
  const save=(status:"Taslak"|"Onaylı")=>{if(!selected)return;const previous=overrides.filter(o=>o.role===selected).sort((a,b)=>b.version-a.version)[0];const next:RoleOverride={id:`role-${selected}-${Date.now()}`,role:selected,version:(previous?.version||0)+1,status,targets,approvedAt:status==="Onaylı"?new Date().toISOString():undefined,updatedAt:new Date().toISOString()};setStorageData(STORAGE_KEYS.ROLE_OVERRIDES,[next,...overrides]);setRevision(v=>v+1);window.dispatchEvent(new CustomEvent("dataUpdated"))};
  return <section className="mt-5 rounded-2xl border border-indigo-100 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><BriefcaseBusiness className="h-4 w-4 text-indigo-600"/><h2 className="text-sm font-semibold">Firma rol yönetişimi</h2></div><p className="mt-1 text-[11px] text-slate-500">Rol hedefini şirketinize göre versiyonlayın; taslakları ayrı tutun, yalnız onaylı sürümü kurumsal referans olarak işaretleyin.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)} className="h-10 min-w-64 rounded-xl border border-slate-200 px-3 text-xs">{roles.map(r=><option key={r.title} value={r.canonicalTitle||r.title}>{r.canonicalTitle||r.title}</option>)}</select></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(targets).map(([label,value])=><label key={label} className="rounded-xl border border-slate-100 bg-slate-50 p-3 text-[10px] text-slate-500"><span className="block min-h-8">{label}</span><input type="number" min="1" max="5" step="0.1" value={value} onChange={e=>setTargets({...targets,[label]:Math.max(1,Math.min(5,Number(e.target.value)))})} className="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-2 text-sm font-semibold text-slate-900"/></label>)}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-[10px] text-slate-400">Son sürüm: {overrides.filter(o=>o.role===selected).sort((a,b)=>b.version-a.version)[0]?.version?`v${overrides.filter(o=>o.role===selected).sort((a,b)=>b.version-a.version)[0].version}`:"Henüz firma sürümü yok"}</p><div className="flex gap-2"><button onClick={()=>save("Taslak")} className="inline-flex h-9 items-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-semibold"><Save className="h-3.5 w-3.5"/>Taslak kaydet</button><button onClick={()=>save("Onaylı")} className="inline-flex h-9 items-center gap-2 rounded-xl bg-indigo-600 px-3 text-xs font-semibold text-white"><BadgeCheck className="h-3.5 w-3.5"/>Onayla & versiyonla</button></div></div></section>
}

function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white bg-white p-3 shadow-sm"><p className="text-[9px] font-bold uppercase tracking-[.08em] text-slate-400">{label}</p><p className="mt-2 truncate text-sm font-semibold text-slate-900" title={value}>{value}</p></div>}
