"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Crown, ShieldCheck, Users } from "lucide-react";
import { getStorageData, STORAGE_KEYS } from "../../utils/storage";
import { getCareerRole } from "../../../lib/hr/careerArchitecture";
import { rankSuccessors } from "../../../lib/hr/succession";

export default function YedeklemePage(){
  const[orgData,setOrgData]=useState<any[]>([]);const[history,setHistory]=useState<any[]>([]);const[selectedName,setSelectedName]=useState("");
  useEffect(()=>{setOrgData(getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]));setHistory(getStorageData<any[]>(STORAGE_KEYS.HISTORY_360,[]));},[]);
  const reportCounts=useMemo(()=>{const map:Record<string,number>={};orgData.forEach(e=>{const m=e["Yönetici 1"];if(m)map[m]=(map[m]||0)+1});return map},[orgData]);
  const criticalRoles=useMemo(()=>orgData.filter(e=>{const level=getCareerRole(e.Pozisyon||"").levelRank;return level>=4||(reportCounts[e["Ad Soyad"]]||0)>=2}).sort((a,b)=>getCareerRole(b.Pozisyon||"").levelRank-getCareerRole(a.Pozisyon||"").levelRank),[orgData,reportCounts]);
  useEffect(()=>{if(!selectedName&&criticalRoles.length)setSelectedName(criticalRoles[0]["Ad Soyad"])},[criticalRoles,selectedName]);
  const target=orgData.find(e=>e["Ad Soyad"]===selectedName);const ranked=useMemo(()=>target?rankSuccessors(target,orgData,history).slice(0,8):[],[target,orgData,history]);
  const readyNow=ranked.filter(r=>r.assessment.readiness==="Şimdi").length;
  return <div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-red-600">Halefiyet yönetimi</p><h1 className="mt-1 text-2xl font-semibold">Yedekleme</h1><p className="mt-1 max-w-4xl text-sm text-slate-500">Sabit “%65 hazır” kaldırıldı. Halef skoru hedef rol yetkinlik uyumu %35, seviye uyumu %15, hazır olma süresi %15, kariyer isteği %10, performans trendi %15 ve potansiyel %10 ile dinamik hesaplanır.</p></div>
  <div className="grid gap-3 sm:grid-cols-3"><Metric label="Kritik rol" value={criticalRoles.length} icon={Crown}/><Metric label="Değerlendirilen halef" value={ranked.length} icon={Users}/><Metric label="Şimdi hazır" value={readyNow} icon={ShieldCheck}/></div>
  <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-red-600"/><h2 className="text-sm font-semibold">Kritik roller</h2></div><p className="mt-1 text-xs text-slate-500">Yönetim seviyesi veya ekip sorumluluğu olan roller.</p><div className="mt-4 space-y-2">{criticalRoles.map(role=>{const active=role["Ad Soyad"]===selectedName;const career=getCareerRole(role.Pozisyon||"");return <button key={role.id??role["Ad Soyad"]} onClick={()=>setSelectedName(role["Ad Soyad"])} className={`w-full rounded-xl border p-3 text-left ${active?"border-red-300 bg-red-50":"border-slate-100 hover:bg-slate-50"}`}><div className="flex justify-between gap-2"><div><p className="text-sm font-semibold">{role["Ad Soyad"]}</p><p className="mt-1 text-xs text-slate-500">{role.Pozisyon}</p></div><span className="text-[10px] font-semibold text-slate-400">{career.level}</span></div><p className="mt-2 text-[11px] text-slate-400">{reportCounts[role["Ad Soyad"]]||0} doğrudan raporlayan</p></button>})}{!criticalRoles.length&&<p className="text-xs text-slate-500">Kritik rol bulunamadı.</p>}</div></div>
  <div className="space-y-4">{target&&<div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs uppercase tracking-wide text-slate-400">Halefi aranan rol</p><h2 className="mt-1 text-lg font-semibold">{target.Pozisyon}</h2><p className="mt-1 text-xs text-slate-500">Mevcut rol sahibi: {target["Ad Soyad"]} · {target.Departman}</p></div>}
  <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Halef adayı</th><th>Hazırlık</th><th className="text-right">Toplam</th><th className="text-right">Rol uyumu</th><th className="text-right">Seviye</th><th className="text-right">Perf. trendi</th><th className="text-right">Potansiyel</th></tr></thead><tbody>{ranked.length?ranked.map(({candidate,assessment})=><tr key={candidate.id??candidate["Ad Soyad"]}><td><p className="font-semibold">{candidate["Ad Soyad"]}</p><p className="text-[11px] text-slate-400">{candidate.Pozisyon}</p></td><td><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${assessment.readiness==="Şimdi"?"bg-emerald-50 text-emerald-700":assessment.readiness==="6–12 ay"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600"}`}>{assessment.readiness}</span></td><td className="text-right"><strong>%{assessment.score}</strong></td><td className="text-right font-mono">%{Math.round(assessment.targetRoleFit)}</td><td className="text-right font-mono">%{Math.round(assessment.levelFit)}</td><td className="text-right font-mono">%{assessment.performanceTrend}</td><td className="text-right font-mono">%{assessment.potential}</td></tr>):<tr><td colSpan={7} className="py-10 text-center text-sm text-slate-500">Halef adayı bulunmuyor.</td></tr>}</tbody></table></div></div>
  {ranked[0]&&<div className="rounded-2xl border border-red-100 bg-red-50/40 p-5"><h3 className="text-sm font-semibold text-red-950">En güçlü aday için açıklama</h3><p className="mt-1 text-xs text-red-800">{ranked[0].candidate["Ad Soyad"]} · %{ranked[0].assessment.score} · {ranked[0].assessment.readiness}</p>{ranked[0].assessment.reasons.length?<div className="mt-3 text-xs leading-5 text-red-800">{ranked[0].assessment.reasons.map(r=><p key={r}>• {r}</p>)}</div>:<p className="mt-3 text-xs text-red-800">Belirgin veri açığı yok. Yine de halefiyet kararı yönetici değerlendirmesi ve kariyer görüşmesiyle teyit edilmelidir.</p>}</div>}
  </div></div></div>}
function Metric({label,value,icon:Icon}:{label:string;value:number;icon:any}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between"><p className="text-xs text-slate-500">{label}</p><Icon className="h-4 w-4 text-red-600"/></div><p className="mt-3 text-2xl font-semibold">{value}</p></div>}
