"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Map, Target, TrendingUp } from "lucide-react";
import { POSITIONS } from "../../data/jobData";
import { getManageableEmployees } from "../../utils/hierarchy";
import { getStorageData, setStorageData, STORAGE_KEYS } from "../../utils/storage";
import { buildCareerArchitecture, calculateCareerReadiness, getCareerRole, JOB_LEVELS } from "../../../lib/hr/careerArchitecture";

export default function KariyerPage(){
  const[user,setUser]=useState<any>(null);const[orgData,setOrgData]=useState<any[]>([]);const[history,setHistory]=useState<any[]>([]);const[selectedName,setSelectedName]=useState("");const[targetPosition,setTargetPosition]=useState("");
  useEffect(()=>{setUser(getStorageData(STORAGE_KEYS.CURRENT_USER,null));setOrgData(getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]));setHistory(getStorageData<any[]>(STORAGE_KEYS.HISTORY_360,[]));},[]);
  const role=String(user?.role||"").toUpperCase();const people=useMemo(()=>{if(!user)return[];if(role==="CEO"||role==="IK")return orgData;try{return getManageableEmployees(user,orgData)}catch{return[]}},[user,orgData,role]);
  useEffect(()=>{if(!selectedName&&people.length)setSelectedName(people[0]["Ad Soyad"])},[people,selectedName]);
  const orgPerson=orgData.find((p)=>p["Ad Soyad"]===selectedName)||{};const assessment=history.find((p)=>(p.Personel||p.target)===selectedName)||{};const person={...orgPerson,...assessment};
  const currentRole=getCareerRole(orgPerson.Pozisyon||"");const architecture=useMemo(()=>buildCareerArchitecture(POSITIONS),[]);const familyRoles=architecture[currentRole.family]||[];
  useEffect(()=>{if(!targetPosition&&currentRole.title){const next=familyRoles.find((r)=>r.levelRank>currentRole.levelRank)||familyRoles.find((r)=>r.title!==currentRole.title);if(next)setTargetPosition(next.title)}},[currentRole.title,currentRole.levelRank,familyRoles,targetPosition]);
  const targetRole=getCareerRole(targetPosition);const readiness=targetPosition?calculateCareerReadiness(person,targetPosition):null;
  const updateAspiration=(value:number)=>{const next=orgData.map((p)=>p["Ad Soyad"]===selectedName?{...p,career_aspiration:value}:p);setOrgData(next);setStorageData(STORAGE_KEYS.ORG_CHART,next);window.dispatchEvent(new CustomEvent("dataUpdated"));};
  return <div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-amber-600">Kariyer mimarisi</p><h1 className="mt-1 text-2xl font-semibold">Kariyer Yolu</h1><p className="mt-1 max-w-4xl text-sm text-slate-500">Hazır bulunuşluk artık “100 − gap × 8” değildir. Endeks; hedef rol yetkinlik uyumu %50, performans %20, potansiyel %15, deneyim %10 ve kariyer isteği %5 ile hesaplanır. Sonuç terfi kararı değil, gelişim göstergesidir.</p></div>
  <div className="grid gap-5 xl:grid-cols-[340px_1fr]"><div className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="text-xs font-medium text-slate-500">Çalışan<select value={selectedName} onChange={e=>{setSelectedName(e.target.value);setTargetPosition("")}} className="mt-1 w-full rounded-xl border border-slate-200 p-2.5 text-sm">{people.map((p:any)=><option key={p.id??p["Ad Soyad"]}>{p["Ad Soyad"]}</option>)}</select></label><div className="mt-4 rounded-xl bg-amber-50 p-3"><p className="text-xs text-amber-700">Mevcut rol</p><p className="mt-1 text-sm font-semibold text-amber-950">{currentRole.title||"—"}</p><p className="mt-1 text-xs text-amber-800">{currentRole.family} · {currentRole.level} {JOB_LEVELS[currentRole.level]}</p></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-medium text-slate-500">Kariyer isteği</p><div className="mt-2 flex items-center justify-between"><span className="text-xs text-slate-500">1 düşük</span><strong>{Number(orgPerson.career_aspiration??3).toFixed(1)} / 5</strong><span className="text-xs text-slate-500">5 yüksek</span></div><input type="range" min="1" max="5" step="0.5" value={Number(orgPerson.career_aspiration??3)} onChange={e=>updateAspiration(Number(e.target.value))} className="mt-2 w-full"/></div></div>
  <div className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Map className="h-4 w-4 text-amber-600"/><h2 className="text-sm font-semibold">{currentRole.family} kariyer mimarisi</h2></div><div className="mt-5 overflow-x-auto"><div className="flex min-w-max items-center gap-2">{familyRoles.map((role,index)=><div key={role.title} className="flex items-center gap-2"><button onClick={()=>setTargetPosition(role.title)} className={`w-[180px] rounded-2xl border p-4 text-left ${role.title===currentRole.title?"border-slate-900 bg-slate-900 text-white":role.title===targetPosition?"border-amber-400 bg-amber-50":"border-slate-200 bg-white"}`}><p className="text-[10px] font-semibold uppercase tracking-wide opacity-60">{role.level} · {JOB_LEVELS[role.level]}</p><p className="mt-2 text-xs font-semibold leading-5">{role.title}</p></button>{index<familyRoles.length-1&&<ArrowRight className="h-4 w-4 text-slate-300"/>}</div>)}</div></div></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="text-xs font-medium text-slate-500">Hedef rol<select value={targetPosition} onChange={e=>setTargetPosition(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-2.5 text-sm"><optgroup label={`${currentRole.family} içi`}>{familyRoles.filter(r=>r.title!==currentRole.title).map(r=><option key={r.title}>{r.title}</option>)}</optgroup><optgroup label="Diğer roller">{POSITIONS.filter(p=>getCareerRole(p).family!==currentRole.family).map(p=><option key={p}>{p}</option>)}</optgroup></select></label>{readiness&&<div className="mt-5 grid gap-4 lg:grid-cols-[220px_1fr]"><div className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs text-slate-400">Hazır bulunuşluk endeksi</p><p className="mt-2 text-5xl font-semibold">%{readiness.index}</p><span className={`mt-3 inline-flex rounded-full px-2 py-1 text-xs font-semibold ${readiness.band==="Hazır"?"bg-emerald-400/20 text-emerald-300":readiness.band==="Yakın"?"bg-amber-400/20 text-amber-300":"bg-slate-700 text-slate-200"}`}>{readiness.band}</span><p className="mt-4 text-[11px] leading-5 text-slate-400">Bu skor otomatik terfi önerisi değildir.</p></div><div className="space-y-3"><Factor label="Yetkinlik uyumu" value={readiness.competencyFit} weight="%50"/><Factor label="Performans" value={readiness.performance} weight="%20"/><Factor label="Potansiyel" value={readiness.potential} weight="%15"/><Factor label="Deneyim / kıdem" value={readiness.experience} weight="%10"/><Factor label="Kariyer isteği" value={readiness.aspiration} weight="%5"/></div></div>}{readiness?.notes.length? <div className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{readiness.notes.map(n=><p key={n}>• {n}</p>)}</div>:null}</div></div></div>
  <div className="grid gap-4 sm:grid-cols-3"><Info icon={Target} title="Job family" text="Benzer uzmanlık alanındaki roller aynı kariyer ailesinde gruplanır."/><Info icon={TrendingUp} title="Job level" text="L1 başlangıçtan L6 üst yönetime kadar rol seviyesi ayrı tutulur."/><Info icon={Map} title="Çapraz kariyer" text="Başka aileye geçiş mümkün; endekste rol ailesi ve seviye mesafesi açıkça görünür."/></div></div>}
function Factor({label,value,weight}:{label:string;value:number;weight:string}){return <div><div className="flex justify-between text-xs"><span>{label} <span className="text-slate-400">{weight}</span></span><strong>%{value}</strong></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-500" style={{width:`${value}%`}}/></div></div>}
function Info({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><Icon className="h-4 w-4 text-amber-600"/><h3 className="mt-3 text-sm font-semibold">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>}
