"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, BriefcaseBusiness, CheckCircle2, FileText, Printer, ShieldCheck, UsersRound, WalletCards } from "lucide-react";
import { getStorageData, STORAGE_KEYS } from "@/app/utils/storage";
import { buildTalentDecisionSnapshot } from "@/lib/hr/talentDecisionChain";

type Summary={headcount:number;departments:number;measured:number;avgPerformance:number|null;lowEvidence:number;stars:number;highPotential:number;development:number;training:number;successionRisks:number;salaryCoverage:number;attendanceCoverage:number;pendingLeaves:number;risks:string[]};
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0};
const avg=(rows:number[])=>rows.length?Math.round(rows.reduce((a,b)=>a+b,0)/rows.length*100)/100:null;
const potentialScore=(snapshot:any)=>n(snapshot?.talent?.potential?.score ?? snapshot?.talent?.potentialScore ?? snapshot?.potential?.score);

function buildSummary():Summary{
  const org=getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]),history=getStorageData<any[]>(STORAGE_KEYS.HISTORY_360,[]),dev=getStorageData<any[]>(STORAGE_KEYS.DEVELOPMENT_PLANS,[]),training=getStorageData<any[]>(STORAGE_KEYS.TRAINING_ASSIGNMENTS,[]),succ=getStorageData<any[]>("hr_succession_plans",[]),pay=getStorageData<any[]>(STORAGE_KEYS.PAYROLL_RECORDS,[]),att=getStorageData<any[]>(STORAGE_KEYS.ATTENDANCE_RECORDS,[]),leaves=getStorageData<any[]>(STORAGE_KEYS.LEAVE_REQUESTS,[]);
  const snapshots=org.map(person=>buildTalentDecisionSnapshot(person,history));
  const perf=snapshots.map(x=>n(x.performance?.score)).filter(x=>x>0);
  const low=snapshots.filter(x=>n(x.evidence?.score)<60).length;
  const stars=snapshots.filter(x=>n(x.performance?.score)>=4&&potentialScore(x)>=4).length;
  const high=snapshots.filter(x=>potentialScore(x)>=4).length;
  const critical=succ.filter((r:any)=>/kritik|yüksek/i.test(String(r.criticality||"")));const noReady=critical.filter((r:any)=>!(r.candidates||[]).some((c:any)=>n(c.readinessScore)>=70)).length;
  const salaryKeys=new Set(pay.filter((r:any)=>n(r.grossSalary)>0).map((r:any)=>String(r.employeeCode||r.employeeName||"")));const orgSalary=org.filter(p=>n(p["Maaş (TL)"]||p.currentSalary)>0).length;const salaryCoverage=org.length?Math.min(100,Math.round(Math.max(orgSalary,salaryKeys.size)/org.length*100)):0;
  const attKeys=new Set(att.map((r:any)=>String(r.employeeCode||r.employeeName||"")));const attendanceCoverage=org.length?Math.min(100,Math.round(attKeys.size/org.length*100)):0;
  const pendingLeaves=leaves.filter((r:any)=>/bekli|pending/i.test(String(r.status||""))).length;const risks:string[]=[];
  if(low)risks.push(`${low} çalışan için Evidence Score %60 altında.`);if(noReady)risks.push(`${noReady} kritik rolde hazır halef görünmüyor.`);if(salaryCoverage<90)risks.push(`Ücret veri kapsamı %${salaryCoverage}; karar dönemi öncesi bordro/master-data eşleşmesi kontrol edilmeli.`);if(att.length&&attendanceCoverage<80)risks.push(`PDKS kapsamı %${attendanceCoverage}; iş yükü/mesai analizi eksik olabilir.`);if(pendingLeaves)risks.push(`${pendingLeaves} izin talebi onay bekliyor.`);
  return{headcount:org.length,departments:new Set(org.map(x=>x.Departman).filter(Boolean)).size,measured:perf.length,avgPerformance:avg(perf),lowEvidence:low,stars,highPotential:high,development:dev.length,training:training.length,successionRisks:noReady,salaryCoverage,attendanceCoverage,pendingLeaves,risks};
}

export default function ExecutiveReportsPage(){const[revision,setRevision]=useState(0);useEffect(()=>{const f=()=>setRevision(v=>v+1);window.addEventListener("dataUpdated",f);return()=>window.removeEventListener("dataUpdated",f)},[]);const s=useMemo(()=>buildSummary(),[revision]);const generated=new Date().toLocaleString("tr-TR",{dateStyle:"long",timeStyle:"short"});return <div className="mx-auto max-w-7xl space-y-5 pb-10 print:max-w-none print:bg-white print:text-black">
<header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="enterprise-eyebrow">Türkçe Yönetici Raporlama</p><h1 className="mt-1 text-2xl font-semibold">İnsan & Yetenek Yönetim Raporu</h1><p className="mt-1 max-w-4xl text-sm leading-6 text-slate-500">Yönetim kurulu/Genel Müdür için organizasyon, performans, yetenek, gelişim, halefiyet, ücret ve işgücü verisini tek karar özetinde birleştirir.</p></div><button onClick={()=>window.print()} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-semibold print:hidden dark:border-slate-700 dark:bg-slate-900"><Printer className="h-4 w-4"/>Yazdır / PDF</button></header>
<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-indigo-600"><FileText className="h-4 w-4"/>FutureHR Executive Brief</div><h2 className="mt-2 text-xl font-semibold">İnsan sermayesi karar özeti</h2><p className="mt-1 text-xs text-slate-500">Oluşturma: {generated} · Kaynak: FutureHR yetkili veri katmanı</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800 dark:border-emerald-900/50 dark:bg-emerald-950/20 dark:text-emerald-200"><strong>Karar ilkesi:</strong> Rapor sinyal üretir; işe alma, işten çıkarma, terfi ve ücret kararının nihai sahibi yetkili insandır.</div></div></section>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={UsersRound} label="Aktif organizasyon" value={`${s.headcount} kişi`} sub={`${s.departments} departman`}/><Kpi icon={BarChart3} label="Performans" value={s.avgPerformance!==null?`${s.avgPerformance}/5`:"—"} sub={`${s.measured}/${s.headcount} ölçümlü`}/><Kpi icon={BriefcaseBusiness} label="Yetenek" value={`${s.stars} yıldız`} sub={`${s.highPotential} yüksek potansiyel`}/><Kpi icon={WalletCards} label="Ücret coverage" value={`%${s.salaryCoverage}`} sub="Bordro/master-data"/><Kpi icon={ShieldCheck} label="Kanıt güveni" value={`${s.lowEvidence} düşük`} sub="Evidence < %60"/></div>
<div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><section className="enterprise-card p-5"><h2 className="text-sm font-semibold">Yönetim gündemi</h2><p className="mt-1 text-[11px] text-slate-500">Önce veri/kanıt açığını, sonra insan kararını ele alın.</p><div className="mt-4 space-y-2">{s.risks.length?s.risks.map((risk,i)=><div key={risk} className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50/70 p-3 text-xs leading-5 text-amber-900 dark:border-amber-900/40 dark:bg-amber-950/20 dark:text-amber-200"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-xl bg-white/70"><AlertTriangle className="h-3.5 w-3.5"/></span><div><strong>{i+1}. öncelik</strong><p>{risk}</p></div></div>):<div className="flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-800"><CheckCircle2 className="h-4 w-4"/>Öne çıkan bloklayıcı veri/karar riski görünmüyor.</div>}</div></section><section className="enterprise-card p-5"><h2 className="text-sm font-semibold">Operasyon göstergeleri</h2><div className="mt-4 space-y-3"><Row label="Gelişim planı" value={s.development}/><Row label="Eğitim / müdahale" value={s.training}/><Row label="Hazır halef riski" value={s.successionRisks}/><Row label="PDKS çalışan coverage" value={s.attendanceCoverage?`%${s.attendanceCoverage}`:"Veri yok"}/><Row label="Bekleyen izin" value={s.pendingLeaves}/></div></section></div>
<section className="enterprise-card p-5"><h2 className="text-sm font-semibold">Yönetim için önerilen okuma sırası</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><Step no="01" title="Kanıtı doğrula" text="Evidence, PDKS, bordro ve benchmark kapsamını kontrol edin."/><Step no="02" title="İnsan riskini ayır" text="9-Box, halefiyet, gelişim ve çalışan deneyimi sinyallerini birlikte okuyun."/><Step no="03" title="Senaryoyu test et" text="Ücret A/B/C/D ve gelişim/readiness senaryolarını karşılaştırın."/><Step no="04" title="İnsan kararı" text="Yetkili yönetici/İK değerlendirmesi ile kararı ve gerekçeyi kaydedin."/></div></section>
</div>}
function Kpi({icon:Icon,label,value,sub}:{icon:any;label:string;value:string;sub:string}){return <div className="enterprise-card p-4"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950/30"><Icon className="h-4 w-4"/></div><p className="mt-3 text-[9px] font-bold uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] text-slate-500">{sub}</p></div>}
function Row({label,value}:{label:string;value:any}){return <div className="flex items-center justify-between border-b border-slate-100 pb-2 text-xs last:border-0 dark:border-slate-800"><span className="text-slate-500">{label}</span><strong>{value}</strong></div>}
function Step({no,title,text}:{no:string;title:string;text:string}){return <div className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><span className="text-[10px] font-bold text-indigo-500">{no}</span><p className="mt-2 text-sm font-semibold">{title}</p><p className="mt-1 text-[10px] leading-5 text-slate-500">{text}</p></div>}
