"use client";

import { ChangeEvent, useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, Database, Download, FileSpreadsheet, RefreshCw, ShieldCheck, Upload } from "lucide-react";
import { getStorageData, setStorageData, STORAGE_KEYS } from "../../../utils/storage";
import { FIELD_DEFINITIONS, appendImportLog, autoMapHeaders, canonicalEmployeeFromRow, validateCanonicalBatch, type CanonicalField, type ImportSource } from "@/lib/hr/dataImport";
import { createImportSnapshot } from "@/lib/hr/importSnapshots";

type RawRow=Record<string,any>;
const SOURCES:Array<{key:ImportSource;label:string;detail:string}>=[{key:"excel",label:"Genel Excel / CSV",detail:"Standart veya şirkete özel personel listesi"},{key:"logo",label:"Logo",detail:"Logo personel/sicil dışa aktarımı"},{key:"mikro",label:"Mikro",detail:"Mikro personel kartı/listesi"},{key:"netsis",label:"Netsis",detail:"Netsis personel/sicil listesi"}];
const normalize=(value:unknown)=>String(value??"").trim().toLocaleLowerCase("tr-TR");
function display(value:unknown){if(value instanceof Date)return value.toISOString().slice(0,10);if(value&&typeof value==="object"){const o=value as any;return o.text??o.result??o.formula??"";}return value??"";}
function parseDelimited(text:string){const lines=text.split(/\r?\n/).filter(line=>line.trim());if(!lines.length)return{headers:[] as string[],rows:[] as RawRow[]};const delimiter=(lines[0].match(/;/g)?.length||0)>=(lines[0].match(/,/g)?.length||0)?";":",";const parse=(line:string)=>{const cells:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i+=1){const char=line[i];if(char==='"'&&line[i+1]==='"'&&quoted){value+='"';i+=1;continue;}if(char==='"'){quoted=!quoted;continue;}if(char===delimiter&&!quoted){cells.push(value.trim());value="";continue;}value+=char;}cells.push(value.trim());return cells;};const headers=parse(lines[0]).map((h,i)=>h||`Kolon ${i+1}`);return{headers,rows:lines.slice(1,10001).map(line=>{const values=parse(line);return Object.fromEntries(headers.map((h,i)=>[h,values[i]??""]));})};}
async function parseFile(file:File){if(file.size>10*1024*1024)throw new Error("Dosya 10 MB sınırını aşıyor.");if(/\.csv$/i.test(file.name))return parseDelimited(await file.text());const ExcelJS=await import("exceljs");const workbook=new ExcelJS.Workbook();await workbook.xlsx.load((await file.arrayBuffer()) as any);const sheet=workbook.worksheets.find(s=>s.actualRowCount>0)||workbook.worksheets[0];if(!sheet)return{headers:[],rows:[]};const headers:string[]=[];const headerRow=sheet.getRow(1);for(let c=1;c<=Math.max(headerRow.cellCount,sheet.columnCount);c+=1)headers.push(String(display(headerRow.getCell(c).value)||`Kolon ${c}`).trim());const rows:RawRow[]=[];for(let r=2;r<=Math.min(sheet.rowCount,10001);r+=1){const row=sheet.getRow(r);const record:RawRow={};let has=false;headers.forEach((h,i)=>{const v=display(row.getCell(i+1).value);record[h]=v;if(String(v).trim())has=true;});if(has)rows.push(record);}return{headers,rows};}
function csvReport(errors:string[],warnings:string[]){const lines=["Tür;Mesaj",...errors.map(x=>`HATA;"${x.replace(/"/g,'""')}"`),...warnings.map(x=>`UYARI;"${x.replace(/"/g,'""')}"`)];const url=URL.createObjectURL(new Blob(["\uFEFF"+lines.join("\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="FutureHR_Veri_Aktarim_Kontrol_Raporu.csv";a.click();URL.revokeObjectURL(url);}

export default function VeriAktarimiPage(){
  const inputRef=useRef<HTMLInputElement|null>(null);const[source,setSource]=useState<ImportSource>("excel");const[fileName,setFileName]=useState("");const[headers,setHeaders]=useState<string[]>([]);const[rows,setRows]=useState<RawRow[]>([]);const[mapping,setMapping]=useState<Partial<Record<CanonicalField,string>>>({});const[loading,setLoading]=useState(false);const[result,setResult]=useState("");
  const employees=useMemo(()=>rows.map(row=>canonicalEmployeeFromRow(row,mapping)),[rows,mapping]);const validation=useMemo(()=>validateCanonicalBatch(employees),[employees]);const missingRequired=FIELD_DEFINITIONS.filter(field=>field.required&&!mapping[field.key]);const mappedCount=Object.values(mapping).filter(Boolean).length;const current=getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]);
  const dryRun=useMemo(()=>{let created=0,updated=0,skipped=0;employees.forEach(emp=>{if(!emp["Ad Soyad"]||!emp.Departman||!emp.Pozisyon){skipped+=1;return;}const id=String(emp.id||"").trim(),name=normalize(emp["Ad Soyad"]);const exists=current.some(item=>(id&&String(item.id||item.employee_id||"").trim()===id)||normalize(item["Ad Soyad"])===name);if(exists)updated+=1;else created+=1;});return{created,updated,skipped};},[employees,current]);
  const reset=()=>{setFileName("");setHeaders([]);setRows([]);setMapping({});setResult("");if(inputRef.current)inputRef.current.value="";};
  const handleSource=(next:ImportSource)=>{setSource(next);if(headers.length)setMapping(autoMapHeaders(headers,next));};
  const handleFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setLoading(true);setResult("");try{const parsed=await parseFile(file);if(!parsed.headers.length)throw new Error("Başlık satırı bulunamadı.");setFileName(file.name);setHeaders(parsed.headers);setRows(parsed.rows);setMapping(autoMapHeaders(parsed.headers,source));}catch(error){reset();setResult(`Dosya okunamadı: ${error instanceof Error?error.message:"bilinmeyen hata"}`);}finally{setLoading(false);}};
  const apply=()=>{if(!rows.length||missingRequired.length||!validation.valid)return;createImportSnapshot(`Veri Aktarım Merkezi · ${fileName}`,source,[STORAGE_KEYS.ORG_CHART]);const next=[...current];let created=0,updated=0,skipped=0;employees.forEach((employee,index)=>{if(!employee["Ad Soyad"]||!employee.Departman||!employee.Pozisyon){skipped+=1;return;}const id=String(employee.id||"").trim(),name=normalize(employee["Ad Soyad"]);const existing=next.findIndex(item=>(id&&String(item.id||item.employee_id||"").trim()===id)||normalize(item["Ad Soyad"])===name);const record={...(existing>=0?next[existing]:{}),...employee,id:id||(existing>=0?next[existing]?.id:`emp-import-${Date.now()}-${index}`),import_source:source,import_file:fileName,imported_at:new Date().toISOString()};if(existing>=0){next[existing]=record;updated+=1;}else{next.push(record);created+=1;}});setStorageData(STORAGE_KEYS.ORG_CHART,next);appendImportLog({source,fileName,totalRows:rows.length,importedRows:created+updated,skippedRows:skipped,updatedRows:updated,createdRows:created,mappedFields:mappedCount});window.dispatchEvent(new CustomEvent("dataUpdated"));setResult(`${created+updated} kayıt uygulandı: ${created} yeni · ${updated} güncellendi · ${skipped} atlandı. İşlem öncesi snapshot oluşturuldu.`);};
  const downloadTemplate=async()=>{const ExcelJS=await import("exceljs");const wb=new ExcelJS.Workbook();const sh=wb.addWorksheet("FutureHR Personel");sh.addRow(["Personel Kodu","Ad Soyad","Departman","Pozisyon","1. Yönetici","2. Yönetici","İşe Giriş Tarihi","Lokasyon","Şube","Maliyet Merkezi","Çalışan Tipi","İşgücü Tipi","Kadro Durumu"]);sh.addRow(["P001","Örnek Çalışan","Finans","Finans Uzmanı","Örnek Yönetici","","2024-01-15","İstanbul","Merkez Ofis","CC-300","Tam Zamanlı","Beyaz Yaka","Aktif"]);sh.getRow(1).font={bold:true};sh.columns.forEach(c=>c.width=20);const buffer=await wb.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([buffer as BlobPart],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}));const a=document.createElement("a");a.href=url;a.download="FutureHR_Personel_Aktarim_Sablonu.xlsx";a.click();URL.revokeObjectURL(url);};
  const blocked=Boolean(missingRequired.length||validation.errors.length);
  return <div className="mx-auto max-w-7xl space-y-5 pb-6"><header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="enterprise-eyebrow">Data Onboarding · Türkiye</p><h1 className="mt-1 text-2xl font-semibold">Veri Aktarım Merkezi</h1><p className="mt-1 max-w-4xl text-sm leading-6 text-slate-500">Excel/CSV çıktısını akıllı eşleme, dry-run, mükerrer kontrol, hata raporu, açık onay ve geri alma snapshotı ile çalışan ana verisine aktarın.</p></div><button onClick={downloadTemplate} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-semibold dark:border-slate-700 dark:bg-slate-900"><Download className="h-4 w-4"/>FutureHR şablonu</button></header>
    <div className="rounded-2xl border border-blue-200 bg-blue-50/70 p-4 text-xs leading-5 text-blue-900 dark:border-blue-900/50 dark:bg-blue-950/20 dark:text-blue-200"><strong>Entegrasyon yaklaşımı:</strong> Logo, Mikro ve Netsis için yaygın dışa aktarım başlıkları eşlenir; bu V1 dosya adaptörüdür, üretici sertifikalı resmî API entegrasyonu değildir.</div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{SOURCES.map(profile=><button key={profile.key} onClick={()=>handleSource(profile.key)} className={`rounded-2xl border p-4 text-left ${source===profile.key?"border-indigo-300 bg-indigo-50/70":"border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"}`}><div className="flex items-center justify-between"><FileSpreadsheet className="h-5 w-5 text-indigo-500"/>{source===profile.key&&<CheckCircle2 className="h-4 w-4 text-indigo-600"/>}</div><p className="mt-3 text-sm font-semibold">{profile.label}</p><p className="mt-1 text-[10px] text-slate-500">{profile.detail}</p></button>)}</section>
    <div className="grid items-start gap-4 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-4"><section className="enterprise-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">1. Dosyayı yükle</h2><p className="mt-1 text-[11px] text-slate-500">.xlsx / .csv · 10 MB · 10.000 veri satırı</p></div>{fileName&&<button onClick={reset} className="inline-flex items-center gap-1 text-[10px] font-semibold text-slate-500"><RefreshCw className="h-3.5 w-3.5"/>Sıfırla</button>}</div><input ref={inputRef} type="file" accept=".xlsx,.csv" onChange={handleFile} className="hidden"/><button onClick={()=>inputRef.current?.click()} disabled={loading} className="mt-4 flex min-h-28 w-full flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50/60"><Upload className="h-6 w-6 text-indigo-500"/><p className="mt-2 text-sm font-semibold">{loading?"Kontrol ediliyor…":fileName||"Excel / CSV dosyasını seç"}</p><p className="mt-1 text-[10px] text-slate-400">Onay vermeden çalışan listesine yazılmaz.</p></button></section>
      {headers.length>0&&<section className="enterprise-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="text-sm font-semibold">2. Sütun eşleme</h2><p className="mt-1 text-[11px] text-slate-500">Zorunlu: Ad Soyad, Departman, Pozisyon. Ücret alanı hassastır; genel organizasyon aktarımında boş bırakılabilir.</p></div><div className="grid gap-3 p-5 md:grid-cols-2">{FIELD_DEFINITIONS.map(field=><label key={field.key}><span className="mb-1 flex items-center gap-1 text-[10px] font-bold uppercase text-slate-500">{field.label}{field.required&&<b className="text-red-500">*</b>}{field.sensitive&&<ShieldCheck className="h-3 w-3 text-amber-500"/>}</span><select value={mapping[field.key]||""} onChange={e=>setMapping({...mapping,[field.key]:e.target.value||undefined})} className="h-9 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs dark:border-slate-700 dark:bg-slate-950"><option value="">Eşleme yok</option>{headers.map(header=><option key={header} value={header}>{header}</option>)}</select></label>)}</div></section>}
    </div><aside className="space-y-4"><section className="enterprise-card p-5"><div className="flex items-center gap-2"><Database className="h-4 w-4 text-indigo-600"/><h2 className="text-sm font-semibold">3. Dry-run / kalite kontrol</h2></div><div className="mt-4 grid grid-cols-2 gap-2"><Stat label="Okunan" value={rows.length}/><Stat label="Eşlenen alan" value={mappedCount}/><Stat label="Yeni" value={dryRun.created}/><Stat label="Güncellenecek" value={dryRun.updated}/><Stat label="Atlanacak" value={dryRun.skipped}/><Stat label="Uyarı" value={validation.warnings.length}/></div>{missingRequired.length>0&&<Message tone="error" text={`Eksik zorunlu eşleme: ${missingRequired.map(x=>x.label).join(", ")}`}/>} {validation.errors.length>0&&<Message tone="error" text={`${validation.errors.length} bloklayıcı hata bulundu.`}/>} {validation.warnings.length>0&&<Message tone="warn" text={`${validation.warnings.length} veri uyarısı bulundu; uygulamadan önce inceleyin.`}/>} {(validation.errors.length>0||validation.warnings.length>0)&&<button onClick={()=>csvReport(validation.errors,validation.warnings)} className="mt-2 text-[10px] font-semibold text-indigo-600">Kontrol raporunu indir</button>}<button disabled={!rows.length||blocked} onClick={apply} className="mt-4 inline-flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 text-xs font-semibold text-white disabled:opacity-40"><CheckCircle2 className="h-4 w-4"/>Kontrol edilen veriyi uygula</button></section>{result&&<div className="rounded-xl border border-slate-200 bg-white p-3 text-xs leading-5 dark:border-slate-800 dark:bg-slate-900">{result}</div>}<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-[10px] leading-5 text-amber-800"><AlertTriangle className="mr-1 inline h-3.5 w-3.5"/>Demo transaction: uygulama öncesi snapshot alınır; üstteki “Son aktarımı geri al” kontrolü ile eski veriye dönülebilir.</div></aside></div>
  </div>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950/50"><p className="text-[9px] font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>}
function Message({tone,text}:{tone:"error"|"warn";text:string}){return <div className={`mt-3 rounded-lg p-2 text-[10px] ${tone==="error"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{text}</div>}
