"use client";

import { ChangeEvent, useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Database, Download, FileSpreadsheet, RefreshCw, ShieldCheck, Upload, WalletCards, UsersRound } from "lucide-react";
import { getStorageData, setStorageData, STORAGE_KEYS } from "../../../utils/storage";
import {
  ATTENDANCE_FIELD_DEFINITIONS,
  FIELD_DEFINITIONS,
  PAYROLL_FIELD_DEFINITIONS,
  appendImportLog,
  autoMapGenericHeaders,
  autoMapHeaders,
  canonicalAttendanceFromRow,
  canonicalEmployeeFromRow,
  canonicalPayrollFromRow,
  detectImportDataset,
  validateAttendanceBatch,
  validateCanonicalBatch,
  validatePayrollBatch,
  type AttendanceField,
  type CanonicalField,
  type ImportDataset,
  type ImportSource,
  type PayrollField,
} from "@/lib/hr/dataImport";
import { createImportSnapshot } from "@/lib/hr/importSnapshots";

type RawRow = Record<string, any>;
type Mapping = Record<string, string | undefined>;
interface SheetData { name: string; headers: string[]; rows: RawRow[]; }

const SOURCES:Array<{key:ImportSource;label:string;detail:string}>=[
  {key:"excel",label:"Genel Excel / CSV",detail:"Şirkete özel personel, bordro veya PDKS çıktısı"},
  {key:"logo",label:"Logo",detail:"Logo personel / bordro dışa aktarımı"},
  {key:"mikro",label:"Mikro",detail:"Mikro personel / ücret dışa aktarımı"},
  {key:"netsis",label:"Netsis",detail:"Netsis sicil / bordro dışa aktarımı"},
];
const DATASETS:Array<{key:ImportDataset;label:string;icon:any;detail:string}>=[
  {key:"employee",label:"Personel & Özlük",icon:UsersRound,detail:"Organizasyon ve çalışan master-data"},
  {key:"payroll",label:"Bordro & Ücret",icon:WalletCards,detail:"Dönemsel brüt/net ücret kayıtları"},
  {key:"attendance",label:"PDKS & Puantaj",icon:Clock3,detail:"Giriş/çıkış, çalışma ve fazla mesai"},
];
const normalize=(value:unknown)=>String(value??"").trim().toLocaleLowerCase("tr-TR");
function display(value:unknown){if(value instanceof Date)return value.toISOString().slice(0,10);if(value&&typeof value==="object"){const o=value as any;return o.text??o.result??o.formula??"";}return value??"";}
function parseDelimited(text:string):SheetData[]{const lines=text.split(/\r?\n/).filter(line=>line.trim());if(!lines.length)return[];const delimiter=(lines[0].match(/;/g)?.length||0)>=(lines[0].match(/,/g)?.length||0)?";":",";const parse=(line:string)=>{const cells:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i+=1){const char=line[i];if(char==='"'&&line[i+1]==='"'&&quoted){value+='"';i+=1;continue;}if(char==='"'){quoted=!quoted;continue;}if(char===delimiter&&!quoted){cells.push(value.trim());value="";continue;}value+=char;}cells.push(value.trim());return cells;};const headers=parse(lines[0]).map((h,i)=>h||`Kolon ${i+1}`);return[{name:"CSV",headers,rows:lines.slice(1,10001).map(line=>{const values=parse(line);return Object.fromEntries(headers.map((h,i)=>[h,values[i]??""]));})}];}
async function parseFile(file:File):Promise<SheetData[]>{if(file.size>15*1024*1024)throw new Error("Dosya 15 MB sınırını aşıyor.");if(/\.csv$/i.test(file.name))return parseDelimited(await file.text());const ExcelJS=await import("exceljs");const workbook=new ExcelJS.Workbook();await workbook.xlsx.load((await file.arrayBuffer()) as any);return workbook.worksheets.filter(sheet=>sheet.actualRowCount>0).slice(0,12).map(sheet=>{const headers:string[]=[];const headerRow=sheet.getRow(1);for(let c=1;c<=Math.max(headerRow.cellCount,sheet.columnCount);c+=1)headers.push(String(display(headerRow.getCell(c).value)||`Kolon ${c}`).trim());const rows:RawRow[]=[];for(let r=2;r<=Math.min(sheet.rowCount,10001);r+=1){const row=sheet.getRow(r);const record:RawRow={};let has=false;headers.forEach((h,i)=>{const v=display(row.getCell(i+1).value);record[h]=v;if(String(v).trim())has=true;});if(has)rows.push(record);}return{name:sheet.name,headers,rows};});}
function definitionsFor(dataset:ImportDataset){return dataset==="employee"?FIELD_DEFINITIONS:dataset==="payroll"?PAYROLL_FIELD_DEFINITIONS:ATTENDANCE_FIELD_DEFINITIONS;}
function mappingFor(headers:string[],dataset:ImportDataset,source:ImportSource):Mapping{if(dataset==="employee")return autoMapHeaders(headers,source) as Mapping;if(dataset==="payroll")return autoMapGenericHeaders(headers,PAYROLL_FIELD_DEFINITIONS) as Mapping;return autoMapGenericHeaders(headers,ATTENDANCE_FIELD_DEFINITIONS) as Mapping;}
function csvReport(errors:string[],warnings:string[]){const lines=["Tür;Mesaj",...errors.map(x=>`HATA;"${x.replace(/"/g,'""')}"`),...warnings.map(x=>`UYARI;"${x.replace(/"/g,'""')}"`)];const url=URL.createObjectURL(new Blob(["\uFEFF"+lines.join("\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="FutureHR_Veri_Aktarim_Kontrol_Raporu.csv";a.click();URL.revokeObjectURL(url);}
function keyForPayroll(row:any){return `${normalize(row.employeeCode)}|${normalize(row.period)}|${normalize(row.source)}`;}
function keyForAttendance(row:any){return `${normalize(row.employeeCode)}|${normalize(row.date)}|${normalize(row.source)}`;}

export default function VeriAktarimiPage(){
  const inputRef=useRef<HTMLInputElement|null>(null);
  const[source,setSource]=useState<ImportSource>("excel");const[fileName,setFileName]=useState("");const[sheets,setSheets]=useState<SheetData[]>([]);const[activeSheet,setActiveSheet]=useState(0);const[datasets,setDatasets]=useState<Record<number,ImportDataset>>({});const[mappings,setMappings]=useState<Record<number,Mapping>>({});const[loading,setLoading]=useState(false);const[result,setResult]=useState("");
  const sheet=sheets[activeSheet];const dataset=datasets[activeSheet]||"employee";const mapping=mappings[activeSheet]||{};

  const activeQuality=useMemo(()=>{
    if(!sheet)return{errors:[] as string[],warnings:[] as string[],valid:false,validRows:0,mapped:0};
    const mapped=Object.values(mapping).filter(Boolean).length;
    if(dataset==="employee"){const records=sheet.rows.map(row=>canonicalEmployeeFromRow(row,mapping as Partial<Record<CanonicalField,string>>));const check=validateCanonicalBatch(records);return{...check,validRows:records.filter(row=>row["Ad Soyad"]&&row.Departman&&row.Pozisyon).length,mapped};}
    if(dataset==="payroll"){const check=validatePayrollBatch(sheet.rows.map(row=>canonicalPayrollFromRow(row,mapping as Partial<Record<PayrollField,string>>,source)));const identifier=Boolean(mapping.employeeCode||mapping.employeeName);const errors=identifier?check.errors:["Personel Kodu veya Ad Soyad alanlarından en az biri eşlenmelidir.",...check.errors];return{...check,errors,valid:check.valid&&identifier,validRows:check.records.length,mapped};}
    const check=validateAttendanceBatch(sheet.rows.map(row=>canonicalAttendanceFromRow(row,mapping as Partial<Record<AttendanceField,string>>,source)));const identifier=Boolean(mapping.employeeCode||mapping.employeeName);const errors=identifier?check.errors:["Personel Kodu veya Ad Soyad alanlarından en az biri eşlenmelidir.",...check.errors];return{...check,errors,valid:check.valid&&identifier,validRows:check.records.length,mapped};
  },[sheet,dataset,mapping,source]);

  const reset=()=>{setFileName("");setSheets([]);setDatasets({});setMappings({});setActiveSheet(0);setResult("");if(inputRef.current)inputRef.current.value="";};
  const handleSource=(next:ImportSource)=>{setSource(next);if(sheets.length){setMappings(Object.fromEntries(sheets.map((item,index)=>[index,mappingFor(item.headers,datasets[index]||detectImportDataset(item.headers),next)])));}};
  const handleDataset=(next:ImportDataset)=>{if(!sheet)return;setDatasets(prev=>({...prev,[activeSheet]:next}));setMappings(prev=>({...prev,[activeSheet]:mappingFor(sheet.headers,next,source)}));};
  const handleFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setLoading(true);setResult("");try{const parsed=await parseFile(file);if(!parsed.length)throw new Error("Okunabilir çalışma sayfası bulunamadı.");const nextDatasets=Object.fromEntries(parsed.map((item,index)=>[index,detectImportDataset(item.headers)])) as Record<number,ImportDataset>;const nextMappings=Object.fromEntries(parsed.map((item,index)=>[index,mappingFor(item.headers,nextDatasets[index],source)]));setFileName(file.name);setSheets(parsed);setDatasets(nextDatasets);setMappings(nextMappings);setActiveSheet(0);}catch(error){reset();setResult(`Dosya okunamadı: ${error instanceof Error?error.message:"bilinmeyen hata"}`);}finally{setLoading(false);}};

  const applyAll=()=>{
    if(!sheets.length)return;
    const allChecks=sheets.map((item,index)=>{const kind=datasets[index]||detectImportDataset(item.headers);const map=mappings[index]||mappingFor(item.headers,kind,source);if(kind==="employee")return validateCanonicalBatch(item.rows.map(row=>canonicalEmployeeFromRow(row,map as any))).valid;if(kind==="payroll"){const check=validatePayrollBatch(item.rows.map(row=>canonicalPayrollFromRow(row,map as any,source)));return check.valid&&Boolean(map.employeeCode||map.employeeName);}const check=validateAttendanceBatch(item.rows.map(row=>canonicalAttendanceFromRow(row,map as any,source)));return check.valid&&Boolean(map.employeeCode||map.employeeName);});
    if(allChecks.some(value=>!value)){setResult("Aktarım durduruldu: en az bir çalışma sayfasında bloklayıcı hata var. Sayfaları tek tek kontrol edin.");return;}
    createImportSnapshot(`Türkiye Veri Onboarding · ${fileName}`,source,[STORAGE_KEYS.ORG_CHART,STORAGE_KEYS.PAYROLL_RECORDS,STORAGE_KEYS.ATTENDANCE_RECORDS]);
    const org=[...getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[])];const payroll=[...getStorageData<any[]>(STORAGE_KEYS.PAYROLL_RECORDS,[])];const attendance=[...getStorageData<any[]>(STORAGE_KEYS.ATTENDANCE_RECORDS,[])];
    let employeeCreated=0,employeeUpdated=0,payrollWritten=0,attendanceWritten=0;
    sheets.forEach((item,index)=>{const kind=datasets[index]||"employee";const map=mappings[index]||{};
      if(kind==="employee"){
        item.rows.map(row=>canonicalEmployeeFromRow(row,map as any)).forEach((employee,rowIndex)=>{if(!employee["Ad Soyad"]||!employee.Departman||!employee.Pozisyon)return;const id=String(employee.id||"").trim(),name=normalize(employee["Ad Soyad"]);const existing=org.findIndex(row=>(id&&String(row.id||row.employee_id||"").trim()===id)||normalize(row["Ad Soyad"])===name);const record={...(existing>=0?org[existing]:{}),...employee,id:id||(existing>=0?org[existing]?.id:`emp-import-${Date.now()}-${index}-${rowIndex}`),import_source:source,import_file:fileName,import_sheet:item.name,imported_at:new Date().toISOString()};if(existing>=0){org[existing]=record;employeeUpdated+=1;}else{org.push(record);employeeCreated+=1;}});
      } else if(kind==="payroll"){
        validatePayrollBatch(item.rows.map(row=>canonicalPayrollFromRow(row,map as any,source))).records.forEach(record=>{const key=keyForPayroll(record);const existing=payroll.findIndex(row=>keyForPayroll(row)===key);const enriched={...record,import_file:fileName,import_sheet:item.name,imported_at:new Date().toISOString()};if(existing>=0)payroll[existing]=enriched;else payroll.push(enriched);payrollWritten+=1;const orgIndex=org.findIndex(row=>normalize(row.id||row.employee_id)===normalize(record.employeeCode)||normalize(row["Ad Soyad"])===normalize(record.employeeName));if(orgIndex>=0&&record.currency.toUpperCase()==="TRY"&&record.grossSalary&&record.grossSalary>0)org[orgIndex]={...org[orgIndex],["Maaş (TL)"]:record.grossSalary,last_payroll_period:record.period,last_payroll_sync_at:new Date().toISOString()};});
      } else {
        validateAttendanceBatch(item.rows.map(row=>canonicalAttendanceFromRow(row,map as any,source))).records.forEach(record=>{const key=keyForAttendance(record);const existing=attendance.findIndex(row=>keyForAttendance(row)===key);const enriched={...record,import_file:fileName,import_sheet:item.name,imported_at:new Date().toISOString()};if(existing>=0)attendance[existing]=enriched;else attendance.push(enriched);attendanceWritten+=1;});
      }
      appendImportLog({source,fileName:`${fileName} · ${item.name}`,dataset:kind,totalRows:item.rows.length,importedRows:item.rows.length,skippedRows:0,updatedRows:0,createdRows:0,mappedFields:Object.values(map).filter(Boolean).length});
    });
    setStorageData(STORAGE_KEYS.ORG_CHART,org);setStorageData(STORAGE_KEYS.PAYROLL_RECORDS,payroll);setStorageData(STORAGE_KEYS.ATTENDANCE_RECORDS,attendance);window.dispatchEvent(new CustomEvent("dataUpdated"));
    setResult(`Aktarım tamamlandı · Personel: ${employeeCreated} yeni / ${employeeUpdated} güncelleme · Bordro: ${payrollWritten} kayıt · PDKS: ${attendanceWritten} kayıt. İşlem öncesi geri alma snapshotı oluşturuldu.`);
  };

  const downloadTemplate=async()=>{const ExcelJS=await import("exceljs");const wb=new ExcelJS.Workbook();const add=(name:string,headers:string[],sample:any[])=>{const sh=wb.addWorksheet(name);sh.addRow(headers);sh.addRow(sample);sh.getRow(1).font={bold:true};sh.columns.forEach(c=>c.width=20);};add("Personel",["Personel Kodu","Ad Soyad","Departman","Pozisyon","1. Yönetici","2. Yönetici","İşe Giriş Tarihi","Lokasyon","Şube","Maliyet Merkezi","Çalışan Tipi","İşgücü Tipi","Kadro Durumu"],["P001","Örnek Çalışan","Finans","Finans Uzmanı","Örnek Yönetici","","2024-01-15","İstanbul","Merkez","CC-300","Tam Zamanlı","Beyaz Yaka","Aktif"]);add("Bordro",["Personel Kodu","Ad Soyad","Bordro Dönemi","Brüt Ücret","Net Ücret","Para Birimi"],["P001","Örnek Çalışan","2026-08","75000","56000","TRY"]);add("PDKS",["Personel Kodu","Ad Soyad","Tarih","İlk Giriş","Son Çıkış","Çalışılan Dakika","Fazla Mesai Dakika","Eksik Çalışma Dakika"],["P001","Örnek Çalışan","2026-09-01","08:30","17:30","480","0","0"]);const buffer=await wb.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([buffer as BlobPart],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}));const a=document.createElement("a");a.href=url;a.download="FutureHR_Turkiye_Onboarding_Sablonu.xlsx";a.click();URL.revokeObjectURL(url);};

  const defs=definitionsFor(dataset);const blocked=!sheet||!activeQuality.valid;
  return <div className="mx-auto max-w-7xl space-y-5 pb-8">
    <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="enterprise-eyebrow">Enterprise Data Onboarding · Türkiye</p><h1 className="mt-1 text-2xl font-semibold">Veri Aktarım Merkezi</h1><p className="mt-1 max-w-4xl text-sm leading-6 text-slate-500">Tek Excel dosyasındaki Personel, Bordro ve PDKS sayfalarını otomatik tanır; eşleme, dry-run, mükerrer kontrol ve geri alma snapshotı ile FutureHR canonical modeline aktarır.</p></div><button onClick={downloadTemplate} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-semibold dark:border-slate-700 dark:bg-slate-900"><Download className="h-4 w-4"/>3 sayfalı FutureHR şablonu</button></header>
    <div className="rounded-2xl border border-indigo-200 bg-indigo-50/60 p-4 text-xs leading-5 text-indigo-900 dark:border-indigo-900/50 dark:bg-indigo-950/20 dark:text-indigo-200"><strong>Güvenli onboarding:</strong> Dosya önce tarayıcıda okunur ve önizlenir. Kullanıcı açıkça “Uygula” demeden demo veri katmanına yazılmaz. Ücret ve puantaj kayıtları ayrı veri kümelerinde tutulur; production SaaS modunda tenant-scoped backend karşılıkları kullanılmalıdır.</div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{SOURCES.map(profile=><button key={profile.key} onClick={()=>handleSource(profile.key)} className={`rounded-2xl border p-4 text-left transition ${source===profile.key?"border-indigo-300 bg-indigo-50/70 dark:bg-indigo-950/20":"border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"}`}><div className="flex items-center justify-between"><FileSpreadsheet className="h-5 w-5 text-indigo-500"/>{source===profile.key&&<CheckCircle2 className="h-4 w-4 text-indigo-600"/>}</div><p className="mt-3 text-sm font-semibold">{profile.label}</p><p className="mt-1 text-[10px] leading-4 text-slate-500">{profile.detail}</p></button>)}</section>
    <div className="grid items-start gap-4 xl:grid-cols-[1.08fr_.92fr]"><div className="space-y-4">
      <section className="enterprise-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">1. Excel / CSV dosyası</h2><p className="mt-1 text-[11px] text-slate-500">.xlsx / .csv · 15 MB · sayfa başına 10.000 satır</p></div>{fileName&&<button onClick={reset} className="inline-flex items-center gap-1 text-[10px] font-semibold text-slate-500"><RefreshCw className="h-3.5 w-3.5"/>Sıfırla</button>}</div><input ref={inputRef} type="file" accept=".xlsx,.csv" onChange={handleFile} className="hidden"/><button onClick={()=>inputRef.current?.click()} disabled={loading} className="mt-4 flex min-h-28 w-full flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50/60 dark:border-slate-700 dark:bg-slate-950/40"><Upload className="h-6 w-6 text-indigo-500"/><p className="mt-2 text-sm font-semibold">{loading?"Dosya ve sayfalar analiz ediliyor…":fileName||"Excel / CSV dosyasını seç"}</p><p className="mt-1 text-[10px] text-slate-400">Çalışma sayfası türü başlıklardan otomatik tespit edilir.</p></button></section>
      {sheets.length>0&&<section className="enterprise-card overflow-hidden"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-slate-400">2. Çalışma sayfaları</p><div className="mt-3 flex flex-wrap gap-2">{sheets.map((item,index)=><button key={`${item.name}-${index}`} onClick={()=>setActiveSheet(index)} className={`rounded-xl border px-3 py-2 text-left ${activeSheet===index?"border-indigo-300 bg-indigo-50 text-indigo-800":"border-slate-200 text-slate-500 dark:border-slate-700"}`}><span className="block text-xs font-semibold">{item.name}</span><span className="mt-0.5 block text-[9px]">{DATASETS.find(x=>x.key===(datasets[index]||"employee"))?.label} · {item.rows.length} satır</span></button>)}</div></div>
        {sheet&&<><div className="grid gap-2 border-b border-slate-100 p-4 sm:grid-cols-3 dark:border-slate-800">{DATASETS.map(item=>{const Icon=item.icon;return <button key={item.key} onClick={()=>handleDataset(item.key)} className={`rounded-xl border p-3 text-left ${dataset===item.key?"border-emerald-300 bg-emerald-50/70":"border-slate-200 dark:border-slate-700"}`}><Icon className="h-4 w-4 text-emerald-600"/><p className="mt-2 text-xs font-semibold">{item.label}</p><p className="mt-1 text-[9px] leading-4 text-slate-500">{item.detail}</p></button>})}</div><div className="grid gap-3 p-5 md:grid-cols-2">{defs.map((field:any)=><label key={field.key}><span className="mb-1 flex items-center gap-1 text-[10px] font-bold uppercase text-slate-500">{field.label}{field.required&&<b className="text-red-500">*</b>}{field.sensitive&&<ShieldCheck className="h-3 w-3 text-amber-500"/>}</span><select value={mapping[field.key]||""} onChange={e=>setMappings(prev=>({...prev,[activeSheet]:{...mapping,[field.key]:e.target.value||undefined}}))} className="h-9 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs dark:border-slate-700 dark:bg-slate-950"><option value="">Eşleme yok</option>{sheet.headers.map(header=><option key={header} value={header}>{header}</option>)}</select></label>)}</div></>}
      </section>}
    </div><aside className="space-y-4"><section className="enterprise-card p-5"><div className="flex items-center gap-2"><Database className="h-4 w-4 text-indigo-600"/><h2 className="text-sm font-semibold">3. Dry-run / kalite kontrol</h2></div><div className="mt-4 grid grid-cols-2 gap-2"><Stat label="Dosya sayfası" value={sheets.length}/><Stat label="Aktif satır" value={sheet?.rows.length||0}/><Stat label="Eşlenen alan" value={activeQuality.mapped}/><Stat label="Geçerli kayıt" value={activeQuality.validRows}/><Stat label="Hata" value={activeQuality.errors.length}/><Stat label="Uyarı" value={activeQuality.warnings.length}/></div>{activeQuality.errors.length>0&&<Message tone="error" text={`${activeQuality.errors.length} bloklayıcı hata: ${activeQuality.errors.slice(0,2).join(" · ")}`}/>} {activeQuality.warnings.length>0&&<Message tone="warn" text={`${activeQuality.warnings.length} veri uyarısı: ${activeQuality.warnings.slice(0,2).join(" · ")}`}/>} {(activeQuality.errors.length>0||activeQuality.warnings.length>0)&&<button onClick={()=>csvReport(activeQuality.errors,activeQuality.warnings)} className="mt-2 text-[10px] font-semibold text-indigo-600">Kontrol raporunu indir</button>}<button disabled={!sheets.length||blocked} onClick={applyAll} className="mt-4 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 text-xs font-semibold text-white disabled:opacity-40"><CheckCircle2 className="h-4 w-4"/>Dosyadaki tüm sayfaları uygula</button><p className="mt-2 text-[9px] leading-4 text-slate-400">Diğer çalışma sayfalarında bloklayıcı hata varsa aktarım başlamaz.</p></section>{result&&<div className="rounded-xl border border-slate-200 bg-white p-3 text-xs leading-5 dark:border-slate-800 dark:bg-slate-900">{result}</div>}<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-[10px] leading-5 text-amber-800"><AlertTriangle className="mr-1 inline h-3.5 w-3.5"/><strong>Production notu:</strong> Logo/Mikro/Netsis “dosya profili” üreticinin resmî canlı API bağlantısı değildir; canlı senkronizasyon Entegrasyon Merkezi'ndeki server-side adapter üzerinden yürütülür.</div></aside></div>
  </div>;
}

function Stat({label,value}:{label:string;value:number|string}){return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950/50"><p className="text-[9px] font-bold uppercase tracking-[.08em] text-slate-400">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>}
function Message({tone,text}:{tone:"error"|"warn";text:string}){return <div className={`mt-3 rounded-xl border p-3 text-[10px] leading-5 ${tone==="error"?"border-red-200 bg-red-50 text-red-700":"border-amber-200 bg-amber-50 text-amber-800"}`}>{text}</div>}
