"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CheckCircle2, DollarSign, Play, Plus, Save, ShieldCheck } from "lucide-react";
import { getStorageData, setStorageData, STORAGE_KEYS } from "../../utils/storage";
import { calculateMarketAverages, processEmployeeData, runScenarioLogic, MarketReference, SimulationResult } from "../../utils/salarySimulation";
import { COMPENSATION_STAGES, COMPENSATION_STAGE_LABELS, CompensationCycle, CompensationStage, canApplySalaryChanges, createCompensationCycle, nextCompensationStage } from "../../../lib/hr/compensationWorkflow";
import { useNotifications } from "../../../context/NotificationContext";

interface ExternalBenchmark extends MarketReference { id:string; source?:string; updatedAt:string; }

export default function MaasPage(){
  const {showToast}=useNotifications();
  const[orgData,setOrgData]=useState<any[]>([]);const[history,setHistory]=useState<any[]>([]);const[benchmarks,setBenchmarks]=useState<ExternalBenchmark[]>([]);const[cycles,setCycles]=useState<CompensationCycle[]>([]);const[scenario,setScenario]=useState<"A"|"B"|"C"|"D">("C");const[inflation,setInflation]=useState(35);const[benchmarkForm,setBenchmarkForm]=useState({department:"",position:"",amount:""});
  const reload=()=>{setOrgData(getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]));setHistory(getStorageData<any[]>(STORAGE_KEYS.HISTORY_360,[]));setBenchmarks(getStorageData<ExternalBenchmark[]>(STORAGE_KEYS.MARKET_BENCHMARKS,[]));setCycles(getStorageData<CompensationCycle[]>(STORAGE_KEYS.COMPENSATION_CYCLES,[]));};
  useEffect(()=>reload(),[]);
  const employees=useMemo(()=>processEmployeeData(orgData,history),[orgData,history]);const internalRefs=useMemo(()=>calculateMarketAverages(employees),[employees]);
  const effectiveRefs=useMemo(()=>internalRefs.map(ref=>{const external=benchmarks.find(b=>b.Departman===ref.Departman&&b.Pozisyon===ref.Pozisyon);return external?{Departman:external.Departman,Pozisyon:external.Pozisyon,"Piyasa Ortalaması":external["Piyasa Ortalaması"]}:ref}),[internalRefs,benchmarks]);
  const results=useMemo(()=>runScenarioLogic(employees,effectiveRefs,inflation,scenario),[employees,effectiveRefs,inflation,scenario]);
  const activeCycle=cycles.find(c=>c.stage!=="EFFECTIVE")||cycles[0];
  const totalCurrent=employees.reduce((sum,e)=>sum+e["Mevcut Maaş"],0);const totalNew=results.reduce((sum,e)=>sum+e["Yeni Maaş"],0);const increase=totalNew-totalCurrent;
  const saveCycles=(next:CompensationCycle[])=>{setCycles(next);setStorageData(STORAGE_KEYS.COMPENSATION_CYCLES,next);};
  const newCycle=()=>{const cycle=createCompensationCycle(`${new Date().getFullYear()} Ücret Dönemi`);saveCycles([cycle,...cycles]);showToast("Yeni ücret döngüsü oluşturuldu.","success")};
  const saveSimulation=()=>{if(!activeCycle)return newCycle();const next=cycles.map(c=>c.id===activeCycle.id?{...c,scenario,inflationRate:inflation,results,stage:"DRAFT_SIMULATION" as CompensationStage}:c);saveCycles(next);showToast("Simülasyon taslağa kaydedildi.","success")};
  const advance=()=>{if(!activeCycle)return;const nextStage=nextCompensationStage(activeCycle.stage);const next=cycles.map(c=>c.id===activeCycle.id?{...c,stage:nextStage,...(nextStage==="FINALIZED"?{finalizedAt:new Date().toISOString()}:{} )}:c);saveCycles(next);showToast(`${COMPENSATION_STAGE_LABELS[nextStage]} aşamasına geçildi.`,"success")};
  const applyFinal=()=>{if(!activeCycle||!canApplySalaryChanges(activeCycle.stage))return;const finalResults=(activeCycle.results||results) as SimulationResult[];const map=new Map(finalResults.map(r=>[r["Ad Soyad"],r["Yeni Maaş"]]));const nextOrg=orgData.map(p=>map.has(p["Ad Soyad"])?{...p,"Maaş (TL)":map.get(p["Ad Soyad"])}:p);setStorageData(STORAGE_KEYS.ORG_CHART,nextOrg);const updatedCycles=cycles.map(c=>c.id===activeCycle.id?{...c,stage:"EFFECTIVE" as CompensationStage,appliedAt:new Date().toISOString(),effectiveDate:new Date().toISOString().slice(0,10)}:c);saveCycles(updatedCycles);setOrgData(nextOrg);window.dispatchEvent(new CustomEvent("dataUpdated"));showToast("Kesinleşen yeni ücret dönemi yürürlüğe alındı.","success")};
  const addBenchmark=(e:FormEvent)=>{e.preventDefault();const amount=Number(benchmarkForm.amount);if(!benchmarkForm.department||!benchmarkForm.position||!amount)return;const entry:ExternalBenchmark={id:`bench-${Date.now()}`,Departman:benchmarkForm.department,Pozisyon:benchmarkForm.position,"Piyasa Ortalaması":amount,source:"Dış kaynak / kullanıcı girişi",updatedAt:new Date().toISOString()};const next=[entry,...benchmarks.filter(b=>!(b.Departman===entry.Departman&&b.Pozisyon===entry.Pozisyon))];setBenchmarks(next);setStorageData(STORAGE_KEYS.MARKET_BENCHMARKS,next);setBenchmarkForm({department:"",position:"",amount:""});};
  return <div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-teal-700">Ücret & bütçe analitiği</p><h1 className="mt-1 text-2xl font-semibold">Maaş Simülasyonu</h1><p className="mt-1 max-w-4xl text-sm text-slate-500">İç veriden hesaplanan değerler artık “İç Ücret Referansı”dır; dış piyasa benchmarkı ayrıca girilir. Simülasyon hiçbir maaşı doğrudan değiştirmez.</p></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-teal-700"/><h2 className="text-sm font-semibold">Ücret döngüsü</h2></div><p className="mt-1 text-xs text-slate-500">Simülasyon → Yönetici Talepleri → Bütçe Kontrolü → Onay → Kesinleştirme → Yeni ücret dönemi</p></div>{!activeCycle&&<button onClick={newCycle} className="rounded-xl bg-teal-700 px-4 py-2 text-sm font-semibold text-white"><Plus className="mr-1 inline h-4 w-4"/>Döngü başlat</button>}</div><div className="mt-5 overflow-x-auto"><div className="flex min-w-max items-center gap-2">{COMPENSATION_STAGES.map((stage,index)=>{const active=activeCycle?.stage===stage;const done=activeCycle?COMPENSATION_STAGES.indexOf(activeCycle.stage)>index:false;return <div key={stage} className="flex items-center gap-2"><div className={`rounded-xl border px-3 py-2 text-xs font-semibold ${active?"border-teal-700 bg-teal-700 text-white":done?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-slate-200 text-slate-400"}`}>{done&&<CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>}{COMPENSATION_STAGE_LABELS[stage]}</div>{index<COMPENSATION_STAGES.length-1&&<span className="text-slate-300">→</span>}</div>})}</div></div>{activeCycle&&<div className="mt-4 flex flex-wrap gap-2"><button onClick={saveSimulation} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold"><Save className="mr-1 inline h-3.5 w-3.5"/>Simülasyonu kaydet</button>{activeCycle.stage==="MANAGER_INPUT"&&<Link href="/yonetici/maas-talep" className="rounded-xl border border-teal-200 bg-teal-50 px-3 py-2 text-xs font-semibold text-teal-800">Yönetici taleplerini aç</Link>}{activeCycle.stage!=="EFFECTIVE"&&activeCycle.stage!=="FINALIZED"&&<button onClick={advance} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Sonraki aşama</button>}{activeCycle.stage==="FINALIZED"&&<button onClick={applyFinal} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white"><Play className="mr-1 inline h-3.5 w-3.5"/>Yeni ücret dönemini yürürlüğe al</button>}</div>}</div>
  <div className="grid gap-5 xl:grid-cols-[1fr_380px]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-medium text-slate-500">Senaryo<select value={scenario} onChange={e=>setScenario(e.target.value as any)} className="mt-1 block rounded-xl border border-slate-200 p-2.5 text-sm"><option value="A">A · Bütçe Dostu</option><option value="B">B · Ücret Referansı Eşitleme</option><option value="C">C · Dengeli</option><option value="D">D · Yönetici Talepleri</option></select></label><label className="text-xs font-medium text-slate-500">Enflasyon %<input type="number" value={inflation} onChange={e=>setInflation(Number(e.target.value))} className="mt-1 block w-28 rounded-xl border border-slate-200 p-2.5 text-sm"/></label></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Mini label="Mevcut aylık toplam" value={`${totalCurrent.toLocaleString("tr-TR")} ₺`}/><Mini label="Simüle yeni toplam" value={`${totalNew.toLocaleString("tr-TR")} ₺`}/><Mini label="Aylık artış etkisi" value={`${increase.toLocaleString("tr-TR")} ₺`}/></div><div className="mt-5 overflow-x-auto"><table className="w-full"><thead><tr><th>Çalışan</th><th>Departman</th><th className="text-right">Mevcut</th><th className="text-right">Yeni</th><th className="text-right">Zam %</th><th>Referans</th></tr></thead><tbody>{results.map(r=>{const external=benchmarks.some(b=>b.Departman===r.Departman&&b.Pozisyon===r.Pozisyon);return <tr key={r["Ad Soyad"]}><td>{r["Ad Soyad"]}</td><td>{r.Departman}</td><td className="text-right font-mono">{r["Mevcut Maaş"].toLocaleString("tr-TR")}</td><td className="text-right font-mono font-semibold">{r["Yeni Maaş"].toLocaleString("tr-TR")}</td><td className="text-right font-mono">%{r["Zam Oranı (%)"].toFixed(1)}</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${external?"bg-blue-50 text-blue-700":"bg-slate-100 text-slate-600"}`}>{external?"Dış Piyasa Benchmarkı":"İç Ücret Referansı"}</span></td></tr>})}</tbody></table></div></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><DollarSign className="h-4 w-4 text-teal-700"/><h2 className="text-sm font-semibold">Dış piyasa benchmarkı</h2></div><p className="mt-1 text-xs text-slate-500">Demo aşamasında araştırılmış dış veri manuel girilir. Girilmezse simülasyonda açıkça “İç Ücret Referansı” kullanılır.</p><form onSubmit={addBenchmark} className="mt-4 space-y-3"><select value={benchmarkForm.department} onChange={e=>setBenchmarkForm({...benchmarkForm,department:e.target.value,position:""})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"><option value="">Departman seçin</option>{Array.from(new Set(employees.map(e=>e.Departman))).map(d=><option key={d}>{d}</option>)}</select><select value={benchmarkForm.position} onChange={e=>setBenchmarkForm({...benchmarkForm,position:e.target.value})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"><option value="">Pozisyon seçin</option>{Array.from(new Set(employees.filter(e=>!benchmarkForm.department||e.Departman===benchmarkForm.department).map(e=>e.Pozisyon))).map(p=><option key={p}>{p}</option>)}</select><input type="number" placeholder="Piyasa aylık brüt referansı" value={benchmarkForm.amount} onChange={e=>setBenchmarkForm({...benchmarkForm,amount:e.target.value})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"/><button className="w-full rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white">Benchmarkı kaydet</button></form><div className="mt-4 space-y-2">{benchmarks.slice(0,6).map(b=><div key={b.id} className="rounded-xl bg-slate-50 p-3 text-xs"><p className="font-semibold">{b.Pozisyon}</p><p className="mt-1 text-slate-500">{b.Departman} · {b["Piyasa Ortalaması"].toLocaleString("tr-TR")} ₺</p></div>)}</div></div></div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
