"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleAlert, FileCheck2, KeyRound, Link2, Scale, ShieldCheck, Smartphone, UsersRound } from "lucide-react";
import { getStorageData, STORAGE_KEYS } from "@/app/utils/storage";
import { readinessChecklist, TURKEY_CONNECTORS } from "@/lib/hr/turkeyEnterprise";

const STORAGE_READY=new Set(["excel","reports","leave","privacy","mobile"]);
type Status={id:string;state:"ready"|"credentials"|"control";detail:string;href:string};

export default function TurkiyeUyumPage(){const[connector,setConnector]=useState<Record<string,any>>({});const[sso,setSso]=useState<any>(null);const[revision,setRevision]=useState(0);
  useEffect(()=>{const load=async()=>{const pairs=await Promise.all(TURKEY_CONNECTORS.map(async c=>{try{const r=await fetch(`/api/integrations/${c.id}`,{cache:"no-store"});return[c.id,await r.json()] as const}catch{return[c.id,{state:"error",configured:false}] as const}}));setConnector(Object.fromEntries(pairs));try{setSso(await (await fetch("/api/sso/status",{cache:"no-store"})).json())}catch{setSso(null)}};void load();const f=()=>setRevision(v=>v+1);window.addEventListener("dataUpdated",f);return()=>window.removeEventListener("dataUpdated",f)},[]);
  const statuses=useMemo<Status[]>(()=>{
    const payroll=getStorageData<any[]>(STORAGE_KEYS.PAYROLL_RECORDS,[]),attendance=getStorageData<any[]>(STORAGE_KEYS.ATTENDANCE_RECORDS,[]),org=getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]),logs=getStorageData<any[]>("hr_ai_audit_log",[]);
    const apiReady=["logo","netsis","mikro","sap_successfactors"].filter(id=>connector[id]?.configured).length;
    return[
      {id:"erp",state:apiReady?"ready":"credentials",detail:apiReady?`${apiReady}/4 ERP/HCM connector yapılandırıldı.`:"Logo, Netsis, Mikro ve SAP adapter kodu hazır; tenant credential/endpoint bekleniyor.",href:"/admin/entegrasyonlar"},
      {id:"excel",state:"ready",detail:"Excel/CSV dry-run, alan eşleme, mükerrer kontrol ve snapshot akışı aktif.",href:"/admin/veri-aktarimi"},
      {id:"pdks",state:connector.pdks?.configured||attendance.length?"ready":"credentials",detail:attendance.length?`${attendance.length} PDKS/puantaj kaydı veri katmanında.`:"Vendor bağımsız PDKS adapter hazır; endpoint/credential bekleniyor.",href:"/admin/entegrasyonlar"},
      {id:"payroll",state:connector.payroll?.configured||payroll.length?"ready":"credentials",detail:payroll.length?`${payroll.length} bordro kaydı canonical payroll alanında.`:"Bordro veri köprüsü hazır; kurum servisi/credential bekleniyor.",href:"/admin/entegrasyonlar"},
      {id:"master",state:org.length?"ready":"control",detail:org.length?`${org.length} çalışan master-data kaydı; Personel Kodu / organizasyon eşleşmesi kullanılabilir.`:"Master-data henüz yüklenmedi.",href:"/organizasyon"},
      {id:"privacy",state:"ready",detail:`RBAC, hassas ücret/halefiyet scope'u, anonim pulse ve ${logs.length} AI audit kaydıyla kontrol katmanı aktif.`,href:"/admin/guven-kvkk"},
      {id:"reports",state:"ready",detail:"Türkçe yönetici karar raporu ve Yazdır/PDF akışı aktif.",href:"/yonetici-raporlari"},
      {id:"leave",state:"ready",detail:"4857 m.53 tabanlı 1 yıl hak kazanma, 14/20/26 gün ve yaş minimumu kontrol motoruna işlendi.",href:"/izinler"},
      {id:"sso",state:sso?.google?.configured||sso?.entra?.configured?"ready":"credentials",detail:`Google: ${sso?.google?.configured?"hazır":"credential bekliyor"} · Entra: ${sso?.entra?.configured?"hazır":"credential bekliyor"}. Doğrulanmış e-posta mevcut FutureHR hesabına eşlenir; auto-provision kapalı.`,href:"/sistem-girisi"},
      {id:"mobile",state:"ready",detail:"Responsive sidebar, mobil alt dock ve standalone/PWA manifest katmanı aktif.",href:"/dashboard"},
    ];
  },[connector,sso,revision]);
  const ready=statuses.filter(x=>x.state==="ready").length;const checklist=readinessChecklist();
  return <div className="mx-auto max-w-7xl space-y-5 pb-10"><header><p className="futurehr-page-eyebrow">Türkiye Enterprise Readiness</p><h1 className="futurehr-page-title">Türkiye Uyum & Entegrasyon Merkezi</h1><p className="futurehr-page-lede">FutureHR'ın Türkiye'deki kurumsal kullanım için teknik hazırlığını 10 iş akışında izleyin. Bu ekran hukuki sertifika veya dış servis bağlantısı iddiası değil; ürün kontrol/readiness görünümüdür.</p></header>
  <div className="grid gap-3 sm:grid-cols-4"><Metric icon={ShieldCheck} label="Hazır iş akışı" value={`${ready}/10`}/><Metric icon={Link2} label="Connector" value={TURKEY_CONNECTORS.length}/><Metric icon={KeyRound} label="SSO" value={sso?.google?.configured||sso?.entra?.configured?"Yapılandırıldı":"Credential bekliyor"}/><Metric icon={Scale} label="Mevzuat motoru" value="TR v1"/></div>
  <section className="grid gap-3 lg:grid-cols-2">{checklist.map(item=>{const st=statuses.find(x=>x.id===item.id)!;return <Link href={st.href} key={item.id} className="enterprise-card group flex items-start gap-4 p-4 transition-transform hover:-translate-y-0.5"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${st.state==="ready"?"bg-emerald-50 text-emerald-600 dark:bg-emerald-950/30":st.state==="credentials"?"bg-amber-50 text-amber-600 dark:bg-amber-950/30":"bg-blue-50 text-blue-600 dark:bg-blue-950/30"}`}>{st.state==="ready"?<CheckCircle2 className="h-5 w-5"/>:<CircleAlert className="h-5 w-5"/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold">{item.label}</h2>{item.critical&&<span className="rounded-full bg-rose-50 px-2 py-0.5 text-[8px] font-bold uppercase text-rose-600 dark:bg-rose-950/30">Kritik</span>}<span className={`rounded-full px-2 py-0.5 text-[8px] font-bold ${st.state==="ready"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30":st.state==="credentials"?"bg-amber-50 text-amber-700 dark:bg-amber-950/30":"bg-blue-50 text-blue-700 dark:bg-blue-950/30"}`}>{st.state==="ready"?"Kodda aktif":st.state==="credentials"?"Credential bekliyor":"Kontrol gerekli"}</span></div><p className="mt-1 text-[10.5px] leading-5 text-slate-500">{st.detail}</p></div><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-slate-300 transition-transform group-hover:translate-x-1"/></Link>})}</section>
  <div className="grid gap-4 xl:grid-cols-3"><Info icon={FileCheck2} title="Veri minimizasyonu" text="Bordro/PDKS entegrasyonlarında yalnız FutureHR karar katmanı için gereken alanlar canonical modele alınır; connector secret değerleri istemciye gönderilmez."/><Info icon={UsersRound} title="İnsan onayı" text="AI; işe alma, terfi, ücret, işten çıkarma veya halef atamasında nihai karar sahibi değildir. Evidence ve insan değerlendirmesi korunur."/><Info icon={Smartphone} title="Mobil-first yönetim" text="Yönetici Özeti, Karar Motoru, ekip/gelişim ve bildirimlere mobil dock üzerinden hızlı erişim sağlanır."/></div>
  <div className="rounded-2xl border border-amber-200 bg-amber-50/70 p-4 text-[10.5px] leading-5 text-amber-900 dark:border-amber-900/40 dark:bg-amber-950/20 dark:text-amber-200"><strong>Hukuki sınır:</strong> FutureHR mevzuat kontrol mantığı ve teknik güvenlik mekanizması sağlar; kurum sözleşmeleri, toplu iş sözleşmeleri, güncel resmi takvimler ve somut hukuki durumlar için yetkili İK/hukuk doğrulaması gerekir.</div></div>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <div className="enterprise-card p-4"><Icon className="h-4 w-4 text-indigo-500"/><p className="mt-3 text-[9px] font-bold uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 text-base font-semibold">{value}</p></div>}
function Info({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="enterprise-card p-5"><Icon className="h-5 w-5 text-[#2f6664]"/><h3 className="mt-3 text-sm font-semibold">{title}</h3><p className="mt-1 text-[10.5px] leading-5 text-slate-500">{text}</p></div>}
