"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleAlert, FileCheck2, KeyRound, Link2, Scale, ShieldCheck, Smartphone, UsersRound } from "lucide-react";
import { getStorageData, STORAGE_KEYS } from "@/app/utils/storage";
import { readinessChecklist, TURKEY_CONNECTORS } from "@/lib/hr/turkeyEnterprise";

type Status={id:string;state:"ready"|"credentials"|"control";detail:string;technical?:string;href:string};
const FRIENDLY_LABELS:Record<string,string>={erp:"ERP / İK sistemi bağlantısı",excel:"Excel ile çalışan aktarımı",pdks:"PDKS / puantaj bağlantısı",payroll:"Bordro / ücret bağlantısı",master:"Çalışan ana bilgileri",privacy:"Gizlilik, KVKK ve yetkiler",reports:"Türkçe yönetim raporları",leave:"Türkiye izin kuralları",sso:"Google / Microsoft ile giriş",mobile:"Mobil kullanım"};

export default function TurkiyeUyumPage(){const[connector,setConnector]=useState<Record<string,any>>({});const[sso,setSso]=useState<any>(null);const[revision,setRevision]=useState(0);
  useEffect(()=>{const load=async()=>{const pairs=await Promise.all(TURKEY_CONNECTORS.map(async c=>{try{const r=await fetch(`/api/integrations/${c.id}`,{cache:"no-store"});return[c.id,await r.json()] as const}catch{return[c.id,{state:"error",configured:false}] as const}}));setConnector(Object.fromEntries(pairs));try{setSso(await (await fetch("/api/sso/status",{cache:"no-store"})).json())}catch{setSso(null)}};void load();const f=()=>setRevision(v=>v+1);window.addEventListener("dataUpdated",f);return()=>window.removeEventListener("dataUpdated",f)},[]);
  const statuses=useMemo<Status[]>(()=>{
    const payroll=getStorageData<any[]>(STORAGE_KEYS.PAYROLL_RECORDS,[]),attendance=getStorageData<any[]>(STORAGE_KEYS.ATTENDANCE_RECORDS,[]),org=getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]),logs=getStorageData<any[]>("hr_ai_audit_log",[]);
    const apiReady=["logo","netsis","mikro","sap_successfactors"].filter(id=>connector[id]?.configured).length;
    return[
      {id:"erp",state:apiReady?"ready":"credentials",detail:apiReady?`${apiReady} kurumsal sistem bağlantısı kullanıma hazır.`:"Kullandığınız ERP / İK sistemi için kurum erişim bilgileri tanımlanmalı.",technical:"Logo, Netsis, Mikro ve SAP adapter kodu hazır; tenant endpoint/credential yapılandırması bekleniyor.",href:"/admin/entegrasyonlar"},
      {id:"excel",state:"ready",detail:"Excel ve CSV dosyaları kontrollü olarak içe aktarılabilir.",technical:"Dry-run, alan eşleme, mükerrer kontrol ve snapshot akışı aktif.",href:"/admin/veri-aktarimi"},
      {id:"pdks",state:connector.pdks?.configured||attendance.length?"ready":"credentials",detail:attendance.length?`${attendance.length} puantaj kaydı hazır.`:"Kullandığınız PDKS sistemi için bağlantı bilgileri tanımlanmalı.",technical:"Vendor bağımsız PDKS adapter hazır; endpoint/credential bekleniyor.",href:"/admin/entegrasyonlar"},
      {id:"payroll",state:connector.payroll?.configured||payroll.length?"ready":"credentials",detail:payroll.length?`${payroll.length} bordro kaydı hazır.`:"Kullandığınız bordro sistemi için bağlantı bilgileri tanımlanmalı.",technical:"Bordro veri köprüsü hazır; kurum servisi/credential bekleniyor.",href:"/admin/entegrasyonlar"},
      {id:"master",state:org.length?"ready":"control",detail:org.length?`${org.length} çalışanın temel bilgileri sisteme eklendi.`:"Henüz çalışan verisi eklenmedi. Çalışanları ekleyerek başlayın.",technical:"Personel Kodu ve organizasyon eşleşmesi ana veri katmanında kullanılır.",href:"/organizasyon"},
      {id:"privacy",state:"ready",detail:"Kullanıcı yetkileri, hassas veri koruması ve KVKK kontrolleri etkin.",technical:`RBAC, hassas ücret/halefiyet scope'u, anonim pulse ve ${logs.length} AI audit kaydı aktif.`,href:"/admin/guven-kvkk"},
      {id:"reports",state:"ready",detail:"Türkçe yönetim raporları görüntülenebilir ve PDF olarak alınabilir.",technical:"Türkçe yönetici karar raporu ve Yazdır/PDF akışı aktif.",href:"/yonetici-raporlari"},
      {id:"leave",state:"ready",detail:"Türkiye yıllık izin hakları için temel kontroller sistemde hazır.",technical:"4857 m.53 tabanlı 1 yıl hak kazanma, 14/20/26 gün ve yaş minimumu kontrol motoruna işlendi.",href:"/izinler"},
      {id:"sso",state:sso?.google?.configured||sso?.entra?.configured?"ready":"credentials",detail:sso?.google?.configured||sso?.entra?.configured?"Kurumsal hesabınızla giriş kullanıma hazır.":"Google veya Microsoft hesabıyla giriş için kurum bağlantısı kurulmalı.",technical:`Google: ${sso?.google?.configured?"hazır":"credential bekliyor"} · Entra: ${sso?.entra?.configured?"hazır":"credential bekliyor"}. Auto-provision kapalı.`,href:"/sistem-girisi"},
      {id:"mobile",state:"ready",detail:"FutureHR telefon ve tablet ekranlarında kullanılabilir.",technical:"Responsive sidebar, mobil alt dock ve standalone/PWA manifest katmanı aktif.",href:"/dashboard"},
    ];
  },[connector,sso,revision]);
  const ready=statuses.filter(x=>x.state==="ready").length;const checklist=readinessChecklist();
  return <div className="mx-auto max-w-7xl space-y-5 pb-10">
    <header className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-indigo-600">Sistem Yönetimi</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Türkiye Ayarları & Hazırlık</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600 dark:text-slate-300">FutureHR'ın şirketinizde kullanıma hazır olan ve kurulum gerektiren alanlarını burada görebilirsiniz. Sarı kartlar hata değildir; yalnızca kurumunuza ait bağlantı veya veri adımı gerektiğini gösterir.</p></header>
    <div className="grid gap-3 sm:grid-cols-4"><Metric icon={ShieldCheck} label="Kullanıma hazır" value={`${ready}/10`}/><Metric icon={Link2} label="Bağlantı seçeneği" value={TURKEY_CONNECTORS.length}/><Metric icon={KeyRound} label="Kurumsal giriş" value={sso?.google?.configured||sso?.entra?.configured?"Hazır":"Kurulum gerekiyor"}/><Metric icon={Scale} label="Türkiye kuralları" value="Aktif"/></div>
    <section aria-labelledby="setup-status-title"><div className="mb-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">Kurulum Durumu</p><h2 id="setup-status-title" className="mt-1 text-lg font-semibold">Neler hazır, neler yapılmalı?</h2></div><div className="grid gap-3 lg:grid-cols-2">{checklist.map(item=>{const st=statuses.find(x=>x.id===item.id)!;return <Link href={st.href} key={item.id} className="enterprise-card group flex items-start gap-4 p-4 transition-transform hover:-translate-y-0.5"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${st.state==="ready"?"bg-emerald-50 text-emerald-600 dark:bg-emerald-950/30":st.state==="credentials"?"bg-amber-50 text-amber-600 dark:bg-amber-950/30":"bg-blue-50 text-blue-600 dark:bg-blue-950/30"}`}>{st.state==="ready"?<CheckCircle2 className="h-5 w-5"/>:<CircleAlert className="h-5 w-5"/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{FRIENDLY_LABELS[item.id]||item.label}</h3>{item.critical&&<span className="rounded-full bg-indigo-50 px-2 py-0.5 text-[8px] font-bold uppercase text-indigo-700 dark:bg-indigo-950/30 dark:text-indigo-300">Öncelikli</span>}<StatePill state={st.state}/></div><p className="mt-1 text-[10.5px] leading-5 text-slate-500">{st.detail}</p>{st.technical&&<details onClick={(event)=>event.preventDefault()} className="mt-2 text-[9.5px] text-slate-400"><summary className="cursor-pointer font-semibold">Teknik ayrıntılar</summary><p className="mt-1 leading-4">{st.technical}</p></details>}</div><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-slate-300 transition-transform group-hover:translate-x-1"/></Link>})}</div></section>
    <div className="grid gap-4 xl:grid-cols-3"><Info icon={FileCheck2} title="Veriler kontrollü işlenir" text="Bordro ve puantaj bağlantılarında yalnız FutureHR'ın ihtiyaç duyduğu alanlar kullanılır. Bağlantı şifreleri kullanıcı ekranında gösterilmez."/><Info icon={UsersRound} title="Nihai karar insanda" text="FutureHR öneri ve analiz üretir; işe alma, terfi, ücret veya işten çıkarma kararını otomatik vermez."/><Info icon={Smartphone} title="Mobil kullanım hazır" text="Ana sayfa, ekip işlemleri, gelişim ve bildirimler telefon ve tablet ekranlarında kullanılabilir."/></div>
    <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-[10.5px] leading-5 text-slate-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300"><strong>Not:</strong> FutureHR temel mevzuat kontrollerini destekler. Şirketinize özel sözleşme, toplu iş sözleşmesi veya hukuki durumlarda İK / hukuk doğrulaması yapılmalıdır.</div>
  </div>}
function StatePill({state}:{state:Status["state"]}){const text=state==="ready"?"Kullanıma hazır":state==="credentials"?"Kurulum gerekiyor":"Kontrol edin";return <span className={`rounded-full px-2 py-0.5 text-[8px] font-bold ${state==="ready"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300":state==="credentials"?"bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-300":"bg-blue-50 text-blue-700 dark:bg-blue-950/30 dark:text-blue-300"}`}>{text}</span>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <div className="enterprise-card p-4"><Icon className="h-4 w-4 text-indigo-500"/><p className="mt-3 text-[9px] font-bold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 text-base font-semibold">{value}</p></div>}
function Info({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="enterprise-card p-5"><Icon className="h-5 w-5 text-[#2f6664]"/><h3 className="mt-3 text-sm font-semibold">{title}</h3><p className="mt-1 text-[10.5px] leading-5 text-slate-500">{text}</p></div>}
