"use client";

import { useEffect, useState } from "react";
import { Building2, CheckCircle2, FileCheck2, Link2, ShieldCheck, TriangleAlert } from "lucide-react";
import { fetchTurkiyeComplianceStatus, updateTurkiyeConnector, type TurkiyeComplianceStatus } from "@/lib/hr/decisionIntelligenceClient";
import { SAAS_DATA_MODE } from "@/lib/hr/saasWorkforceClient";

const demoStatus:TurkiyeComplianceStatus={country_code:"TR",locale:"tr-TR",checks:[{key:"tenant_isolation",label:"Şirket verisi tenant sınırında",status:"ready"},{key:"secure_auth",label:"Sunucu tarafı güvenli oturum",status:"not_configured"},{key:"legacy_api",label:"Legacy API production'da kapalı",status:"ready"},{key:"ai_human_oversight",label:"AI kararlarında insan onayı",status:"ready"},{key:"pulse_privacy",label:"Bireysel pulse ham verisi kapalı",status:"ready"},{key:"connector_readiness",label:"Türkiye bordro/SGK entegrasyon hazırlığı",status:"not_configured"}],connectors:{sgk:{enabled:false,mode:"manual",label:"SGK"},logo:{enabled:false,mode:"file",label:"Logo"},mikro:{enabled:false,mode:"file",label:"Mikro"},netsis:{enabled:false,mode:"file",label:"Netsis"}},notice:"Demo görünümü teknik hazırlığı gösterir; canlı SGK işlemi veya hukuki görüş değildir."};
const PROVIDERS=[{key:"sgk",label:"SGK",text:"İşe giriş/çıkış ve işveren süreçleri için güvenli entegrasyon kontratı."},{key:"logo",label:"Logo",text:"Bordro/çalışan verisi için kontrollü dosya veya API adaptörü."},{key:"mikro",label:"Mikro",text:"Bordro ve çalışan ana verisi adaptör hazırlığı."},{key:"netsis",label:"Netsis",text:"ERP/İK veri aktarımı adaptör hazırlığı."}] as const;

export default function TurkiyeUyumPage(){
  const[data,setData]=useState<TurkiyeComplianceStatus|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[saving,setSaving]=useState("");
  const reload=async()=>{try{setData(SAAS_DATA_MODE?await fetchTurkiyeComplianceStatus():demoStatus);}catch(err){setError(err instanceof Error?err.message:"Türkiye uyum durumu yüklenemedi.");}finally{setLoading(false);}};
  useEffect(()=>{void reload();},[]);
  const toggle=async(provider:"sgk"|"logo"|"mikro"|"netsis")=>{if(!SAAS_DATA_MODE||!data)return;setSaving(provider);setError("");try{const current=data.connectors[provider];await updateTurkiyeConnector(provider,{enabled:!current.enabled,mode:current.mode==="api"?"api":"file",label:PROVIDERS.find(item=>item.key===provider)?.label});await reload();}catch(err){setError(err instanceof Error?err.message:"Bağlayıcı ayarı kaydedilemedi.");}finally{setSaving("");}};
  const ready=data?.checks.filter(item=>item.status==="ready").length||0,total=data?.checks.length||0;

  return <div className="space-y-5">
    <header className="futurehr-page-header"><p className="futurehr-page-eyebrow">Türkiye Uyum Katmanı</p><h1 className="futurehr-page-title">Uyum & Entegrasyon Hazırlığı</h1><p className="futurehr-page-lede">KVKK-by-design, insan onaylı AI ve Türkiye bordro/işveren entegrasyonlarını aynı teknik kontrol katmanında görün. Bu ekran hukuki görüş değil; sistem readiness ve veri güvenliği görünümüdür.</p></header>
    <div className="grid gap-3 sm:grid-cols-3"><Metric icon={ShieldCheck} label="Hazır kontrol" value={loading?"…":`${ready}/${total}`}/><Metric icon={Building2} label="Ülke profili" value={data?.country_code||"TR"}/><Metric icon={Link2} label="Aktif bağlayıcı" value={loading?"…":Object.values(data?.connectors||{}).filter(item=>item.enabled).length}/></div>
    {error&&<div className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-xs text-rose-700">{error}</div>}
    <div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]">
      <section className="enterprise-card overflow-hidden"><div className="border-b border-slate-200 px-5 py-4 dark:border-slate-800"><p className="enterprise-eyebrow">Production readiness</p><h2 className="mt-1 text-sm font-semibold">Güven ve uyum kontrolleri</h2></div><div className="divide-y divide-slate-100 px-5 dark:divide-slate-800">{(data?.checks||[]).map(check=><div key={check.key} className="flex items-center justify-between gap-4 py-3"><div className="flex items-center gap-2.5">{check.status==="ready"?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<TriangleAlert className="h-4 w-4 text-amber-600"/>}<span className="text-xs font-medium">{check.label}</span></div><span className={`rounded-md px-2 py-1 text-[9.5px] font-semibold ${check.status==="ready"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{check.status==="ready"?"Hazır":check.status==="not_configured"?"Yapılandırılmadı":"Kontrol et"}</span></div>)}</div></section>
      <section className="enterprise-card overflow-hidden"><div className="border-b border-slate-200 px-5 py-4 dark:border-slate-800"><p className="enterprise-eyebrow">Türkiye bağlayıcıları</p><h2 className="mt-1 text-sm font-semibold">SGK · Logo · Mikro · Netsis</h2></div><div className="grid gap-3 p-4 sm:grid-cols-2">{PROVIDERS.map(provider=>{const state=data?.connectors[provider.key];return <article key={provider.key} className="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><FileCheck2 className="h-4 w-4 text-[#2f6664]"/><p className="text-xs font-semibold">{provider.label}</p></div><p className="mt-2 text-[10.5px] leading-4 text-slate-500">{provider.text}</p></div><span className={`h-2 w-2 shrink-0 rounded-full ${state?.enabled?"bg-emerald-500":"bg-slate-300"}`}/></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 dark:border-slate-800"><span className="text-[10px] text-slate-400">Mod: {state?.mode||"manual"}</span><button disabled={!SAAS_DATA_MODE||saving===provider.key} onClick={()=>void toggle(provider.key)} className={`h-8 rounded-lg px-3 text-[10.5px] font-semibold disabled:cursor-not-allowed disabled:opacity-45 ${state?.enabled?"border border-slate-200 text-slate-600":"bg-[#2f6664] text-white"}`}>{state?.enabled?"Devre dışı bırak":"Hazır olarak işaretle"}</button></div></article>})}</div></section>
    </div>
    <div className="rounded-lg border border-[#cbdad8] bg-[#f1f6f5] px-4 py-3 text-[10.5px] leading-5 text-[#315f5c] dark:border-[#294643] dark:bg-[#172b2a] dark:text-[#a9cfcb]">{data?.notice||"Uyum katmanı hazırlanıyor."} Bağlayıcıyı “hazır” olarak işaretlemek gerçek dış servis kimlik bilgisi saklamaz ve canlı gönderim başlatmaz.</div>
  </div>;
}
function Metric({icon:Icon,label,value}:{icon:typeof ShieldCheck;label:string;value:string|number}){return <div className="enterprise-card p-4"><div className="flex items-center justify-between"><p className="text-xs text-slate-500">{label}</p><Icon className="h-4 w-4 text-slate-400"/></div><p className="mt-3 text-xl font-semibold">{value}</p></div>}
