"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Briefcase, Plus, Sparkles, UserPlus } from "lucide-react";
import { POSITIONS } from "../../data/jobData";
import { getStorageData, setStorageData, STORAGE_KEYS } from "../../utils/storage";

const STAGES = ["Başvuru","Ön Eleme","Test","Mülakat","Teklif","İşe Alındı","Reddedildi"] as const;
type CandidateStage=(typeof STAGES)[number];
interface Candidate { id:string|number; name:string; role:string; email?:string; phone?:string; status?:CandidateStage; createdAt?:string; type?:string; raw_scores?:Record<string,number>; [key:string]:any }

export default function IseAlimPage(){
  const[candidates,setCandidates]=useState<Candidate[]>([]);const[assessments,setAssessments]=useState<any[]>([]);const[selectedId,setSelectedId]=useState<string|number|undefined>();const[showNew,setShowNew]=useState(false);const[form,setForm]=useState({name:"",role:"",email:"",phone:""});const[ai,setAi]=useState<any>(null);const[aiLoading,setAiLoading]=useState(false);
  const reload=()=>{const stored=getStorageData<any[]>(STORAGE_KEYS.CANDIDATES,[]).filter(c=>c.type!=="Mevcut Çalışan");setCandidates(stored.map((c,index)=>({...c,id:c.id??`cand-${index}`,status:(c.status||"Başvuru") as CandidateStage,createdAt:c.createdAt||c.date||new Date().toISOString()})));setAssessments(getStorageData<any[]>(STORAGE_KEYS.ASSESSMENTS,[]));};
  useEffect(()=>reload(),[]);useEffect(()=>{if(selectedId===undefined&&candidates.length)setSelectedId(candidates[0].id)},[candidates,selectedId]);
  const selected=candidates.find(c=>c.id===selectedId);const assessment=selected?assessments.find(a=>a.subjectType==="candidate"&&(String(a.subjectId)===String(selected.id)||a.subjectName===selected.name)):null;
  const legacyScores=selected?.raw_scores;const scores=assessment?.scores||legacyScores||{};const scoreValues=Object.values(scores).map(Number).filter(Number.isFinite);const testScore=scoreValues.length?scoreValues.reduce((a,b)=>a+b,0)/scoreValues.length:null;
  const save=(next:Candidate[])=>{setCandidates(next);setStorageData(STORAGE_KEYS.CANDIDATES,next);window.dispatchEvent(new CustomEvent("candidatesUpdated"));};
  const add=(e:FormEvent)=>{e.preventDefault();if(!form.name.trim()||!form.role||!form.email.trim())return;const item:Candidate={id:`cand-${Date.now()}`,name:form.name.trim(),role:form.role,email:form.email.trim(),phone:form.phone.trim(),status:"Başvuru",createdAt:new Date().toISOString(),type:"Aday"};save([item,...candidates]);setSelectedId(item.id);setForm({name:"",role:"",email:"",phone:""});setShowNew(false);};
  const move=(id:string|number,status:CandidateStage)=>save(candidates.map(c=>c.id===id?{...c,status}:c));
  const requestAI=async()=>{if(!selected)return;setAiLoading(true);setAi(null);try{const response=await fetch("/api/ai/hr-recommendation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"recruitment",context:{candidate:{name:selected.name,role:selected.role,status:selected.status},testScore,assessmentAvailable:Boolean(assessment||legacyScores),evidenceNotice:"Test skoru yalnızca bir veri noktasıdır; nihai işe alım kararı üretilmemelidir."}})});setAi(await response.json())}catch{setAi({mode:"rules",recommendation:"Yetkinlik testi yalnızca bir veri noktasıdır. Ön eleme, deneyim, teknik/iş örneği, yapılandırılmış mülakat ve rol gereksinimlerini birlikte değerlendirin."})}finally{setAiLoading(false)}};
  return <div className="space-y-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-violet-600">Aday karar akışı</p><h1 className="mt-1 text-2xl font-semibold">İşe Alım</h1><p className="mt-1 max-w-4xl text-sm text-slate-500">Artık yalnızca testi tamamlayanlar değil, tüm adaylar ATS'de görünür. Akış: Başvuru → Ön Eleme → Test → Mülakat → Teklif → İşe Alındı / Reddedildi.</p></div><button onClick={()=>setShowNew(true)} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="mr-1 inline h-4 w-4"/>Başvuru ekle</button></div>
  <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-7">{STAGES.map(stage=><div key={stage} className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{stage}</p><p className="mt-2 text-2xl font-semibold">{candidates.filter(c=>c.status===stage).length}</p></div>)}</div>
  <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex min-w-max gap-3">{STAGES.map(stage=><div key={stage} className="w-[250px]"><div className="mb-2 flex items-center justify-between"><h2 className="text-xs font-semibold text-slate-600">{stage}</h2><span className="text-[10px] text-slate-400">{candidates.filter(c=>c.status===stage).length}</span></div><div className="space-y-2">{candidates.filter(c=>c.status===stage).map(c=><button key={c.id} onClick={()=>{setSelectedId(c.id);setAi(null)}} className={`w-full rounded-xl border bg-white p-3 text-left shadow-sm ${selectedId===c.id?"border-violet-400 ring-2 ring-violet-100":"border-slate-200"}`}><p className="text-sm font-semibold">{c.name}</p><p className="mt-1 text-xs text-slate-500">{c.role}</p><p className="mt-2 text-[10px] text-slate-400">{c.email||"E-posta yok"}</p></button>)}</div></div>)}</div></div>
  {selected&&<div className="grid gap-5 xl:grid-cols-[1fr_380px]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><Briefcase className="h-4 w-4 text-violet-600"/><h2 className="text-lg font-semibold">{selected.name}</h2></div><p className="mt-1 text-xs text-slate-500">{selected.role} · {selected.email}</p></div><select value={selected.status} onChange={e=>move(selected.id,e.target.value as CandidateStage)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm">{STAGES.map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Mini label="Aşama" value={selected.status||"Başvuru"}/><Mini label="Yetkinlik testi" value={testScore!==null?`${testScore.toFixed(1)} / 5`:"Henüz yok"}/><Mini label="Yanıt kalitesi" value={assessment?.responseConsistency?.band||"—"}/></div>{scoreValues.length>0?<div className="mt-5"><h3 className="text-sm font-semibold">Test içgörüsü</h3><p className="mt-1 text-xs text-slate-500">Bu skor yalnızca rol uyum değerlendirmesine girdi sağlar; “kabul/red” kararı değildir.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(scores).slice(0,10).map(([key,value])=><div key={key} className="flex justify-between rounded-xl bg-slate-50 p-3 text-xs"><span>{key}</span><strong>{Number(value).toFixed(1)}</strong></div>)}</div></div>:<div className="mt-5 rounded-xl bg-amber-50 p-4 text-xs text-amber-800">Aday henüz yetkinlik testini tamamlamadı. ATS kaydı yine de süreçte kalır.</div>}<div className="mt-5 flex gap-2"><Link href={`/aday-testi?mode=candidate&candidateId=${selected.id}`} className="rounded-xl bg-violet-50 px-3 py-2 text-xs font-semibold text-violet-700">Test bağlantısı / test ekranı</Link></div></div>
  <div className="rounded-2xl border border-violet-200 bg-violet-50/40 p-5"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-violet-700"/><h2 className="text-sm font-semibold text-violet-950">Karar desteği</h2></div><p className="mt-1 text-xs leading-5 text-violet-800">AI varsa aday hakkında nihai kabul/red kararı üretmez; yalnızca mevcut kanıtı özetler ve bir sonraki doğrulama adımını önerir.</p><button onClick={requestAI} disabled={aiLoading} className="mt-4 w-full rounded-xl bg-violet-700 px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{aiLoading?"Analiz ediliyor...":"Öneri oluştur"}</button>{ai&&<div className="mt-4 rounded-xl bg-white p-4 text-sm leading-6 text-slate-700"><p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-violet-700">{ai.mode==="ai"?"AI Karar Desteği":"Kural Bazlı Öneri"}</p><div className="whitespace-pre-wrap">{ai.recommendation}</div>{ai.note&&<p className="mt-2 text-xs text-slate-400">{ai.note}</p>}</div>}</div></div>}
  {showNew&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><form onSubmit={add} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center gap-2"><UserPlus className="h-4 w-4 text-violet-600"/><h2 className="text-lg font-semibold">Yeni başvuru</h2></div><div className="mt-5 space-y-3"><input placeholder="Ad Soyad" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"><option value="">Pozisyon seçin</option>{POSITIONS.map(p=><option key={p}>{p}</option>)}</select><input type="email" placeholder="E-posta" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"/><input placeholder="Telefon" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowNew(false)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm">Vazgeç</button><button className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">Başvuruyu kaydet</button></div></form></div>}
  </div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
