"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CalendarDays, Clock3, MoreHorizontal, Search, Users } from "lucide-react";
import { getManageableEmployees } from "../../utils/hierarchy";
import { getStorageData, STORAGE_KEYS } from "../../utils/storage";

export default function EkipYonetimiPage(){
  const[user,setUser]=useState<any>(null);const[orgData,setOrgData]=useState<any[]>([]);const[leaveRequests,setLeaveRequests]=useState<any[]>([]);const[history,setHistory]=useState<any[]>([]);const[plans,setPlans]=useState<any[]>([]);const[search,setSearch]=useState("");
  const reload=()=>{setUser(getStorageData(STORAGE_KEYS.CURRENT_USER,null));setOrgData(getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]));setLeaveRequests(getStorageData<any[]>(STORAGE_KEYS.LEAVE_REQUESTS,[]));setHistory(getStorageData<any[]>(STORAGE_KEYS.HISTORY_360,[]));setPlans(getStorageData<any[]>(STORAGE_KEYS.DEVELOPMENT_PLANS,[]));};
  useEffect(()=>{reload();const h=()=>reload();window.addEventListener("dataUpdated",h);return()=>window.removeEventListener("dataUpdated",h)},[]);
  const role=String(user?.role||"").toUpperCase();const team=useMemo(()=>{if(!user)return[];if(role==="CEO"||role==="IK")return orgData;try{return getManageableEmployees(user,orgData)}catch{return[]}},[user,orgData,role]);
  const filtered=team.filter(e=>{const q=search.toLocaleLowerCase("tr-TR");return !q||[e["Ad Soyad"],e.Pozisyon,e.Departman].some(v=>String(v||"").toLocaleLowerCase("tr-TR").includes(q))});
  const pendingLeave=leaveRequests.filter(r=>r.status==="Bekliyor"&&team.some(e=>e["Ad Soyad"]===r.employee)).length;const activePlans=plans.filter(p=>p.status!=="Tamamlandı"&&team.some(e=>e["Ad Soyad"]===p.employee)).length;
  return <div className="space-y-5"><header className="futurehr-page-header"><p className="futurehr-page-eyebrow">Ekip operasyonları</p><h1 className="futurehr-page-title">Ekip</h1><p className="futurehr-page-lede">Bağlı çalışanları ve günlük ekip aksiyonlarını yönetin. Çalışan ana verisi Çalışanlar & Organizasyon'da; kullanıcı hesabı ve yetkiler Kullanıcı & Yetki'de yönetilir.</p></header>
  <div className="grid gap-3 sm:grid-cols-3"><Metric label="Yönetilen çalışan" value={team.length} icon={Users}/><Metric label="Bekleyen izin" value={pendingLeave} icon={CalendarDays}/><Metric label="Aktif gelişim aksiyonu" value={activePlans} icon={Clock3}/></div>
  <div className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 dark:border-slate-800 dark:bg-slate-900"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ekipte ara" className="h-11 flex-1 bg-transparent text-sm outline-none"/></div>
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(employee=>{const name=employee["Ad Soyad"];const lastEval=history.find(h=>(h.Personel||h.target)===name);const employeePlans=plans.filter(p=>p.employee===name&&p.status!=="Tamamlandı").length;const leave=leaveRequests.filter(r=>r.employee===name&&r.status==="Bekliyor").length;const q=`?employeeName=${encodeURIComponent(name)}`;return <article key={employee.id??name} className="enterprise-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">{name}</h2><p className="mt-1 text-xs text-slate-500">{employee.Pozisyon}</p><p className="mt-1 text-[11px] text-slate-400">{employee.Departman}</p></div><div className="flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 text-xs font-semibold text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300">{name.split(" ").slice(0,2).map((p:string)=>p[0]).join("")}</div></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Son perf." value={lastEval?.Performans?Number(lastEval.Performans).toFixed(1):"—"}/><Mini label="Gelişim" value={String(employeePlans)}/><Mini label="İzin talebi" value={String(leave)}/></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 dark:border-slate-800"><Link href={`/organizasyon${q}`} className="text-[11px] font-semibold text-[#2f6664] hover:underline">Çalışanı görüntüle →</Link><details className="relative"><summary className="flex h-8 w-8 cursor-pointer list-none items-center justify-center rounded-lg border border-slate-200 text-slate-500 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800" aria-label={`${name} aksiyonları`}><MoreHorizontal className="h-4 w-4"/></summary><div className="absolute bottom-10 right-0 z-20 min-w-[160px] overflow-hidden rounded-lg border border-slate-200 bg-white py-1 shadow-lg dark:border-slate-700 dark:bg-slate-900"><Link href={`/degerlendirme${q}`} className="block px-3 py-2 text-[11px] font-medium text-slate-700 hover:bg-slate-50 dark:text-slate-200 dark:hover:bg-slate-800">Değerlendir</Link><Link href={`/gelisim${q}`} className="block px-3 py-2 text-[11px] font-medium text-slate-700 hover:bg-slate-50 dark:text-slate-200 dark:hover:bg-slate-800">Gelişim planı</Link><Link href="/izinler" className="block px-3 py-2 text-[11px] font-medium text-slate-700 hover:bg-slate-50 dark:text-slate-200 dark:hover:bg-slate-800">İzinler</Link></div></details></div></article>})}</div>
  {!filtered.length&&<div className="enterprise-card p-10 text-center text-sm text-slate-500">Yönetilebilir çalışan bulunmuyor.</div>}</div>}
function Metric({label,value,icon:Icon}:{label:string;value:number;icon:any}){return <div className="enterprise-card p-4"><div className="flex justify-between"><p className="text-xs text-slate-500">{label}</p><Icon className="h-4 w-4 text-slate-500"/></div><p className="mt-3 text-2xl font-semibold">{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-2.5 dark:bg-slate-800/70"><p className="text-[9px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>}
