"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CalendarDays, ClipboardCheck, Clock3, Search, Users } from "lucide-react";
import { getManageableEmployees } from "../../utils/hierarchy";
import { getStorageData, STORAGE_KEYS } from "../../utils/storage";

export default function EkipYonetimiPage(){
  const[user,setUser]=useState<any>(null);const[orgData,setOrgData]=useState<any[]>([]);const[leaveRequests,setLeaveRequests]=useState<any[]>([]);const[history,setHistory]=useState<any[]>([]);const[plans,setPlans]=useState<any[]>([]);const[search,setSearch]=useState("");
  const reload=()=>{setUser(getStorageData(STORAGE_KEYS.CURRENT_USER,null));setOrgData(getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]));setLeaveRequests(getStorageData<any[]>(STORAGE_KEYS.LEAVE_REQUESTS,[]));setHistory(getStorageData<any[]>(STORAGE_KEYS.HISTORY_360,[]));setPlans(getStorageData<any[]>(STORAGE_KEYS.DEVELOPMENT_PLANS,[]));};
  useEffect(()=>{reload();const h=()=>reload();window.addEventListener("dataUpdated",h);return()=>window.removeEventListener("dataUpdated",h)},[]);
  const role=String(user?.role||"").toUpperCase();const team=useMemo(()=>{if(!user)return[];if(role==="CEO"||role==="IK")return orgData;try{return getManageableEmployees(user,orgData)}catch{return[]}},[user,orgData,role]);
  const filtered=team.filter(e=>{const q=search.toLocaleLowerCase("tr-TR");return !q||[e["Ad Soyad"],e.Pozisyon,e.Departman].some(v=>String(v||"").toLocaleLowerCase("tr-TR").includes(q))});
  const pendingLeave=leaveRequests.filter(r=>r.status==="Bekliyor"&&team.some(e=>e["Ad Soyad"]===r.employee)).length;const activePlans=plans.filter(p=>p.status!=="Tamamlandı"&&team.some(e=>e["Ad Soyad"]===p.employee)).length;
  return <div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-600">Ekip operasyonları</p><h1 className="mt-1 text-2xl font-semibold">Ekip</h1><p className="mt-1 text-sm text-slate-500">Bu ekran bağlı çalışanları ve ekip aksiyonlarını yönetir. Çalışan ana verisi Çalışanlar & Organizasyon'da; kullanıcı hesabı ve yetkiler Kullanıcı & Yetki'de yönetilir.</p></div>
  <div className="grid gap-3 sm:grid-cols-3"><Metric label="Yönetilen çalışan" value={team.length} icon={Users}/><Metric label="Bekleyen izin" value={pendingLeave} icon={CalendarDays}/><Metric label="Aktif gelişim aksiyonu" value={activePlans} icon={Clock3}/></div>
  <div className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 shadow-sm"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ekipte ara" className="h-11 flex-1 bg-transparent text-sm outline-none"/></div>
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(employee=>{const name=employee["Ad Soyad"];const lastEval=history.find(h=>(h.Personel||h.target)===name);const employeePlans=plans.filter(p=>p.employee===name&&p.status!=="Tamamlandı").length;const leave=leaveRequests.filter(r=>r.employee===name&&r.status==="Bekliyor").length;const q=`?employeeName=${encodeURIComponent(name)}`;return <div key={employee.id??name} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">{name}</h2><p className="mt-1 text-xs text-slate-500">{employee.Pozisyon}</p><p className="mt-1 text-[11px] text-slate-400">{employee.Departman}</p></div><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 text-xs font-semibold text-slate-600">{name.split(" ").slice(0,2).map((p:string)=>p[0]).join("")}</div></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Son perf." value={lastEval?.Performans?Number(lastEval.Performans).toFixed(1):"—"}/><Mini label="Gelişim" value={String(employeePlans)}/><Mini label="İzin talebi" value={String(leave)}/></div><div className="mt-4 flex flex-wrap gap-2"><Link href={`/degerlendirme${q}`} className="rounded-lg bg-blue-50 px-2.5 py-2 text-[11px] font-semibold text-blue-700"><ClipboardCheck className="mr-1 inline h-3.5 w-3.5"/>Değerlendir</Link><Link href={`/gelisim${q}`} className="rounded-lg bg-emerald-50 px-2.5 py-2 text-[11px] font-semibold text-emerald-700">Gelişim</Link><Link href="/izinler" className="rounded-lg bg-sky-50 px-2.5 py-2 text-[11px] font-semibold text-sky-700">İzinler</Link></div></div>})}</div>
  {!filtered.length&&<div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">Yönetilebilir çalışan bulunmuyor.</div>}</div>}
function Metric({label,value,icon:Icon}:{label:string;value:number;icon:any}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between"><p className="text-xs text-slate-500">{label}</p><Icon className="h-4 w-4 text-slate-600"/></div><p className="mt-3 text-2xl font-semibold">{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-2.5"><p className="text-[9px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>}
