"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bot, CheckCircle2, Database, Download, EyeOff, FileClock, KeyRound, LockKeyhole, ShieldCheck, Trash2, UserCheck, UsersRound } from "lucide-react";
import { getStorageData, setStorageData, STORAGE_KEYS } from "../../../utils/storage";
import { clearAIGovernanceLog, readAIGovernanceLog, type AIGovernanceEvent } from "@/lib/hr/governanceLog";

const RETENTION_DAYS=365;
type ControlState="active"|"control"|"credentials";
interface Control{ id:string;title:string;state:ControlState;owner:string;evidence:string;detail:string;icon:any; }
function parseDate(value:unknown):Date|null{if(!value)return null;const date=new Date(String(value));return Number.isNaN(date.getTime())?null:date;}
function candidateCreatedAt(candidate:any){return parseDate(candidate?.createdAt||candidate?.created_at||candidate?.applicationDate||candidate?.date||candidate?.Tarih);}
function candidateRetentionUntil(candidate:any){const explicit=parseDate(candidate?.retentionUntil||candidate?.retention_until||candidate?.consentExpiresAt||candidate?.consent_expires_at);if(explicit)return explicit;const created=candidateCreatedAt(candidate);return created?new Date(created.getTime()+RETENTION_DAYS*86400000):null;}
function kindLabel(kind:string){return({recruitment:"İşe Alım",performance:"Performans",talent:"Yetenek",development:"Gelişim",career:"Kariyer",succession:"Halefiyet",copilot:"FutureHR Copilot"} as Record<string,string>)[kind]||kind;}
function formatDate(value:string){try{return new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));}catch{return value;}}

export default function GuvenKvkkPage(){
  const[events,setEvents]=useState<AIGovernanceEvent[]>([]);const[user,setUser]=useState<any>(null);const[candidates,setCandidates]=useState<any[]>([]);const[sso,setSso]=useState<any>(null);const[accessPolicy,setAccessPolicy]=useState<any>(null);
  useEffect(()=>{const refresh=()=>{setEvents(readAIGovernanceLog());setCandidates(getStorageData<any[]>(STORAGE_KEYS.CANDIDATES,[]));setAccessPolicy(getStorageData<any>(STORAGE_KEYS.ACCESS_POLICY,null));};setUser(getStorageData(STORAGE_KEYS.CURRENT_USER,null));refresh();fetch("/api/sso/status",{cache:"no-store"}).then(r=>r.json()).then(setSso).catch(()=>setSso(null));window.addEventListener("futurehrGovernanceLogUpdated",refresh);window.addEventListener("accessPolicyUpdated",refresh);window.addEventListener("dataUpdated",refresh);return()=>{window.removeEventListener("futurehrGovernanceLogUpdated",refresh);window.removeEventListener("accessPolicyUpdated",refresh);window.removeEventListener("dataUpdated",refresh);};},[]);
  const role=String(user?.role||"").toUpperCase();const allowed=role==="CEO"||role==="IK"||role==="ADMIN"||role==="HR_ADMIN";
  const metrics=useMemo(()=>{const aiRuns=events.filter(e=>e.mode==="ai").length,fallbackRuns=events.filter(e=>e.fallbackUsed).length,scores=events.map(e=>e.evidenceScore).filter((v):v is number=>v!==null);return{total:events.length,aiRuns,fallbackRuns,fallbackRate:events.length?Math.round(fallbackRuns/events.length*100):0,averageEvidence:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null};},[events]);
  const retention=useMemo(()=>{const now=Date.now();let dated=0,overdue=0,missingDate=0;candidates.forEach(candidate=>{const expiry=candidateRetentionUntil(candidate);if(!expiry){missingDate+=1;return;}dated+=1;if(expiry.getTime()<now)overdue+=1;});return{total:candidates.length,dated,overdue,missingDate};},[candidates]);
  const controls=useMemo<Control[]>(()=>[
    {id:"rbac",title:"RBAC ve rol bazlı ekran kapsamı",state:"active",owner:"İK + Sistem Yöneticisi",evidence:accessPolicy?"Kurum erişim politikası yüklü":"Varsayılan fail-closed politika",detail:"Ücret, halefiyet, yönetici raporu ve admin alanları route/scope kontrolünden geçer. Yetki yoksa kişi verisinden çıkarım yapılmaz.",icon:UserCheck},
    {id:"sensitive",title:"Hassas ücret / yetenek kapsamı",state:"active",owner:"İK",evidence:"Sensitive scope + role checks",detail:"Kişisel ücret ve yüksek etkili yetenek/halefiyet kararları genel çalışan görünümüne açılmaz; karar sahibi insan olarak kalır.",icon:LockKeyhole},
    {id:"tenant",title:"Tenant izolasyonu",state:"active",owner:"Platform",evidence:"Secure SaaS session + tenant scope",detail:"Production SaaS akışında kullanıcı oturumu tenant kimliğiyle bağlanır; başka tenant verisine istemci parametresiyle geçiş kabul edilmez.",icon:Database},
    {id:"secrets",title:"Connector ve SSO secret yönetimi",state:"active",owner:"Platform / DevOps",evidence:"Server-side environment variables",detail:"Logo/Mikro/Netsis/SAP, PDKS, bordro ve SSO secret değerleri client payloadına veya readiness endpointlerine gönderilmez.",icon:KeyRound},
    {id:"ai_min",title:"AI veri minimizasyonu",state:"active",owner:"FutureHR Intelligence",evidence:`${events.length} gizlilik güvenli audit kaydı`,detail:"Dış modele gönderimden önce ad/e-posta/telefon, korunan özellikler ve yetkisiz ham ücret alanları redakte/anonymize edilir; retrieved data talimat değil kanıt kabul edilir.",icon:EyeOff},
    {id:"pulse",title:"Employee Experience anonimliği",state:"active",owner:"İK Analitik",evidence:"k ≥ 5 anonimlik eşiği",detail:"Yönetim görünümünde küçük gruplar bastırılır; bireysel pulse yanıtı ve yorumları yöneticiye açılmaz.",icon:UsersRound},
    {id:"audit",title:"Audit ve kanıt izi",state:events.length?"active":"control",owner:"İK + İç Kontrol",evidence:events.length?`${events.length} AI governance olayı`:"Henüz demo AI olayı yok",detail:"AI provider/model, karar amacı, Evidence Score, fallback ve gizlilik metadata kaydedilir. Production'da merkezi/immutable audit deposu kurum politikasına göre yapılandırılmalıdır.",icon:Bot},
    {id:"retention",title:"Aday verisi saklama kontrolü",state:retention.overdue||retention.missingDate?"control":"active",owner:"Veri Sorumlusu / İK",evidence:`${retention.overdue} süresi geçmiş · ${retention.missingDate} tarihsiz`,detail:"Demo kontrolü 12 aylık hedef üzerinden veri kalitesi sinyali verir. Gerçek saklama süresi işleme amacı, aydınlatma metni ve kurum hukuk/KVKK politikasıyla belirlenmelidir.",icon:FileClock},
    {id:"sso",title:"SSO fail-closed hesap eşleme",state:sso?.google?.configured||sso?.entra?.configured?"active":"credentials",owner:"IT / IAM",evidence:`Google ${sso?.google?.configured?"hazır":"credential bekliyor"} · Entra ${sso?.entra?.configured?"hazır":"credential bekliyor"}`,detail:"SSO otomatik kullanıcı veya rol oluşturmaz; sağlayıcı tarafından doğrulanmış e-posta aynı tenant içindeki mevcut aktif FutureHR hesabıyla eşleşmelidir.",icon:ShieldCheck},
    {id:"human",title:"Human-in-the-loop yüksek etkili kararlar",state:"active",owner:"Yetkili Yönetici + İK",evidence:"Deterministic output guardrails",detail:"AI işe alma, işten çıkarma, terfi, ücret artışı, disiplin veya halef ataması için nihai kişi kararı üretmez; insan doğrulaması ve gerekçe gerektirir.",icon:CheckCircle2},
  ],[accessPolicy,events,retention,sso]);
  useEffect(()=>{if(!allowed||!controls.length)return;setStorageData(STORAGE_KEYS.KVKK_CONTROL_REGISTER,controls.map(({icon,...control})=>({...control,checkedAt:new Date().toISOString()})));},[allowed,controls]);
  const exportLog=()=>{const payload={exportedAt:new Date().toISOString(),scope:"FutureHR Trust & KVKK technical control register",legalDisclaimer:"Teknik kontrol kaydı hukuki uygunluk sertifikası değildir.",controls:controls.map(({icon,...control})=>control),events};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`futurehr-kvkk-audit-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);};

  if(!allowed)return <div className="enterprise-card mx-auto max-w-3xl p-8 text-center"><LockKeyhole className="mx-auto h-8 w-8 text-slate-300"/><h1 className="mt-3 text-lg font-semibold">Güven & KVKK Merkezi</h1><p className="mt-2 text-sm text-slate-500">Bu görünüm yalnızca yetkili CEO / İK / sistem yönetimi rollerine açıktır.</p></div>;
  const active=controls.filter(c=>c.state==="active").length,controlsNeeded=controls.filter(c=>c.state==="control").length,credentials=controls.filter(c=>c.state==="credentials").length;

  return <div className="mx-auto max-w-7xl space-y-5 pb-8">
    <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="enterprise-eyebrow">Trust · Privacy · Audit · RBAC</p><h1 className="mt-1 text-2xl font-semibold">Güven & KVKK Kontrol Merkezi</h1><p className="mt-1 max-w-4xl text-sm leading-6 text-slate-500">FutureHR'ın veri minimizasyonu, erişim, SSO, audit, saklama ve yüksek etkili AI karar sınırlarını 10 teknik kontrol altında izler.</p></div><div className="flex gap-2"><button onClick={exportLog} className="inline-flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold"><Download className="h-3.5 w-3.5"/>Kontrol + audit dışa aktar</button><button onClick={()=>{if(window.confirm("Demo AI denetim kayıtları temizlensin mi?"))clearAIGovernanceLog();}} disabled={!events.length} className="inline-flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-500 disabled:opacity-40"><Trash2 className="h-3.5 w-3.5"/>Demo AI logunu temizle</button></div></header>
    <div className="rounded-2xl border border-amber-200 bg-amber-50/70 p-4 text-xs leading-5 text-amber-900"><strong>Hukuki sınır:</strong> Bu merkez teknik kontrol/readiness ve denetim kanıtı sağlar; tek başına KVKK uygunluk sertifikası değildir. İşleme amacı, hukuki sebep, aydınlatma/açık rıza ihtiyacı, VERBİS ve saklama-imha politikası kurumun veri sorumlusu/hukuk ekibi tarafından doğrulanmalıdır.</div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={ShieldCheck} label="Aktif kontrol" value={`${active}/10`} note="Kod / politika sinyali"/><Metric icon={AlertTriangle} label="İnceleme gerekli" value={String(controlsNeeded)} note="Veri/operasyon kontrolü"/><Metric icon={KeyRound} label="Credential bekleyen" value={String(credentials)} note="Harici IAM / servis"/><Metric icon={Bot} label="AI audit olayı" value={String(metrics.total)} note={`${metrics.aiRuns} AI · ${metrics.fallbackRuns} fallback`}/><Metric icon={Database} label="Ort. Evidence" value={metrics.averageEvidence!==null?`${metrics.averageEvidence}/100`:"—"} note={`Fallback %${metrics.fallbackRate}`}/></div>

    <section className="grid gap-3 lg:grid-cols-2">{controls.map((control,index)=>{const Icon=control.icon;return <div key={control.id} className="enterprise-card p-4"><div className="flex items-start gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${control.state==="active"?"bg-emerald-50 text-emerald-600":control.state==="credentials"?"bg-amber-50 text-amber-600":"bg-blue-50 text-blue-600"}`}><Icon className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-[9px] font-bold text-slate-400">{String(index+1).padStart(2,"0")}</span><h2 className="text-sm font-semibold">{control.title}</h2><span className={`rounded-full px-2 py-0.5 text-[8px] font-bold ${control.state==="active"?"bg-emerald-50 text-emerald-700":control.state==="credentials"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700"}`}>{control.state==="active"?"Aktif":control.state==="credentials"?"Credential bekliyor":"Kontrol gerekli"}</span></div><p className="mt-1 text-[10.5px] leading-5 text-slate-500">{control.detail}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[9px] text-slate-400"><span><strong className="text-slate-500">Sahip:</strong> {control.owner}</span><span><strong className="text-slate-500">Kanıt:</strong> {control.evidence}</span></div></div></div></div>})}</section>

    <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="enterprise-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold">AI Karar Desteği Denetim Defteri</h2><p className="mt-1 text-[11px] text-slate-500">Kişi adı veya ham prompt saklamadan provider/model, amaç, Evidence Score, fallback ve privacy metadata izlenir.</p></div>{events.length?<div className="max-h-[430px] overflow-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-[9px] uppercase tracking-[.08em] text-slate-400"><tr><th className="px-4 py-3">Zaman</th><th className="px-4 py-3">Amaç</th><th className="px-4 py-3">Provider/model</th><th className="px-4 py-3">Mode</th><th className="px-4 py-3">Evidence</th><th className="px-4 py-3">Privacy</th></tr></thead><tbody className="divide-y divide-slate-100">{events.slice(0,50).map(event=><tr key={event.id}><td className="whitespace-nowrap px-4 py-3 text-[10px]">{formatDate(event.timestamp)}</td><td className="px-4 py-3 font-semibold">{kindLabel(event.decisionKind)}</td><td className="px-4 py-3"><p>{event.provider}</p><p className="max-w-44 truncate text-[9px] text-slate-400">{event.model}</p></td><td className="px-4 py-3">{event.mode}{event.fallbackUsed?" · fallback":""}</td><td className="px-4 py-3 font-semibold">{event.evidenceScore!==null?`${event.evidenceScore}/100`:"—"}</td><td className="px-4 py-3 text-[9px]">PII redacted{event.privacy.employeeExperienceAggregated?` · EX aggregate k≥${event.privacy.anonymityThreshold||5}`:""}</td></tr>)}</tbody></table></div>:<div className="px-5 py-10 text-center"><Bot className="mx-auto h-7 w-7 text-slate-300"/><p className="mt-2 text-sm font-medium">Henüz AI audit kaydı yok</p><p className="mt-1 text-xs text-slate-400">FutureHR Intelligence çalıştığında gizlilik güvenli olay kaydı burada oluşur.</p></div>}</div>
      <div className="enterprise-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Aday saklama veri kalitesi</h2><p className="mt-1 text-[10px] leading-5 text-slate-500">12 aylık değer yalnız demo kontrol varsayımıdır; hukuki saklama süresi değildir.</p></div><FileClock className="h-5 w-5 text-indigo-500"/></div><div className="mt-4 grid grid-cols-2 gap-3"><SmallStat label="Aday" value={retention.total}/><SmallStat label="Tarihli" value={retention.dated}/><SmallStat label="Süresi geçmiş" value={retention.overdue} danger={retention.overdue>0}/><SmallStat label="Tarih eksik" value={retention.missingDate} danger={retention.missingDate>0}/></div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-[10px] leading-5 text-slate-500"><strong>Production kapısı:</strong> Saklama-imha job'ı, veri sahibi başvuru süreci, audit deposu, yedek imha politikası ve kurumun güncel KVKK envanteri ayrıca doğrulanmalıdır.</div></div></section>
  </div>;
}

function Metric({icon:Icon,label,value,note}:{icon:any;label:string;value:string;note:string}){return <div className="enterprise-card p-4"><Icon className="h-4 w-4 text-indigo-500"/><p className="mt-3 text-[9px] font-bold uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p><p className="mt-1 text-[9px] text-slate-400">{note}</p></div>}
function SmallStat({label,value,danger=false}:{label:string;value:number;danger?:boolean}){return <div className={`rounded-xl border p-3 ${danger?"border-rose-200 bg-rose-50":"border-slate-200 bg-slate-50"}`}><p className="text-[9px] font-bold uppercase text-slate-400">{label}</p><p className={`mt-1 text-lg font-semibold ${danger?"text-rose-700":""}`}>{value}</p></div>}
