"use client";

import { Suspense, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, CheckCircle2, Clock, FileText, ShieldCheck } from "lucide-react";
import { CANDIDATE_QUESTIONS } from "../../data/questions";
import { getManageableEmployees } from "../../utils/hierarchy";
import { getStorageData, setStorageData, STORAGE_KEYS } from "../../utils/storage";
import { calculateResponseConsistency } from "../../../lib/hr/assessmentQuality";

const COMPETENCIES:Record<string,string>={DIG:"Dijital Okuryazarlık",ANA:"Analitik Düşünme",RES:"Sonuç Odaklılık",DET:"Detaylara Özen",LRN:"Sürekli Öğrenme",ETH:"Etik ve Uyum",DIS:"Öz-Disiplin",STR:"Stratejik Bakış",TEA:"Takım Çalışması",COM:"İletişim Becerileri"};
const DURATION=45*60;

function AssessmentPage(){
  const params=useSearchParams();const router=useRouter();const mode=params.get("mode")==="candidate"?"candidate":"employee";const candidateId=params.get("candidateId");
  const[user,setUser]=useState<any>(null);const[orgData,setOrgData]=useState<any[]>([]);const[candidates,setCandidates]=useState<any[]>([]);const[selectedPerson,setSelectedPerson]=useState("");const[active,setActive]=useState(false);const[startedAt,setStartedAt]=useState<number|null>(null);const[remaining,setRemaining]=useState(DURATION);const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<Record<number,number>>({});const[result,setResult]=useState<any>(null);
  useEffect(()=>{const u=getStorageData(STORAGE_KEYS.CURRENT_USER,null);setUser(u);const org=getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]);setOrgData(org);const cs=getStorageData<any[]>(STORAGE_KEYS.CANDIDATES,[]).filter(c=>c.type!=="Mevcut Çalışan");setCandidates(cs);if(mode==="candidate"&&candidateId){const c=cs.find(x=>String(x.id)===String(candidateId));if(c)setSelectedPerson(c.name)}},[mode,candidateId]);
  const role=String(user?.role||"").toUpperCase();const availablePeople=useMemo(()=>{if(mode==="candidate")return[];if(!user)return[];const self=orgData.find(e=>e["Ad Soyad"]===(user.name||user.username));if(role==="EMPLOYEE"||role==="PERSONEL")return self?[self]:[];if(role==="CEO"||role==="IK")return orgData;try{return getManageableEmployees(user,orgData)}catch{return[]}},[mode,user,orgData,role]);
  useEffect(()=>{if(mode==="employee"&&!selectedPerson&&availablePeople.length){const self=availablePeople.find(e=>e["Ad Soyad"]===(user?.name||user?.username));setSelectedPerson((self||availablePeople[0])["Ad Soyad"])}},[mode,availablePeople,selectedPerson,user]);
  const candidate=mode==="candidate"?(candidateId?candidates.find(c=>String(c.id)===String(candidateId)):candidates.find(c=>c.name===selectedPerson)):null;const employee=orgData.find(e=>e["Ad Soyad"]===selectedPerson);const subjectRole=mode==="candidate"?candidate?.role:employee?.Pozisyon;
  const questions=useMemo(()=>CANDIDATE_QUESTIONS.slice(0,130),[]);const current=questions[index];
  useEffect(()=>{if(!active||!startedAt)return;const timer=setInterval(()=>{const next=Math.max(0,DURATION-Math.floor((Date.now()-startedAt)/1000));setRemaining(next);if(next===0)clearInterval(timer)},1000);return()=>clearInterval(timer)},[active,startedAt]);
  const canStart=Boolean(selectedPerson&&subjectRole);
  const start=()=>{if(!canStart)return;setActive(true);setStartedAt(Date.now());setRemaining(DURATION);setIndex(0);setAnswers({});setResult(null)};
  const finish=()=>{if(!selectedPerson||!subjectRole)return;const missing=questions.filter(q=>!answers[q.id]);if(missing.length&&remaining>0){alert(`${missing.length} soru henüz cevaplanmadı.`);return}const scores:Record<string,number>={};Object.entries(COMPETENCIES).forEach(([code,label])=>{const values=questions.filter(q=>q.category===code).map(q=>{let v=answers[q.id]||3;if(q.type==="R")v=6-v;return v});if(values.length)scores[label]=Math.round(values.reduce((a,b)=>a+b,0)/values.length*100)/100});const consistencyAnswers=questions.filter(q=>q.category==="LIE").map(q=>answers[q.id]||3);const consistency=calculateResponseConsistency(consistencyAnswers);const assessment={id:`assessment-${Date.now()}`,subjectType:mode,subjectId:mode==="candidate"?(candidate?.id||candidateId):(employee?.id||selectedPerson),subjectName:selectedPerson,role:subjectRole,scores,responseConsistency:consistency,completedAt:new Date().toISOString(),durationSeconds:startedAt?Math.round((Date.now()-startedAt)/1000):null,questionCount:questions.length};const existing=getStorageData<any[]>(STORAGE_KEYS.ASSESSMENTS,[]);setStorageData(STORAGE_KEYS.ASSESSMENTS,[assessment,...existing]);if(mode==="candidate"){const nextCandidates=candidates.map(c=>String(c.id)===String(candidate?.id||candidateId)?{...c,status:c.status==="Başvuru"||c.status==="Ön Eleme"?"Test":c.status,testCompletedAt:new Date().toISOString()}:c);setStorageData(STORAGE_KEYS.CANDIDATES,nextCandidates);window.dispatchEvent(new CustomEvent("candidatesUpdated"))}window.dispatchEvent(new CustomEvent("dataUpdated"));setResult(assessment);setActive(false)};
  if(result)return <div className="mx-auto max-w-3xl space-y-5"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600"/><h1 className="mt-3 text-xl font-semibold text-emerald-950">Değerlendirme tamamlandı</h1><p className="mt-1 text-sm text-emerald-800">{result.subjectName} · {result.role}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold">Yetkinlik sonuçları</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{Object.entries(result.scores).map(([label,value])=><div key={label} className="flex justify-between rounded-xl bg-slate-50 p-3 text-xs"><span>{label}</span><strong>{Number(value).toFixed(1)} / 5</strong></div>)}</div><div className="mt-4 rounded-xl bg-blue-50 p-4"><p className="text-xs font-semibold text-blue-950">Yanıt tutarlılığı: %{result.responseConsistency.score} · {result.responseConsistency.band}</p><p className="mt-1 text-xs leading-5 text-blue-800">{result.responseConsistency.note}</p></div></div><button onClick={()=>router.push(mode==="candidate"?"/ise-alim":"/yetenek-matrisi")} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Sonuç ekranına dön</button></div>;
  if(active&&current){const minutes=Math.floor(remaining/60),seconds=remaining%60,progress=(index+1)/questions.length*100;return <div className="mx-auto max-w-4xl space-y-4"><div className="sticky top-0 z-20 flex items-center justify-between rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-sm backdrop-blur"><div><p className="text-xs text-slate-500">{selectedPerson} · {subjectRole}</p><p className="mt-1 text-sm font-semibold">Soru {index+1} / {questions.length}</p></div><div className={`flex items-center gap-2 rounded-xl px-3 py-2 font-mono text-sm font-semibold ${remaining<300?"bg-red-50 text-red-700":"bg-indigo-50 text-indigo-700"}`}><Clock className="h-4 w-4"/>{String(minutes).padStart(2,"0")}:{String(seconds).padStart(2,"0")}</div></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-indigo-600" style={{width:`${progress}%`}}/></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2 text-xs font-semibold text-indigo-600"><FileText className="h-4 w-4"/>Yetkinlik değerlendirmesi</div><h2 className="mt-4 text-base font-semibold leading-7 text-slate-900">{current.text}</h2><div className="mt-6 space-y-2">{[{v:1,l:"Kesinlikle Katılmıyorum"},{v:2,l:"Katılmıyorum"},{v:3,l:"Kararsızım"},{v:4,l:"Katılıyorum"},{v:5,l:"Kesinlikle Katılıyorum"}].map(o=><button key={o.v} onClick={()=>setAnswers({...answers,[current.id]:o.v})} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left text-sm ${answers[current.id]===o.v?"border-indigo-500 bg-indigo-50 text-indigo-900":"border-slate-200 hover:bg-slate-50"}`}><span>{o.l}</span><span className="font-mono text-xs">{o.v}</span></button>)}</div><div className="mt-6 flex items-center justify-between"><button disabled={index===0} onClick={()=>setIndex(Math.max(0,index-1))} className="rounded-xl border border-slate-200 px-4 py-2 text-sm disabled:opacity-30">Önceki</button>{index===questions.length-1||remaining===0?<button onClick={finish} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Değerlendirmeyi tamamla</button>:<button disabled={!answers[current.id]} onClick={()=>setIndex(index+1)} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-30">Sonraki</button>}</div></div></div>}
  return <div className="mx-auto max-w-4xl space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-indigo-600">Yetkinlik değerlendirmesi</p><h1 className="mt-1 text-2xl font-semibold">Yetkinlik Testi</h1><p className="mt-1 text-sm text-slate-500">130 soru · 45 dakika. Çalışan değerlendirmeleri Assessments alanına, aday kimliği Candidates alanına kaydedilir; iki veri modeli artık karışmaz.</p></div><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-indigo-600"/><h2 className="text-sm font-semibold">Değerlendirilecek kişi</h2></div>{mode==="employee"?<div className="mt-4"><label className="text-xs font-medium text-slate-500">Çalışan<select value={selectedPerson} onChange={e=>setSelectedPerson(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-2.5 text-sm">{availablePeople.map((p:any)=><option key={p.id??p["Ad Soyad"]}>{p["Ad Soyad"]}</option>)}</select></label><p className="mt-2 text-xs text-slate-400">Personel yalnızca kendi adına test başlatabilir. Yönetici/direktör yalnızca hiyerarşik kapsamındaki çalışanları seçebilir; CEO/İK tüm çalışanları görebilir.</p></div>:candidate?<div className="mt-4 rounded-xl bg-violet-50 p-4"><p className="text-sm font-semibold text-violet-950">{candidate.name}</p><p className="mt-1 text-xs text-violet-800">{candidate.role} · {candidate.email}</p></div>:<div className="mt-4 rounded-xl bg-red-50 p-4 text-xs text-red-700">Geçerli aday kaydı bulunamadı. Testi İşe Alım ekranından başlatın.</div>}<button onClick={start} disabled={!canStart} className="mt-5 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Testi başlat</button></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-amber-700"/><h2 className="text-sm font-semibold text-amber-950">Yanıt kalitesi notu</h2></div><p className="mt-2 text-xs leading-5 text-amber-800">Eski “manipülasyon skoru” kaldırıldı. Yeni “yanıt tutarlılığı” göstergesi yalnızca cevap örüntüsünün veri kalitesine dair yardımcı sinyaldir; yalan tespiti, dürüstlük ölçümü veya tek başına işe alım/terfi kriteri değildir.</p></div></div></div>}

export default function AdayTestiPage(){return <Suspense fallback={<div className="p-6 text-sm text-slate-500">Test yükleniyor...</div>}><AssessmentPage/></Suspense>}
