"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { KeyRound, Shield, Trash2, UserPlus, Users } from "lucide-react";
import { getStorageData, setStorageData, STORAGE_KEYS } from "../../utils/storage";
import { useNotifications } from "../../../context/NotificationContext";

function normalizeUsername(name:string){return name.toLocaleLowerCase("tr-TR").replace(/ı/g,"i").replace(/ğ/g,"g").replace(/ü/g,"u").replace(/ş/g,"s").replace(/ö/g,"o").replace(/ç/g,"c").replace(/[^a-z0-9]/g,"")}
function randomPassword(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*";return Array.from({length:12},()=>chars[Math.floor(Math.random()*chars.length)]).join("")}

export default function AdminPage(){
  const{showToast}=useNotifications();const[currentUser,setCurrentUser]=useState<any>(null);const[orgData,setOrgData]=useState<any[]>([]);const[users,setUsers]=useState<Record<string,any>>({});const[selectedEmployee,setSelectedEmployee]=useState("");const[username,setUsername]=useState("");const[password,setPassword]=useState("");const[role,setRole]=useState("PERSONEL");
  const reload=()=>{setCurrentUser(getStorageData(STORAGE_KEYS.CURRENT_USER,null));setOrgData(getStorageData<any[]>(STORAGE_KEYS.ORG_CHART,[]));setUsers(getStorageData<Record<string,any>>(STORAGE_KEYS.USERS,{}));};useEffect(()=>reload(),[]);
  const currentRole=String(currentUser?.role||"").toUpperCase();const allowed=currentRole==="CEO"||currentRole==="IK"||process.env.NODE_ENV==="development";
  const accountNames=useMemo(()=>new Set(Object.values(users).map((u:any)=>u.name).filter(Boolean)),[users]);const withoutAccount=orgData.filter(e=>!accountNames.has(e["Ad Soyad"]));
  const selectEmployee=(name:string)=>{setSelectedEmployee(name);const employee=orgData.find(e=>e["Ad Soyad"]===name);setUsername(`${normalizeUsername(name)}${Math.floor(1000+Math.random()*9000)}`);setPassword(randomPassword());const p=String(employee?.Pozisyon||"").toLocaleLowerCase("tr-TR");setRole(/direktör|director/.test(p)?"DIRECTOR":/müdür|manager|lider/.test(p)?"MANAGER":"PERSONEL")};
  const save=(e:FormEvent)=>{e.preventDefault();if(!selectedEmployee||!username||!password)return;if(users[username])return showToast("Bu kullanıcı adı zaten var.","error");const employee=orgData.find(x=>x["Ad Soyad"]===selectedEmployee);const next={...users,[username]:{username,password,name:selectedEmployee,role,dept:employee?.Departman||"",department:employee?.Departman||"",position:employee?.Pozisyon||"",active:true,createdAt:new Date().toISOString()}};setUsers(next);setStorageData(STORAGE_KEYS.USERS,next);showToast("Demo kullanıcı hesabı oluşturuldu.","success");setSelectedEmployee("");setUsername("");setPassword("")};
  const toggle=(key:string)=>{const next={...users,[key]:{...users[key],active:users[key].active===false?true:false}};setUsers(next);setStorageData(STORAGE_KEYS.USERS,next)};const remove=(key:string)=>{if(!confirm("Bu demo kullanıcı hesabı silinsin mi? Çalışan kaydı silinmez."))return;const next={...users};delete next[key];setUsers(next);setStorageData(STORAGE_KEYS.USERS,next)};
  if(!allowed)return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">Kullanıcı ve yetki yönetimine yalnızca CEO / İK erişebilir.</div>;
  return <div className="space-y-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-600">Hesap & erişim yönetişimi</p><h1 className="mt-1 text-2xl font-semibold">Kullanıcı & Yetki Yönetimi</h1><p className="mt-1 max-w-4xl text-sm text-slate-500">Çalışan burada oluşturulmaz; çalışan ana verisi Çalışanlar & Organizasyon'dan gelir. Bu ekran yalnızca demo kullanıcı hesabı ve rol erişimini yönetir.</p></div><Link href="/ayarlar/roller" className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white"><Shield className="mr-1 inline h-4 w-4"/>Rol izin matrisi</Link></div>
  <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-800"><strong>Demo güvenlik notu:</strong> Bu sürümde kimlik doğrulama localStorage tabanlıdır. Gerçek sunucu tabanlı authentication devreye alındığında parolalar istemci tarafında tutulmayacak ve bu ekran backend kimlik/rol servisine bağlanacaktır.</div>
  <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><UserPlus className="h-4 w-4 text-slate-700"/><h2 className="text-sm font-semibold">Çalışana hesap ata</h2></div><div className="mt-4 space-y-3"><select value={selectedEmployee} onChange={e=>selectEmployee(e.target.value)} className="w-full rounded-xl border border-slate-200 p-2.5 text-sm"><option value="">Çalışan seçin</option>{withoutAccount.map(e=><option key={e.id??e["Ad Soyad"]}>{e["Ad Soyad"]}</option>)}</select><label className="block text-xs font-medium text-slate-500">Kullanıcı adı<input value={username} onChange={e=>setUsername(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-2.5 text-sm"/></label><label className="block text-xs font-medium text-slate-500">Geçici parola<div className="mt-1 flex gap-2"><input value={password} onChange={e=>setPassword(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-200 p-2.5 text-sm"/><button type="button" onClick={()=>setPassword(randomPassword())} className="rounded-xl border border-slate-200 px-3"><KeyRound className="h-4 w-4"/></button></div></label><label className="block text-xs font-medium text-slate-500">Rol<select value={role} onChange={e=>setRole(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-2.5 text-sm"><option>PERSONEL</option><option>MANAGER</option><option>DIRECTOR</option><option>IK</option></select></label><button className="w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Hesabı oluştur</button></div></form>
  <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-slate-600"/><h2 className="text-sm font-semibold">Kullanıcı hesapları</h2></div><span className="text-xs text-slate-400">{Object.keys(users).length} hesap</span></div><div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Çalışan</th><th>Kullanıcı</th><th>Rol</th><th>Departman</th><th>Durum</th><th></th></tr></thead><tbody>{Object.entries(users).map(([key,u]:any)=><tr key={key}><td>{u.name||"—"}</td><td className="font-mono text-xs">{key}</td><td>{u.role||"—"}</td><td>{u.dept||u.department||"—"}</td><td><button onClick={()=>toggle(key)} className={`rounded-full px-2 py-1 text-[10px] font-semibold ${u.active===false?"bg-slate-100 text-slate-500":"bg-emerald-50 text-emerald-700"}`}>{u.active===false?"Pasif":"Aktif"}</button></td><td className="text-right"><button onClick={()=>remove(key)} className="rounded-lg p-2 text-red-500 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div></div></div></div>}
